### ISSUE TITLE
o.expr doesn't issue warning/error for bogus parameter names

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#10]
if you try to construct a new bundle parameter via assign(), i would expect to get some information that o.expr doesn't know what you'd like to do when you don't issue a slash (/) first.  Here's an example:

<pre><code>
----------begin_max5_patcher----------
499.3oc4V0zabBCD8LQJ+Gr7oFIJKFX+n8Vuzy8dHJxK3rwor1HaSJMQ8+dr
GCaX2nrKQIYUh5E+DyXF+7yiev8mdR.dorkownuiNGEDbuMR.DyEInOP.dMs
snhpgIhkQqYZMcECG1k1vZMPpIDTNdIIG6fTOj3gLGHlHX+4.SYSUq3BVgrQ
.kNoOprwTwLl+Vy7rFiQWzm6JovHnqgL3en3zpMEiW549xa9JYSvZpo3ZtX0
kJVgwWtjYjnogHRVbTrElBPZVT71qhleGrJjDa9ApPgrRp7UBdyGGHCKgnYM
WX2F5s1Z1n9cGDl.Q+2om3PKDdDNfvucpbxdU44SAcEFIIoNHI9SkHaajsay
mpvxHVasBYmFek3K444XWOuCyyCQSHm87Z7Oapp9Es32LyKVsSGgZO2KQYyG
uZukDR93zmNvk302oltXehW5rm5G7IqU8CgeP521mJ24y9egevQvNHK9vhcu
cP16qcfupvGy28+L.p4RritpkMphdUnycCMfdkLsgKnFtTLXR1OqiHONoq4k
kLH+F5Wx0zkULPlhe9C5QSqjwPqc39QfVtC+QvqEGc8xYAbXhsK8egDqqeiV
WeKSo6JsmS1Kr23MJlE5elK7O66kwJ1s79WYtODUYu8XrWcZT96bsKlgsYfE
zN7.9cSfyA
-----------end_max5_patcher-----------
</code></pre>

</code></pre>

**Comment by maccallum** [comment]
this is still an issue!

**Comment by maccallum** [comment]
This prints an error now
