### ISSUE TITLE
Folder organization 

### ISSUE THREAD

**Issue by maccallum** [CNMAT/CNMAT-odot#149]
Thinking through the folder organization a little bit, it seems to me that if there are patches that we're uncommitted to for whatever reason (API or whatever), we should make a stronger statement about them and put them in a folder that will not automatically end up in the search path. I propose that we keep the experimental folder, but that we move unstable out of the patchers folder. We would then recommend that users of odot never put experimental in their search path---the contents are highly volatile and can break, change, or disappear at any time without warning. The contents of experimental are a place for us to collaborate. Maybe they don't even go out with the release. 

As patches in experimental become more generally useful, they move into unstable. We can recommend that users of odot put unstable into their search path if they want, but with the understanding that the API and behavior of the things in there may change, but that we've committed to the basic idea of the patch. I would propose that moving something into unstable represents a certain level of commitment and that a drastic change such as a name change would mean that we have to not just change the name, but move a copy with the old name into the deprecated folder which people can also put in their search path to manage the upgrade of legacy patches.

Finally, when we're reasonably satisfied with patches in unstable, they move into patchers. 

I guess my only real suggestion for action here is to move unstable out of patchers and possibly stop including experimental with the release. If we do the latter, we may need to move some things from experimental into unstable.

Thoughts?

**Comment by ramagottfried** [comment]
Coming back to this topic after a long time, but it's still an important issue to try to get as right as we can.

I'm thinking, we should have some kind of system for moving objects out of the `dev` folder after some time (years?). When does an object move out of the dev folder? I suppose this points to setting up some object testing guidelines.

Another thought is that the word `dev` implies that it's being worked on and gradually tested and improved but not quite done yet, vs `experimental` which to me suggests it might change drastically. 

For object lifespan we currently we have, `dev`, `externals`, and `deprecated`. 

I wonder if we need another folder, or maybe `staging` or `beta`, where we put objects that are *pretty much* done, but still in testing before they are officially approved to be moved to `externals` (which of course doesn't mean they're bug free!). For example, objects in this category could print a warning on load, and also have a clearly stated `beta` flag in the help patch, etc. while being tested.

**Comment by maccallum** [comment]
"Coming back to this topic after a long time..."

I think the folder structure is ok as is. One of the complaints is that it's annoying to have to let people know that they have to add the dev folder to their search paths, but I think that by doing it, you're agreeing to work with things that may change in the future. If anything, I'd rename it something like `future`. At one point, I believe it was `unstable`, but that sounds like the objects are crashy, which they're not. 

There's some discussion of this in #402, but I don't think it's a good idea to move everything from dev into the main folders. That said, there are a few critical objects that I don't see changing in the future that should be reviewed and moved, like `o.downcast`, and the slip objects. 

I'm going to close this, but I've opened a new issue to review the contents of the dev folder and move as much as possible into the main folders (#405)
