### ISSUE TITLE
tools for transcoding jitter matrices and o. messages

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#260]
Original Email from Adrian:

"The feature modeling with cv.jit is done with small jitter matrices and a lot of jit.iter
Someone with more time on their hands than I will perhaps be motivated to write some general
tools for transcoding of jitter matrices and 'o.' messages.
The other half of this project is to wrap the video composition workflow of jitter in 'o.'"

**Comment by adrianfreed** [comment]
Was this closed because it is done or abandoned?

**Comment by equilet** [comment]
It was abandoned for the moment, but yes I think we should keep it open.

**Comment by maccallum** [comment]
I'm going to consider this orphaned for the time being.
