### ISSUE TITLE
&& and || list functions broken

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#270]
&& and || no longer work to compare two lists, scalar compare does work.

luckily the and() and or() functions still work!

<pre><code>
----------begin_max5_patcher----------
636.3ocyUs0aaBCE9Yxuhy3gnFIFgK45j1CUZZOtN0WWllLfShaL1Hiogr19
eu1FHARylRiZmlhBF+ct3ONmOa+POK6HdIN2F9D7Cvx5gdVVFHMfU8bK6TTY
LEkabyNlmlhYRamJaRbozf2uOfXIviOBLNP4rUXArkK1.aIx0.kjKyWvVvjq
QrMKKnzcZ2uZfIHtP8RtjPolPbfbNjtCxH3XLDiXvJNvYePsLCZVWJggi4EL
yhGVCxJRILJVZXp+APdgrA0qFcImIyI+Fa7z2sANCIiWSXq9k.GKqJKgSmnL
qbZpdHbzb8vnPWO3msxECkZxk80BBh1vRRhAiGc2G88Z.WJVEYnhqmF3od8z
ObNy5O2EWlIbi4IXsiG2FFVdysvmgHNmd0Pz.3w5WiF3rfMr75u8k1V621px
9Qw1M3atMPYU0qZbvYu45vON6cRu1pNA519IxvIary9aMV82bLmxEU8IOce4
vC+VMntRffZzJH4tLbUBr+pRV9cT7FrRc2YVmN8YpZLjXtQ5D5MpRAMqEmZI
MlYeA5fTbdNZE9EB.OvGz+q94A6kccpgAmrx3+mpLWdEHbl4SudX5qcWyT6K
ZKRBIOih1Y+dHedGJRAiMGpL1y2TxBOsLY7kTKX3spXegJg6loj1vPDLL5sP
f7VrYYxgcIpg4uVoRP6xiITyYIGc4lY003cqY47BQbyGS0dRkPXOARvpamXH
IgyZ4y3N9rljjfYsuiQoBQQTrghm9n9ykMSOC1D7eGa7+mvlfyfMytvZSkLB
kkcOVjWmRCQTaxtq5jiINloDV0TyNDaA9dRi+l6vrQBknWpT7EhJYb4jQJAq
Zcdp2yPWZOTh
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
Those were changed to | and & for the 1.0 release
