### ISSUE TITLE
o.timetag produces timestamps  that o.display 2015 before years end

### ISSUE THREAD

**Issue by adrianfreed** [CNMAT/CNMAT-odot#273]
I am curious if this is a display or a translation problem in o.timetag.

**Comment by adrianfreed** [comment]
please indicate which version has this fixed

**Comment by ilzxc** [comment]
I'm going to clean-test the RC7 release from yesterday. I believe that the
RC6 was still affected.

**Comment by ilzxc** [comment]
Tested the current release in 32 and 64 bit mode using basic sequencer. Time tag issues were sorted out long ago, but lost track of things related to releases.
