### ISSUE TITLE
Many objects not working on max 6 and 7 x64

### ISSUE THREAD

**Issue by Leamucho** [CNMAT/CNMAT-odot#274]
As soon as I charge the o.overview on max 6 or 7 x64 the following list of objects show problems on the console, the basic problem is NO SUCH OBJECT:
o.route
o.compose
o.collect
o.pack
o.select
o.expr.codebox
o.callpatch
o.mappatch
o.if
o.cond
o.change
o.var
o.print
o.printbytes
o.prepend
o.union
o.intersection
o.difference
o.collect
o.flatten
o.explode
o.timetag
o.schedule
o.listenumerate
o.append
o.display
o.dict
o.edge

**Comment by equilet** [comment]
Windows specific - 64bit

**Comment by Leamucho** [comment]
So, it only happens on windows?

**Comment by equilet** [comment]
Correct.

**Comment by Leamucho** [comment]
I'm not very familiar with the architecture of Max at all, but that means something like a total makeover of the odots for 64bits?

**Comment by alfonso73** [comment]
Hi all, i think that CNMAT externals for Windows 64 bit (.mxe64) are really needed. 
As it is now 64 bit architecture is the norm.
Any hope? thanks and all the best

**Comment by matcham** [comment]
please, we really need these objects in windows / Max 64 bit !
any chance to see an update anytime soon ?
thanks

**Comment by ramagottfried** [comment]
hello!  yes, the plan is to make this happen in the fall.  sorry for the wait.

**Comment by matcham** [comment]
thanks for your fast reply, Rama.
in the meantime, would you know another way to make OSC bundle in Max64 (windows) ?
Thanks

**Comment by ramagottfried** [comment]
Hi Mathieu, I think in the meantime, the closest option would probably be to use dictionaries.

**Comment by matcham** [comment]
Thanks Rama
but I don't think it's a viable option, as sending a dict over network implies using dict.serialize in order to convert dict into one big symbol, and as it produce a new symbol for each new dict, it tend to flood Max hash table.
(using more and more memory,... until crash)
a discussion on this topic here : https://cycling74.com/forums/how-to-avoid-flooding-max-symbol-hash-table
I can't find any other way to send a dict over network.
am I missing something ?

**Comment by ramagottfried** [comment]
hmm, I hadn't seen that thread, thanks.  not sure what other options there are for windows 64bit.  I think you might be stuck with 32bits for now. It's possible the classic OpenSoundControl object might be functional on Win64 sooner than the fall, but I can't promise when exactly.

**Comment by stgoddv** [comment]
Hi Rama, we are really waiting for the x64 bits version, mainly because nowadays practically nobody uses 32bits! My question is, What happens if you only build the actual src .c files for 64 bits? Would it work? What you really need to do to build the externals in 64 bits?

**Comment by stgoddv** [comment]
Aah, by the way, Where can i find the classical OpenSourceControl source object? I could try to compile to 64 bits by myself (i can't promise anything because i have never contribute to Git, and i don't know very well how to do it)

**Comment by ramagottfried** [comment]
Hi @stgoddv, yes, I know 64bits is great : )  We will have a release in the fall, but in the meantime if you're interested to work on it, you can find the source for the CNMAT-Externals is [here](https://github.com/CNMAT/CNMAT-Externs). I believe we will be moving things over to Visual Studio, but for the moment there is just the Makefile.

**Comment by stgoddv** [comment]
Ok, thanks rama, one last question. It's enough to reconfigure the compilation parameters of the Makefile for 64 bits? Or it will require more changes to the code?

**Comment by ramagottfried** [comment]
hi guys -- here is a test build for Windows 32/64 bit, can you try it on your systems and tell me if it loads and works for you?

https://github.com/CNMAT/CNMAT-odot/releases/tag/v1.2-19_windows_beta

so far I've only tested it on Windows 10, so hopefully it will work for everybody.

let me know what happens!

**Comment by stgoddv** [comment]
Hi rama! Fineee! Im going to test it now on windows 10 and i reply to you.
Thanks you very much!

**Comment by stgoddv** [comment]
Hi Rama. 
Thank you very much for you good work!
For me, it's working perfectly, at least for now. I'm on a Windows 10 machine 64 bits.
If i encounter any bug during the next weeks, i will post it here with all the info necessary for debugging.
Thanks!
Regards,
Stgoddv

**Comment by matcham** [comment]
Hi Rama

many thanks for this update :-)
everything seems to work fine here (win10 / Max64)

I have 2 objects missing : error message when opening o.overview :
newobj: o.callpatch: No such object
script connect: can't make connection (docmsg 0 -> obj 0)
script connect: can't make connection (obj 0 -> oroute 0)
newobj: o.mappatch: No such object
script connect: can't make connection (docmsg 0 -> obj 0)
script connect: can't make connection (obj 0 -> oroute 0)

Mathieu


________________
Mathieu Chamagne
mathieu.chamagne@gmail.com
http://mathieuchamagne.com

2017-10-10 19:15 GMT+02:00 stgoddv <notifications@github.com>:

**Comment by Leamucho** [comment]
Yes Rama, thank you, great doing!!!
was just going to report in as matcham,
same obj missing
newobj • o.callpatch: No such object

script connect: can't make connection (docmsg O -> obj 0)
script connect: can't make connection (obj O -> oroute 0)
newobj • o.mappatch: No such object
script connect: can't make connection (docmsg O -> obj 0)
script connect: can't make connection (obj O -> oroute 0)

but seems to work fine anyway. Win 10 last update by the way.

Thanks again!!

**Comment by ramagottfried** [comment]
great, thanks guys -- o.callpatch and o.mappatch are currently in the /dev folder, and are in a helper abstraction used the overview patch, so we need to figure out if we should keep those in dev and rework the overview or move them out of the dev folder...  either way, there shouldn't be an error message in the overview. 

thanks for reporting, and let us know if you notice anything else!

cheers,
rama

**Comment by maccallum** [comment]
I’d vote for keeping them both in dev and removing them from the overview. Or making a dev section of the overview patch with a note that if the objects are bogus, they can be used by adding the dev folder to the search path.

**Comment by ramagottfried** [comment]
for the overview it turns out there were just two hidden autodoc abstractions referencing o.callpatch and o.mapatch that were left in after moving them to the dev folder so that's an easy fix : )
