### ISSUE TITLE
o.dict broken - Max 7 

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#275]
See helpfile for details... I'm testing against RC6.

Expected: dictionary data in dict.view object
Actual: nothing printed
Related: Is dictionary support global for all odot objects?

Version info:

`{
	"version" : "Version 7.0.1 (57afb55) (32-bit mac)",
	"platform" : "mac",
	"arch" : "x86",
	"osversion" : "Mac OS X Version 10.9.5 x86_64",
	"samplerate" : 44100,
	"iovs" : 512,
	"sigvs" : 512,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"eventinterval" : 2,
	"overdrive" : "on",
	"mixerparallel" : "on",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf",
}`

**Comment by ilzxc** [comment]
RC7 does not seem to have addressed this.

Feeding the result into the right inlet of a regular Max message box causes hard crash to Desktop. Investigating...

**Comment by ilzxc** [comment]
Just tested this in 64 and 32 bit mode (using the not-yet-official RC8) and this is confirmed fixed.
