### ISSUE TITLE
o.expr.codebox crash - Max 7

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#276]
steps:

1. open test patch, attached
2. unlock patcher, option-click on o.expr.codebox to reveal help file
3. click on "higher order functions"
4. unlock patcher 
5. select all
6. copy (command-c)
7. close window (command-w)
8. repeat 2-7 until crash

---

<pre><code>
----------begin_max5_patcher----------
494.3ocuUE0aaCBD9Y6eEHd1y0fSRilzj1S84991zDASaoCCVXblyp5+8AGN
sNscQznr9hAt63366ybGOjmg2XFE8XzmQeCkk8PdVFXJXHaZcFtkMxUrdHLr
orQ12oX6vEQuNwnC7bgSz67SpK9t9BVXx9PTRsfaFzPbzIi5gVoVIbPZISFu
wnc2v3hfspY15k+ArQnkUOueyf6kIHZxsqSDIEFi9wjqNliemTe6OsBtK5kr
txmODc4xv.YIrZw5xpm1jrIx5M2+oUyYL2nL1XRfM87GRX2g.eLOO7oHQgUK
9s+TdkpZJ6X7eg.wcuyd2NEvOL9XhYhJzUCJ009yP3RQqlFtjBBG8skpE3ym
.XY5FSKhTkH6ouO1K0oQ63ciUqOFsqOiztU3rFOqqPekwcxsBD4+i.rgouMI
EfNMPNlDPOEIvTJF6rkbSiHD3qZrvPe4vBfyauCZBUFEu25DJY98l5+gbQNs
dJPpf1pun2Mfmf8CU6dyfkumUwBTeleBPMdoUpYNoQOKFxAwbmroQnmqs92A
XaTBfLUu4e8TQScBnYwGFZnIfl5OLzPR.MqNQzDuFw551Jr8SoD.hu7793Uw
KKfkRcbIjQrUrUtOdn5Cyr9x.muFXvF6LMtN9bIt0WTa0CRH17vI+X9eADL3
xuK
-----------end_max5_patcher-----------
</code></pre>

{
	"version" : "Version 7.0.1 (57afb55) (32-bit mac)",
	"platform" : "mac",
	"arch" : "x86",
	"osversion" : "Mac OS X Version 10.9.5 x86_64",
	"samplerate" : 44100,
	"iovs" : 512,
	"sigvs" : 512,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"eventinterval" : 2,
	"overdrive" : "on",
	"mixerparallel" : "on",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf",
}

**Comment by equilet** [comment]
crash report:
https://gist.github.com/equilet/7273ca5ab1fdbc6c2e95

**Comment by ramagottfried** [comment]
can't reproduce, can you check with the latest version? I believe what you're seeing is issue #267 which should be fixed now.

**Comment by equilet** [comment]
100% reproducible on my machine with RC6.

**Comment by ramagottfried** [comment]
can you check your build date? the fix for #267 was pushed Nov. 18.
I'm running odot version v1.0.6rc-5-g0ffefea (compiled Mon Dec 29 14:59:02 PST 2014)

**Comment by equilet** [comment]
Ah, OK - maybe that untagged release is what I need - I'm running the following:
odot version v1.0.6rc-0-g2d74e3f (compiled Thu Sep 18 14:27:36 PDT 2014)

**Comment by ramagottfried** [comment]
ok cool -- I'm pretty sure that will fix it (I was seeing the same crash before), so I'm going to close this issue -- but let me know if you still see it with the newer version!

**Comment by equilet** [comment]
Doesn't look like the aforementioned release is newer than RC6 (it's from July), so we'll need to keep this open until I have a valid DL to test against.

**Comment by ilzxc** [comment]
Thanks for reopening - I'll be in on the 8th, and we can build a new
version & test.

**Comment by equilet** [comment]
This is fixed now.
