### ISSUE TITLE
string split with "" separator

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#277]
/res = split(quote(), /str)

results in /res = /str with no split, I would have expected that it would split every character?

<pre><code>
----------begin_max5_patcher----------
552.3oc0UEriaBCD8L7UX4S6JQ2ESLIgJ0q8bu2rJxAlj3sDaJ1Dk1U6+dsG
CMjsn1zJsUsRgwxie9MuL9g4o3H5F8IvPIuk7QRTzSwQQXJehn94QzChSk0B
CBipuqTenQa.ZRXUKbxhqbuw15FWQEaJqfs6VQGfn5Nn6r0fEof0msoELfxJ
rRsZcKTZCxHOO6tzDRFi6GR6CjG520VsxtUTBdvo84Bja+RCDnfRu.tQ9UbA
lm3yhtTWqaCaHcboRHrQ0yocoZP5YCRWXK2KU6FIaNmGjcNxPNRTFeDSxpPC
byiuY9PmwHNBUq2zoppg00fZmcuGDOcp0qDVQnXyxSHEKckgsvG7ELEC9boL
2eiq3Wl6gi6O2Gl6C7Kgv48KGlVrHT1hhuWPlOj4CybPHO3k8yww9PxqfiJY
k5dmsYZaVsTAk5Nkc7Q0zdu+UcQyJP6CmsXjKZ1xocQ4+BWzb9+mtnIYmOf6
LQ+U8nvolVmQsB7.+Aip2S9NhooVZu4ycZKbysIDu881ouCL62wG99t55OHJ
+DXoIWL6Uxex9I9ykyv60JBCyli9yro8mL5nNMB.eE8EetAqhO+kseitqsbn
CzemI4bYp.iUpvucLBC6BL6kUUfZbqsRZDapAThoSZCtV0vtB03d+jv9CTSn
UIZZNBsldJQg37jOFNLWjfSkpvTjQZKbTNfGOCohV2An0c500hhmdZNmF1py
I2p5jH1XekeN9afIZFM7
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
Fixed

**Comment by ramagottfried** [comment]
this seems not to have made it into the release?  I haven't built the dev version in while but I thought the release was relatively up to date, and this is over a year old.  weird.

**Comment by adrianfreed** [comment]
please review the release process and what code the release corresponds to.

**Comment by ramagottfried** [comment]
not sure what you mean -- the fix was on Jan 12, 2015 (assumed to be in the master branch) and the release was July 15, 2015.

**Comment by adrianfreed** [comment]
I have shared the correct approach to making sure that releases reflect a known state of the software.

I thought you were indicating a breakdown in this process.

Release candidates should not be built on private laptop drives but on the release drive / Windows machine provided for this purpose.

**Comment by ramagottfried** [comment]
I'm just following up on a bug that I remember John fixed, but seems to still be in the release. So possibly this issue should be reopened.

**Comment by ramagottfried** [comment]
sorry, to clarify, I mean that I'm checking to see if it was fixed or not, if not then I'd like to reopen the issue.

I'm working from the release version while teaching so not sure how the master branch differs at the moment -- however the dates seem to point to a possible missed commit for this fix when the release build was made. 

I'm not involved in building the release so I'll leave it to those who know the release process to evaluate what happened here.

**Comment by maccallum** [comment]
It works on the build I’m using which is

odot version v1.0.9rc-mmjss2015-0-gf872be7 (compiled Mon Jul 27 15:56:38 PDT 2015), by John MacCallum, Adrian Freed, Rama Gottfried, Ilya Rostovtsev

Which build are you using?

**Comment by ramagottfried** [comment]
great, thanks for checking -- I'm using the current public release from Jul 12 2015 that's on the github release tab to be in sync with the students, so I guess that fix will be in the next one to go out. 

Not a show stopper by any means, was just surprised since the fix looked like it was in January so thought I would mention it.

**Comment by ramagottfried** [comment]
oh!!!  sorry for the noise, I had the year off by one!
I got confused because the issue and the fix were both in January, but in different years! : ) how time flies.

**Comment by ramagottfried** [comment]
... but wait, but that's weird that it works in your build from Jul 27, 2015 and the fix was in Jan 2016?
ah, that was probably just when you marked the issue as closed, and the fix was actually sometime before Jul 27, 2015.

Ok, anyway, if it's working for you then I'm optimistic it will be in a future release.  thanks!

**Comment by ramagottfried** [comment]
just to conclude, I should have checked the libo commit log, not CNMAT-odot. clear as day now, thanks.
