### ISSUE TITLE
o.route and o.prepend question

### ISSUE THREAD

**Issue by hanstutschku** [CNMAT/CNMAT-odot#279]
the set method is still working but deprecated. What is the current syntax to change the address for those objects on the fly? I did not find that info in the documentation. Thanks, Hans

**Comment by hanstutschku** [comment]
to give more info on why I'm trying to do this:
I have more than one bpatcher of the same treatment. They are differentiated by instance number.
By using /1 /2 or /* I can decide to which instance I'm sending the control values.
 
![screenshot 2015-03-14 16 50 39](https://cloud.githubusercontent.com/assets/8834836/6672186/051a5bce-cbe1-11e4-95d1-dec9ce8408f2.jpg)

The instance number in each bpatcher is given as the first argument (#1).
I'm using it to set the o.route in order to distinguish between the different instances.

![screenshot 2015-03-14 16 51 28](https://cloud.githubusercontent.com/assets/8834836/6672190/0fdca60c-cbe1-11e4-9714-cd7a55611349.jpg)


Again, all this works currently, but I'm receiving a warning in the max window that the set methods are deprecated. How would I realize the same functionality with currently supported syntax?

**Comment by adrianfreed** [comment]
we hope to provide a mechanism to do this well using the o. expression language. The current functionality will work for a good while yet.

**Comment by maccallum** [comment]
Hi Hans,

Sorry you had to wait so long for a response on this. Just to echo what Adrian wrote, that ominous deprecation warning is just to signal that we have ideas for a better mechanism to support what you're doing, but it won't be implemented right away. In any case, we'll also provide an abstraction that will ease the transition when the time comes.

**Comment by maccallum** [comment]
This is now issue #300
