### ISSUE TITLE
simple recursion example for o.expr help patch

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#284]
just doing some recursion tests and thought this might be a cute example for the help patch:

<pre><code>
----------begin_max5_patcher----------
409.3ocuSEqSCCCDcN4qvxSTQHMoMJEPfXiY1oUHWGC0AW6HGGHkp9ui84D0
zh.AcfEmb28tme9d1aCCvKUsrZL5ZzinffsgAAPJWhft3.7ZRKUPpAXXUbAu
tRP1fi7UMrVCTY76q3BlPoprQywBx5kEjyJiPknaP4n6PjpJwlyP6wYKcdJZ
jEd4n43n4xwZ6+48LK3RFU0HA5mzkT1rlKELCnlzAZfpDJs+jjDmDMXIMNAs
Xe6pFyw8+rRZdlPYtbIc4pHF5Jt7kmzLpwy6UY.c4ScexlAQYWNfcGO07O.d
RmD2SEuvO5VVdQZ+gyqBylJlmaLFsvUYWXnaI5WaGr1JcLUUvb.+AO41S2St
sC1PTIi9+roImjMkjLzlx+S1zzu0ltuQHdfPekYvQGDcf8AaELYN5wEHWW9C
8zZUil1uEcB.sWvErZCWRLbkb.lzCvrhWTvjCGM1GpjkBFbpR9h3rV5aLccG
kfPrWsJ8lyrHHjK8g.iXM6MdO9LHCQam8F6fuQChG2lmg8sZuPpkMbXDG514
cgeBqH6D6B
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
What should I do with this?

**Comment by maccallum** [comment]
added to the higher order functions tab in o.expr.codebox.maxhelp
