### ISSUE TITLE
Review all odot objects to remove unnecessary method bindings in the new routine

### ISSUE THREAD

**Issue by ilzxc** [CNMAT/CNMAT-odot#288]
Max autogenerates bubbles for the objects' APIs based on methods registered for handling specific things. Several of our objects' inlets list many a message they no longer support. Culprits are:
- o.compose -- `float` `int` `list` and `anything` are no longer supported
- o.display -- `select` is not supported as it functions inappropriately in locked patchers (enabling, for example, editing the box from a locked patcher).

I recall seeing some others while working on documentation, but I don't have the time right now to address this properly. Soon.

**Comment by equilet** [comment]
You and I should meet on this.  Just as an exercise, we can explore all the various options, many of which you won't be interested in, but alas, it's good to know what's there.

**Comment by ilzxc** [comment]
My approach to writing the reference has been to create an odot object and right click on every inlet, noting inputs accepted. Messages understood by inlets were then tested, one at a time. In the case of o.compose and display outlined above, float and int are recognized by the object, yet those routines just print the error message based on the design work we carried out last summer. The same error messages would occur if the methods weren't present -- the issue I'm seeing arises from the left-overs being visible due to Max providing object introspection automatically, which leads you to believe objects respond to floats and its when in fact they do not.

In such cases, it's safe to take the methods out, as they can not affect existing patches (since those messages yield nothing but errors). However, reviewing it all will take a little time. Once the reference pages are done, it should be easier to see which methods I have purposefully omitted from the documentation and start from there.

**Comment by equilet** [comment]
I think my comment was irrelevant for this particular issue.  I'll start a new one if necessary.

**Comment by maccallum** [comment]
This has been fixed for some time
