### ISSUE TITLE
dot operator syntax error within lambda expression

### ISSUE THREAD

**Issue by ilzxc** [CNMAT/CNMAT-odot#295]
The left side of the patch is what's wanted, right-hand-side of the patch is a hack that shows the result. The idea here is to pass subbundles as `kwargs` (key-word arguments) for functions, enabling odot libraries to feature compatible functions of one argument.

<pre><code>
----------begin_max5_patcher----------
699.3oc6Ws0aZCCE94vuhH+TqTVHFxMlzdcOu2aPHShojtDmnDGT5P7ee1Ga
XAHcDpFkMogPNwm61emKv1QFnkEszZj4mMexzvX6HCCfjjfgduAJmzFmQpAw
PE1Io0kYjWQVJtrl7hFdFkC7wZpkDd75T1yKpnwbk8m5Z6XYNI.Ke35LS9PR
ybtVmzDkGV9xmB1acko4uVRUFAgNHNm1xiKxJpTb.ydzxAIWUv3qHwfIb5Pq
N8G.M7D68jKqn0TFmvSKXmG6S8jObzKGru3JHkc3FPRa2nQxEqAeoRaKqriK
RnRA6b.A1i4zZ9pFVr4WLiPYj7kIjGdpctkYDyT7YrHnax3Bts1iIQrGiPVQ
rCZ8.71i6MaVJiFWzv.a61KJN4RnH1K.PQLbWDLseTL7MQwu1jk8MR72obj0
Q6dKz0o6E+sAc0moaA5FWjWVTS6GXEurMhEwGSfC.75RoqhX6tBL6hUdpBOr
Gb.885Gxlc8EdN13vPqSdbK.H0A32iO6ybqIanIKV1vRxnKxnrm4qkrCc6ie
BgSzNxyxblL7wAxE48kCrHo4fENd.e8cEUFf99ZsvXO81CB4JEx+LccEN5OR
PfmnBhYAc8H1waXZEdIsvlyeWkBmL8X3kBc6nIH0aePNMuT1E77Fi.qiaNJD
8BtSqsfWu0g3oWagnaPv4y.wyB5uVz+dMD7tOO6pvwKOjy6ZGxowoimxE52O
L4921Tt+8GXou+GzDqI22IV+e5y8e5CfaPJ2I+UFH0RR+3j85hlp38YI5e0i
4uP+DQNdJC9MHcjI7HYVmljPYcyODC1HKynPhoSuEcCMZBGPzD7gEMtCHZ7+
vhlICHZbemQiJMhTVtgVUqMIDHhtiun5cDXAaSYpsfEQUzMo6kGpvQjJQGMt
ncVSED7n1P0vbTtXjXEqIU2ZV34ci9YZsKIs
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
done
