### ISSUE TITLE
gui copy paste colors 

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#296]
doing some customization tests with o.compose, and find that the text color resets to default when copy/pasting, the background and frame colors are correct though.

**Comment by ilzxc** [comment]
Yeah, I need to revisit text color stuff in the Max API because it's not right -- and it is different because it's not owned by our custom code (belongs to a Max jTextbox or whatever... :(

**Comment by equilet** [comment]
https://github.com/CNMAT/CNMAT-odot/issues/264

**Comment by ramagottfried** [comment]
fixed -- turns out the textbox object has a default attr name which is textcolor not text_color, so it wasn't getting saved properly.
