### ISSUE TITLE
o.pack slow with subbundles (possibly windows only)

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#297]
packing a subbundle on windows 32bit is very slow, testing on mac 64bit it seems ok. haven't tested mac 32bit yet.

<pre><code>
----------begin_max5_patcher----------
718.3ocyW97aaBCEG+bpT+e.woVIVps4WgIsC6xNu6SSUNfC0cDapwzktp8+
97OBoj1FpqFf5Erxims+99jmeOyime1B+07cjFeuO68CuEKdTYYgwl1xhNCK
72h2kWgaLN5K4kkUD+f8ui0tk2JqHRyagclajOnbR6+AOstIenlX2PeJS568
ytWSKLtyWe6mfwGlTMVleCkUdsfjKsyCljtLNvCsBsDnFh5d9zRUiE3sDIQb
MggWa0AnmforC50X7umeldTMD3LFXjeqj5AcJI6LxyuDKGE3bBxD5.YBCAZl
DZICpOYNJ3QidvWwwEqwrxw..l040g.ZHHDALwcrgAP.3Mfv3mAvWViy+k2U
a37wfCeqsp56pEjbpCKPWRIRh0bHIaxnwVRSCtj7Rb7j98x.fvDODLCkEghN
3ZEkQx4sLi+wS2YGvPfJLxdbwVUwl8jlNAmctkJWtotorkdhrCz6JTCNJb2v
YRlp1mYVeUPwU9uBIVMDHxfFN.S0CqrURR5yA8drAmebUUswF5eLFgZDNtYW
qakRNaZKqjNX5QBzVOI6TMcl7pJ2iEyQ8jA68hf8yNBSmrNLyvsLhFLPscQh
x9HdGi6Tarfq.+zdfXv1rvUlNJYgl9JwSVh.eIYWsXYNufn87Er3pcdewai5
hGxjnKvMj6t.Dn55C.Wd4aUecniFANz3cv7mLCRfw1KoBrmWPiTcz9THmWwE
1M0Tr9oGP8t8Lva2dSK2meueSTnewy96ng2Jx6PT2kP85EHEjFIkgkTUE5dd
AO1qanEED1QAaAsQezwfTvoyPbWXwNIrvYWXtqK37BLjKBK8CJu.yNubBWql
cbk5DtlcY4Dshm+pDtJq4M2JxEYg9un09h+3556Ihl8qrUQplt2ZaijFX+Mk
Y+sck8Ej6ocSw9MZ9XgpqmT0xqUXujwtUI96mspcsfo9Dm82+wnA0i+AOBEB
uB
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
I can't replicate on Mac 32 or 64-bit. I'll test on Windows this week

**Comment by maccallum** [comment]
Assigning to Jeff to test on Windows

**Comment by maccallum** [comment]
This is not an issue on Win64, and we're not supporting 32-bit, so I'm going to close
