### ISSUE TITLE
interleave(?) crash when dealing ridiculously large lists 

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#299]
this came up in some homework that I just received.  not sure if it's interleave or not.

and, no, I'm not saying this is a good idea : )

but probably we shouldn't crash.

<pre><code>
----------begin_max5_patcher----------
580.3ocsU00aaBCE8Y3WgkepUhk.TJIcR6087deqJxAtIwcFalsIKcU8+97G
PDjzLHQZ7.V95qO93y4Z62BCvqEG.EF8Yz2QAAuEFD3BYCDz1O.WQNTvHJWZ
3MLAuoBG4GpVBJfqIZpfuRBEZOTIwoKmEGgdHMw1D29C8b6zLHHZzLP6vLsM
pR+JCbKRG7aDxJhCy71H9ooesF7qjIUDdMguEeD7ZhtXGku8x74QGgRSGxHJ
uiPIsAokN1HV+xmxNtiIRREnA4JfSV64arcn2CCs+hlnNxgeavsCUMbP6WqY
0jhehlS4EiqwYt8zi4SPiStnFelh90FF6aFR.5wzz9qeR70Kp43aP3DyfC0x
YEhRvl3oB37MDJC8EDQA+5tTKihMeQNE89nevmaTSyvTtwBY.YObmaFlDrM2
2gGixgBQCW2u.cLmX4SenSX4VgfIj9zi6mjQ3F8bw+xgh9X+Zifq2PJ7UmSv
C8LO8AmUlk2iRVjTz+3PJwXtSzZWbaVagnpVnfQJ8yybGiydJdZ5cxxkQmzj
L5Ikyuo4ZU2gzbwBuFmckha54h6xN8QYpeKWstgWxfULfuUuqOmFLbIQS77B
8bOuwwEW49IOC31P13CMLknQVzIIdm1HpG2QkfRS4NCqWNFBiRNlyNZYIv6S
zRpxdWZ4kuLcprIeBrYHi+exlrIvl7ajMdiiTWuGjpVHcDwbl5Ees+hHWWJ2
20gHVB6oc46dUESjlJWsorsQ5eZ3Pt+4Nbk4RVIug5pOCsq76g+Er436OA
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
Doesn't crash for me. We can't predictively determine when a list or something will exhaust the memory.

{
	"version" : "Version 7.0.4 (cbb83ff) (32-bit mac)",
	"platform" : "mac",
	"arch" : "x86",
	"osversion" : "Mac OS X Version 10.10.4 x86_64",
	"samplerate" : 44100,
	"iovs" : 1024,
	"sigvs" : 1024,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "9e39a8f2dd16c55c866911287cd55401",
	"eventinterval" : 1,
	"overdrive" : "off",
	"mixerparallel" : "off",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf",
	"packages" : 	{
		"Beap" : 		{
			"name" : "BEAP",
			"type" : "package",
			"author" : "Matthew Davidson, Peter McCulloch",
			"description" : "BEAP (Berklee Electro Acoustic Pedagogy) Modular is a synthesis pedagogical tool.",
			"version" : "Master from GitHub",
			"major_version" : "0",
			"minor_version" : "0",
			"min_max_version" : "612",
			"min_osx_version" : "None",
			"min_win_version" : "None",
			"website" : "https://github.com/stretta/BEAP/wiki",
			"link_mac32" : "https://github.com/stretta/BEAP/archive/master.zip",
			"link_mac64" : "https://github.com/stretta/BEAP/archive/master.zip",
			"link_win32" : "https://github.com/stretta/BEAP/archive/master.zip",
			"link_win64" : "https://github.com/stretta/BEAP/archive/master.zip",
			"relative_path" : "None",
			"path" : "Macintosh HD:/Applications/Max.app/Contents/Resources/C74/packages/Beap",
			"vol" : -682
		}
,
		"Gen" : 		{
			"name" : "Gen",
			"path" : "Macintosh HD:/Applications/Max.app/Contents/Resources/C74/packages/Gen",
			"vol" : -683
		}
,
		"Jitter" : 		{
			"name" : "Jitter",
			"path" : "Macintosh HD:/Applications/Max.app/Contents/Resources/C74/packages/Jitter",
			"vol" : -684
		}
,
		"Max for Live" : 		{
			"name" : "Max for Live",
			"path" : "Macintosh HD:/Applications/Max.app/Contents/Resources/C74/packages/Max for Live",
			"vol" : -685
		}
,
		"max-mxj" : 		{
			"name" : "mxj",
			"type" : "package",
			"author" : "Cycling '74",
			"description" : "Max Java Support",
			"version" : "7.0.4",
			"major_version" : "7",
			"minor_version" : "0",
			"min_max_version" : "7.0.4",
			"path" : "Macintosh HD:/Applications/Max.app/Contents/Resources/C74/packages/max-mxj",
			"vol" : -686
		}
,
		"MaxDefaultContent" : 		{
			"name" : "MaxDefaultContent",
			"path" : "Macintosh HD:/Applications/Max.app/Contents/Resources/C74/packages/MaxDefaultContent",
			"vol" : -687
		}
,
		"MaxIntroLessons" : 		{
			"name" : "MaxIntroLessons",
			"path" : "Macintosh HD:/Applications/Max.app/Contents/Resources/C74/packages/MaxIntroLessons",
			"vol" : -688
		}
,
		"mira" : 		{
			"name" : "Mira",
			"type" : "package",
			"author" : "Cycling '74",
			"description" : "Mira automatically connects to Max and mirrors your interface.",
			"version" : "1.1.8",
			"major_version" : "1",
			"minor_version" : "1",
			"min_max_version" : "7.0.2",
			"path" : "Macintosh HD:/Applications/Max.app/Contents/Resources/C74/packages/mira",
			"vol" : -689
		}
,
		"vizzie" : 		{
			"name" : "vizzie",
			"path" : "Macintosh HD:/Applications/Max.app/Contents/Resources/C74/packages/vizzie",
			"vol" : -690
		}
,
		"Max" : 		{
			"name" : "Max"
		}
,
		"MSP" : 		{
			"name" : "MSP"
		}

	}

}

**Comment by ramagottfried** [comment]
ok, not crashing here now too.
