### ISSUE TITLE
set message console errors deemed unnecessary

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#300]
are we actually going to remove the set message for o.pack, o.route, and o.prepend?
so much functionality depends on it, and it seems that the replacement will not be until the new expression language, which is going to be odot 2.0.

can we remove the error messages for the current version?

I would prefer non-programmer users of max applications not need to see these messages since they only create fear that something is going to break in the future, when in fact odot 1.0 will probably be frozen at some point soonish, and 2.0 will have a different way of dynamically creating and routing address.

**Comment by ramagottfried** [comment]
#300 !! cool number : )

**Comment by ramagottfried** [comment]
for creating address, you can use o.expr.codebox with assign() to avoid the error message, but for routing it seems much more convenient to use set than any expr alternative, for example in a poly~ voice using thispoly~ to set the voice o.route.

**Comment by ramagottfried** [comment]
I volunteer to remove these error messages, ok?  in particular o.route, for the poly~ use-case described above.

**Comment by maccallum** [comment]
I'll remove

**Comment by maccallum** [comment]
error messages have been removed
