### ISSUE TITLE
o.gather 'see also'

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#302]
this menu is populated incorrectly - instead of "o.route o.select o.atomize" being the 1st element, they need to be separate elements

**Comment by maccallum** [comment]
Is this an issue with o.helpfilehelper? Do other help patches have the same problem?

**Comment by equilet** [comment]
No other help patches have this issue that I know of.  It may have been propagated by hand at some point...

**Comment by equilet** [comment]
this is an abstraction; I'll try to address it there.

**Comment by equilet** [comment]
fixed
