### ISSUE TITLE
o.atomize connection (bug?)

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#304]
I am unable to connect the output of o.atomize to a [buffer~] object, unless the object is named with an address.  This behavior contradicts the behavior with most other max objects...  Patch below.

<pre><code>
----------begin_max5_patcher----------
562.3oc0V00aaBCE8Y3WgkelkwmIjo87dduOMEY.mF2B1HykrjU08aeFafRZ
hJrBsR6ALxWru9bN2OLOZagSDmnUXzWP+.YY8nskk1TiAq14V3BxozbRkdYX
N8Whj6wNlOAzSf1bR898T4e5rWRfzCL9c6jzTv39v0QqbcPdA5WgwMi99qbQ
+rcOhZHmBv4RpYC384BBfcTNmvuC2uNVl9DUn3SdtcGXEbNWuObmEdcAiqbn
F1dc3RRqnbf.LA+BrEN.atsC8mnxUFvo8keiwmrsaFblmpIVQ.QA62Tzm2KD
iKdq0PKd83ZWir8s577uSRefB2T719OpcyWEREEEJ0+JY3qHPdFUPdPQZDbf
UgREbth7pnzqHJ9w5jnsa0wNi13OLtMfrwyhrtuCg7WgXFpzNFLdvdj.85ko
Hw2aioHIXBEIdKmhkJxyGUrZKcibWEMkRi9maoWQyJWIrayjizrcJ+oP5NB.
RVRMX50Z0K.VXZQBMqOGyHYKjvMdOY+MtKdO4vO71JynRqU.VrRsfYQ9Erno
TxdtQ6MHt2E2FGDdEyGPJ++m5c5M7lxEHh5sXQTs2w4L9K+gKMKZreohTIpk
ocnr8BazyDIiVALttI8f0z7GQCVzAVVFU+c2tswpHI4CZ4bUnYpvY8DfSzGF
Z7l.Z7einwD4HkkGoxpVWpAhJq8dgrY5FG8TF2LUmMfkzirt0qOCLQpxWAUx
ZszjKcJ1b6LtPjQk7ZVaVi5jex9uR0HrM.
-----------end_max5_patcher-----------
</code></pre>

Let me know if there is something I'm missing; it's a bit of a bummer and I'd love to find that there is a workaround.

**Comment by ramagottfried** [comment]
Hi Jeff, I agree I think this is a bug. What is happening is that o.atomize and o.route always create a delegation outlet which is defined as having a "FullPacket" output type -- however, with o.atomize, it is actually never a FullPacket and is always a message. A fix for this would be to make an #ifdef around the delegation outlet type, and use NULL for the delegation outlet with o.atomize.

The reason you're not able to connect to buffer~ is that buffer~ only allows certain message types (and probably has no "anything" input handling) so when o.atomize tells it that it is going to send it a FullPacket, buffer~ says "no thanks".

Keep in mind that o.atomize will always contain the /address with the message, so if you send it an object they would need to understand "/" prefixed messages.

**Comment by maccallum** [comment]
fixed
