### ISSUE TITLE
"index_of" function

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#306]
would be nice to have a fast function for getting indexes of matching values in a list, something like the numpy nonzero(), or python list.index()

http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.nonzero.html#numpy.nonzero

**Comment by maccallum** [comment]
I agree, but designing a good interface for this is not trivial. ideally, this is something that would not be built into the language, but a library written in the language.

**Comment by maccallum** [comment]
Moved to https://github.com/CNMAT/libo/issues/26
