### ISSUE TITLE
dot operator support in value() function

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#307]
for sub-bundle usability, it would be helpful to be able to dynamically look through the bundle, for example:

<pre><code>
----------begin_max5_patcher----------
814.3oc6XszaiBCD9L4WAxm1UKMAayijUZutm26appHfaKsDSDXhnaU9uu1C
1IjFRBMsphCQJwfGlGeiw9aL90QVnE40rRj8Os+qsk0qirr.QJAV59VnkQ0w
YQkfZn7ww4KWkWxPNMOUvpEvSlrRHu75b9bwDr4N48oIxNXGcuZYG2wa69Bz
0W0ayb9FiSyR4r37JN34PsPd0xTdFS..gnEllz.qEOcSfw5UErRFWDIRy42U
vhEMIHcJdrqi8Ln0U2Xeaq7HNOKunQYIFmN04MWvszWhl7JgANXszFQhWVwZ
bCBs0f6y4h6ihgG3ZPZjH9wT9CGCkXe.mX2fVQV4nxz+ANBSFa7UYzZVxcKp
3IYr6xX7GDOBZPC5RgjHQjNf9xnoRNbnpABGznj4hkIeO9gwAN1dfCH5dRod
dx+AGprqT9mRXm50DUuYFIGIjgjOoHpROHOc801qCJH3sJ29dy.DwsMVMtP9
Kf5XeSnzlavtzS1R5zu3S4WJ4vrw9V0DiMiFoZbFDD.RwR8q0FLQvJEcxILq
mbB9miSvelZAFkDNrIE1ClFVAJ8xYEBIWYEtxJzEqPWdYaZ0BmuijzL5n7GL
lhw96lOryQeLdIV8pBI4TBSo3AjSJVkesiUQd+5nrJ12lq3sFOYN5GJU9dmr
MjtXavGx13cN1lv.0BWBsmrMsT5T7Ljiwy76prr+DE+LSRhtWu2M+iA3dvEh
heQtf5DzOCxJKvKdiiZY7dltyPvlZsQxG24bCLsmkhnmYxwLXRAE6OnqDE32
fRZ6BQSCu3BQD+qEhtVH5bEhTyt6UEjqisu6wVEn1htiO.e4Hd.9YFenyYff
FXbx3.3vBBBudjAW4jGjGYvo2Ztd+3v9vw61ykTh553I0enMkiQC9sWio3Ke
60fNvPyaNHWHPJ46+poLupH1jB5yM0dWjRjC4obXyoszwaOcdLMIgwamTIok
QKxXvnd268uunwqGnwWpC9KAM3dfF5WFZH8.M3K7MUyznnUqVyJJ0tD.hbs7
SMqYfBjH4psltvZMTAacpQeHFnnB47agbxcUA.dTcPyGFiVJY.J3Uof0iTQd
yn+CMFAMW.
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
the value function converts a string to an address and looks it up. an address with a dot in it is not an address, but an expression that has to be evaluated, so this can be done instead: eval("/test = /pt./"+/idx)
