### ISSUE TITLE
o.compose outputs on mouse up

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#308]
in my opinion it should output on mouse down (click) which is the usual behavior in max.

currently clicking on o.compose for sound testing feels like a delayed response.

**Comment by maccallum** [comment]
This is worth some discussion. I’d prefer for it to remain on mouse-up, but for output to be cancelled if the mouse is no longer within the borders of the object when the button is lifted so that you can change your mind. If you really need mouse down behavior, you can hook up a button. 

We could also make it a preference, but that would go against the general design of the objects.

**Comment by ramagottfried** [comment]
interesting... have you seen that behavior anywhere else?

from a "performance" perspective, I want to send the values when I strike the keyboard/mouse/button -- pushing the values down the pipe.

for me send on release feels like a vacuum gets created when you click, and then when you release the bundle get sucked down.

**Comment by maccallum** [comment]
I haven’t seen that behavior in Max, but it seems to be the normal behavior in the UI for most other programs I can think of and throughout the OS X Finder. If you want mouse-down behavior, it’s easy enough to get with a button or the key object, but if you have it and don’t want it, there’s nothing you can do.

**Comment by ramagottfried** [comment]
true true, good points.  To me the extra objects required to make a performance oriented UI for help patches etc. feels cluttered -- but I understand your logic which also makes sense.

**Comment by adrianfreed** [comment]
I am confused by this discussion. There is no "natural" way to do this, only normative or conventional ways.  It isn't a question of logic or sense, feel, or clutter. This is a problem with the mimetic approach and Skeuomorphism. The essence of the solution is attestation and manifestation.

**Comment by ramagottfried** [comment]
hm, now I'm confused.  I thought I was talking about "User Experience" or even "User Centered Design"?

I understand expectations of a user (like me) to be a product of how a given action relates to what I've come to expect though normative experience over time, which is why I pointed out this fairly minor thing.

Since Max is like an instrument to me I've grown accustomed to it behaving in certain ways which creates a sense of "feel" for me. The difference of button behavior "jumps out at me" because I'm conditioned to expect certain things by convention.

This is my subjective UX, and "feel" is obviously a very real part of my experience. When something doesn't "feel" right, or come "naturally", I have to then use "logic" to figure out why it is the way it is, so that I can either create a new "normal" for myself or at lest try to remember that it's not "what I'm used to"(and eventually get used to it to where it becomes "natural").

**Comment by maccallum** [comment]
Confused here too… I don’t see where anyone suggested that there was a “natural” way of doing anything. Rama correctly pointed out that our object behaves differently than most other Max objects, and in response to his question about whether I had seen the behavior I was proposing, I pointed out that it seems to be the norm in the programs I use most frequently—my method of determining that was to poke around in the 12 programs I currently have running. Not very scientific, I know… 

The most significant UI change introduced by Cycling when they moved to JUCE was the change to the number box. Pre-JUCE, you couldn’t “back out” of a change to a value—if you started typing and realized you made a mistake, you had no choice but to click outside the box at which point that value would be sent. I can attest to the value of being able to back out of a gesture in the middle of it, as well as the difficulty involved in correctly building the machinery that will let me do that if I find myself making a mistake in rehearsal, for example.

**Comment by ramagottfried** [comment]
It's interesting about the standard behavior being mouse-up for most buttons in OSX, I never noticed that before.

My only explanation for the Max standard being mouse-down would be that it wants to be "immediate"?

**Comment by adrianfreed** [comment]
It might be an example of Miller Puckette's charismatic authority.
He might have favored "consistancy" with the slider and kslider which in addition have modes.

It's important that people know how to design interactions with all these styles. It's an area
that Ilya is studying at the moment.

**Comment by adrianfreed** [comment]
I should join the dots with the naturalist reference but not in the issue queue.
This is an old debate in HCI and design circles. It is probably better to pick it up with Bjoern and Ilya
who have access to the latest literature. The terminology is confusing as NUI's use the word natural in a different way:

https://en.wikipedia.org/wiki/Natural_user_interface

This is a good place to start (Yes, I know I have not been shy to share my critiques of Don's work)

http://www.jnd.org/dn.mss/natural_user_interfa.html

What I was connecting to the "natural" at the start of this was Rama's expression of unsatisfied expectations and the "feel" of the interaction.
