### ISSUE TITLE
lambda crash when attempting to return a static number

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#314]
... but no problem if you use progn()

test patch and crash log below:

<pre><code>
----------begin_max5_patcher----------
548.3ocyUEraiBCD8L7UX4SIRzTLFHaqTu1y68pnUNfSi6ZrQFSUxV0+80L.
6BoIQozVs6Ea4wCy7l48F7K9d305c7JL5VzCHOuW787.SMF75N6gKX6xjrJv
Mbltnfqr3f16r7cVvtRixLrps8WTY2K4vM8VT0EBkjag3P5LVxrYaEpG+ggm
YawAIhtHIvsEuHzskD1rE4VQq59HQNDX85mtZ4fnqqs8gOrO7FdkCsLqPqFj
hjvTHEzzlXG1sfV07Qu562rD7A6GeRMiX5M.RIe6BZFomnYLgxRuHWTUJY66
CYa7r6K4s.Ci+CBNZsrQqraXY7QrwaquzHnfHgCJOZ7fxqINUheAwgz37ap5
niW0jyKAhiSfLGkLVBLfGyzRsoSSBva3xjDK5E7cklEY5bdiiGpYtdiVitCw
JKk6mgjrh04rYOrJ.UZzORlQlOO.c8ZlY9IIk6qkxuyx9I2IHGc5SjrHwvTC
MDjjzn2EYEebxJ5hHKBc4kPVgCc5iPVGLBLlmtEcE8Kd3fdCcvzwxkSX3fd9
gi+uj4DjSfG9uRc20s6j2QwzIHuImWd+9DpPdwRg5vWnAv2XeLGToqMY88pt
gMzeQeNuxJTvn0.ehF4yVQdNWMrQ4lAXqk77S+PxkhFxEfF5DQSaqxondlap
5BI.Dmv7o118x.3nP0dDnDrg+rn2eHGXlwoKrNQQso8E6cos+yBW3jyFUs.X
e+lL+p+uAL6LlPH
-----------end_max5_patcher-----------
</code></pre>

Process:               Max [3174]
Path:                  /Applications/Max.app/Contents/MacOS/Max
Identifier:            com.cycling74.Max
Version:               7.2.0 [13d948d] (7.2.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Max [3174]
User ID:               501

Date/Time:             2016-03-07 10:48:32.580 -0800
OS Version:            Mac OS X 10.10.5 (14F1605)
Report Version:        11
Anonymous UUID:        E844FD0B-4873-595F-3615-7C8115A0DD9F

Sleep/Wake UUID:       CA0E2531-33E0-4226-A8F5-1C6145804E82

Time Awake Since Boot: 85000 seconds
Time Since Wake:       2800 seconds

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007f8951205a00

VM Regions Near 0x7f8951205a00:
    MALLOC_SMALL           00007f894d800000-00007f8951000000 [ 56.0M] rw-/rwx SM=PRV  
--> MALLOC_SMALL           00007f8951000000-00007f8951800000 [ 8192K] rw-/rwx SM=COW  
    MALLOC_SMALL           00007f8951800000-00007f8952800000 [ 16.0M] rw-/rwx SM=PRV  

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   ???                           	0x00007f8951205a00 0 + 140227748321792
1   edu.cnmat.berkeley.o.expr.codebox	0x000000011bca33b8 osc_expr_evalInLexEnv + 1000
2   edu.cnmat.berkeley.o.expr.codebox	0x000000011bca7baa osc_expr_evalArgInLexEnv + 490
3   edu.cnmat.berkeley.o.expr.codebox	0x000000011bca6ea1 osc_expr_specFunc_assign + 513
4   edu.cnmat.berkeley.o.expr.codebox	0x000000011bca36d1 osc_expr_evalInLexEnv + 1793
5   edu.cnmat.berkeley.o.expr.codebox	0x000000011bc905aa oexprcodebox_fullPacket + 378
6   edu.cnmat.berkeley.o.expr.codebox	0x000000011bc9097c oexprcodebox_mouseup + 140
7   com.cycling74.Max             	0x0000000103413d18 BoxComponent::sendMouseMessage(juce::MouseEvent const&, symbol*) + 158
8   com.cycling74.Max             	0x0000000103414fe8 BoxComponent::mouseUp(juce::MouseEvent const&) + 540
9   com.cycling74.Max             	0x000000010366c6af juce::Component::internalMouseUp(juce::MouseInputSource&, juce::Point<int> const&, juce::Time const&, juce::ModifierKeys const&) + 355
10  com.cycling74.Max             	0x00000001036bacc7 juce::MouseInputSourceInternal::sendMouseUp(juce::Component*, juce::Point<int> const&, long long, juce::ModifierKeys const&) + 87
11  com.cycling74.Max             	0x00000001036baae0 juce::MouseInputSourceInternal::setButtons(juce::Point<int> const&, long long, juce::ModifierKeys const&) + 214
12  com.cycling74.Max             	0x00000001036ba2cb juce::MouseInputSourceInternal::handleEvent(juce::ComponentPeer*, juce::Point<int> const&, long long, juce::ModifierKeys const&) + 141
13  com.cycling74.Max             	0x00000001036b9e82 juce::MouseInputSource::handleEvent(juce::ComponentPeer*, juce::Point<int> const&, long long, juce::ModifierKeys const&) + 64
14  com.cycling74.Max             	0x00000001036bf116 juce::ComponentPeer::handleMouseEvent(int, juce::Point<int> const&, juce::ModifierKeys const&, long long) + 94
15  com.cycling74.Max             	0x0000000103742091 juce::NSViewComponentPeer::sendMouseEvent(NSEvent*) + 121
16  com.cycling74.Max             	0x000000010374219c juce::NSViewComponentPeer::redirectMouseUp(NSEvent*) + 122
17  com.apple.Foundation          	0x00007fff90778dd0 __NSThreadPerformPerform + 293
18  com.apple.CoreFoundation      	0x00007fff8e150a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
19  com.apple.CoreFoundation      	0x00007fff8e142b8d __CFRunLoopDoSources0 + 269
20  com.apple.CoreFoundation      	0x00007fff8e1421bf __CFRunLoopRun + 927
21  com.apple.CoreFoundation      	0x00007fff8e141bd8 CFRunLoopRunSpecific + 296
22  com.apple.HIToolbox           	0x00007fff943d756f RunCurrentEventLoopInMode + 235
23  com.apple.HIToolbox           	0x00007fff943d71ee ReceiveNextEventCommon + 179
24  com.apple.HIToolbox           	0x00007fff943d712b _BlockUntilNextEventMatchingListInModeWithFilter + 71
25  com.apple.AppKit              	0x00007fff8b3db8ab _DPSNextEvent + 978
26  com.apple.AppKit              	0x00007fff8b3dae58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
27  com.apple.AppKit              	0x00007fff8b3d0af3 -[NSApplication run] + 594
28  com.cycling74.Max             	0x00000001035ffa92 -[MaxCefApplication run] + 49
29  com.cycling74.chromium        	0x000000010423f311 0x104123000 + 1164049
30  com.cycling74.chromium        	0x000000010423ec1c 0x104123000 + 1162268
31  com.cycling74.chromium        	0x000000010427d4d0 0x104123000 + 1418448
32  com.cycling74.chromium        	0x000000010429657a 0x104123000 + 1521018
33  com.cycling74.chromium        	0x000000010427ce6d 0x104123000 + 1416813
34  com.cycling74.chromium        	0x00000001041954b2 0x104123000 + 468146
35  com.cycling74.Max             	0x00000001035ffaa0 -[MaxCefApplication run] + 63
36  com.cycling74.Max             	0x000000010374691d juce::MessageManager::runDispatchLoop() + 81
37  com.cycling74.Max             	0x000000010361885f juce::JUCEApplication::main(juce::StringArray const&) + 59
38  com.cycling74.Max             	0x0000000103618976 juce::JUCEApplication::main(int, char const**) + 68
39  com.cycling74.Max             	0x00000001032c2094 start + 52

**Comment by maccallum** [comment]
fixed
