### ISSUE TITLE
modulo discrepency

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#315]
the % operator acts differently with negative values stored in addresses than it does with constant values.

<pre><code>
----------begin_max5_patcher----------
394.3ocqSF0SCBCDG+Y3SQSS7MFiBt4zj8pO66pwzUt45j0RJkElK66tkqvF
ScQMwWZ492692iesceX.cgtApnj6HORBB1GFDfRsBAcwAzM7FQAuBSipiykU
kE7czH+pVnwhqLdoV6lGwhdRMdA2b76JKrEbQr9RJjJPnqUXcYchK0J6Rt.Z
0R5zJ4VwJo50WLfv56R1jYwIQjTVV6DaRR6zTVbB44AFUIeGMhkF26kL22+K
VOJaXuKzEZSm2nkCGNZppdit1V.VjBrNUujcWI3MfRGVfTcL+VsCggsCQ+ZP
CMklXgNGZS7ao8bxnLxUjzdh6hY8wdpOmfI5z9GgOKa1.3O41+D7YW.9nWmF
tL7SuD7uutn3At3MvRiNK5mOTvLPz7oGCHDZ0O+jpRWaD86a2eE4TCmCUVoh
akZ0fbxNKmUx7bPMD3tGV7EE.hpjuzb7xxsfopyRrQbWXV6w2MQXnT4CQDQM
vVYe93dP4F2Ip0cbVavlm1L8ZpuT20LipV1AF2NeH7C.g9D9XA
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
(n.b. I actually love the wrapping behavior it has, but wonder if it's correct)

**Comment by maccallum** [comment]
fixed
