### ISSUE TITLE
float numbers not compatibile with Max

### ISSUE THREAD

**Issue by snopeusz** [CNMAT/CNMAT-odot#317]
FullPackets send by udpsend or converted to messages by OpenSoundControl object from CNMAT-externals have floats set to zero. [Max 7.2.1 64-bit] MacOS 10.11.4]

<pre><code>
----------begin_max5_patcher----------
1274.3oc0YsraaiCEcs8WgfV63xW50rYvf.L65zAnYWQQ.sESByHKYHQ65zh
9uOTWRkHmJGIKao3BjPCSyGWdtm6KxeLch6hrchBWm+v4KNSl7ioSl.cU1wD
62m3thuaYBu.FlahbqXdhLU3Ny7qqyEEhTEWIyRuMWrTYVMJ1eNZlC1CU9QU
iyWsy5wMEJ4cxkvzJmAy9CkK8xrjrbyxflGDxnXV4rwLOTTHrNDpGIRu50Vw
zMqjoIBEHlXam777rusWOKxxiEvh6okI6QfqV9fL89ZhOgxl6o2.FCNEHy2H
n82vrMppcrZsjw.Lks3wqngtk88yoSKal0W.dnPDxwgHTRPMEJNDZCBOJ.In
O.Rp3a5IWgFJwNPfbKDINK3o22FOjVJnZ.qQZnQdUOsVXFsqYEcbcaFEqvrB
0SIvTbcOLhgwdvd6CaqGXOPHGDvHM.Xd8AvxlGKKVmve5WvrOrkmTpZl2BnY
j6.ViXV4pUiOB.6dMGFcceat4cYop63KE0oOk8UH+NzGl7VDzJ3NBD6..t0V
wGBtwM.29iO+Di..lD48NPP8AUFMr+DT1YDwTNKbRZAth.mPjvyCZgOJzBwL
nk4CTOPKZePqEaTJcLxVnQFGxTiRri.yY.THQ3Z93Hrp1ivnizGPYknnfeun
YObdyYTBts.CV.i0M.6bXuQPQ0.qv1XPMAV3w2CkGwDpOX7cP4ar1Yjd6eBM
HAP2mfYRPaSpptPb.vj.oiPvA+VEZ0pGLLVSjUV3wvaImyHqeZsH8yZ7N9Z8
AHOqsPFFD2uiI.BTW8+e5yWeibk3F9YwMYUtIDihDSagJSa.BoCrexAwkmG0
TFnI7jezw6xiPFtfllzH5L23rEzLz3JyKpuAMInyNY3khBFnXejZm49D6CGM
T4ZNroMZh1i86cZi3fQv44X4HzlnHp+NBw9mtCgAyzlYtoHp4ZG5ioMtWkTs
La0JsGteQceWRFWU37cQdlH14JmOx2472aRR9W9x+Snbjo5IpOFxExDo5o+7
MSo4Dz5znWxbvdCRkHT2u5HL5LZCrIdsNbPrSR1RdxCYEJmHTzywA6+wzy5i
yXjioAsPta3bFNB4qdolkom01wljjklbTFOAmWVhV1DxsBfd3b8+7w+5F2dh
Lcj+...Iv..l6d93BR5+6VdATcEQu3vLv+3OxdClNGMnZ6xqcqTaaJtJpGoF
SGZehnS2mH0yjiMwu29DI8ymXYjsrBQu7IhliCg2Uo9G3S39gNMOiViDaUTV
OiGYZEUmzB9VQ7sKzY.lHtMQjdu5A382PM86wbEuROp4nkf.NnrAdTLnorOD
VCRc3OB7rBvAQuZA1oWeDLlcgM+4yJurjYNWEffmeyNCJLJnw4q0HG.b.Iu7
p2zDvT3Q01iwTjsIeYkFzVjsdeeFUiEEJY5yuQ4Wd9UYpOnGjwwhz5JVczX9
hDA.9nF4tcUdfsB2l73OdxCqCxyq.wgTdv9cQewFW4oU803gOvVcAouncw9Z
L4OcPbvim4EoKpKJduA89KOjKLycz3QmQcw7ZD4OjtvmCtrjmvKKwgbYErff
trjGbzn48AHp3KGuyuxv4cWd5RrTL6hJV53Yq2kHEAWTpJuwyvZ.cCZJAiud
8VQdgcIAAQWd9ilxqClAeUlZ9JThratXqrZ7P4qt7bcYvJcMvaxM2xvNelqY
pYwh7zMRXrSK24eN8+E1XodE
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
The udpreceive object must have the CNMAT argument after the port number. o.compose encodes floats as doubles which I think udpreceive doesn’t understand.

**Comment by snopeusz** [comment]
> The udpreceive object must have the CNMAT argument after the port number.

Yes, if I want to receive FullPacket. 

>o.compose encodes floats as doubles which I think udpreceive doesn’t understand.

I think this poses the problem. CNMAT's own [OpenSoundControl] object also doesn't understand it. I 
tried to send OSC directly to INscore (inscore.sf.net), and that's how I came across the issue. There are probably more apps that doesn't understand double precision floats. And there is no way in Max to convert them to regular float.

**Comment by ilzxc** [comment]
Yes there is -- you can use o.downcast before forwarding the bundle to
udpsend.

**Comment by snopeusz** [comment]
Thank you, it solves the issue. But I wouldn't have found the object without your help. I assume there is some experimental staff in /dev directory, thus not included in search path. I hope o.downcast doesn't go away.

**Comment by ilzxc** [comment]
It won't go away -- much of the stuff in /dev is quite mature. The only
thing we do not guarantee with objects in /dev is the consistency of
interface (number of inlets / outlets, object arguments, etc.) This means
that objects in /dev do not guarantee that a later release won't break your
projects (but we do highlight which objects interface may change).

I'll open an issue about moving downcast out of dev, since it's a very
important object for anyone wishing to provide glue between our world and
others' OSC support.

**Comment by adrianfreed** [comment]
downcast should be moved ASAP. It was parked in dev because
we didn’t like aspects of the argument api. It is more important
now to get it in the release than fix that.

**Comment by snopeusz** [comment]
Is there any official place to engage in conversation with developers? A kind of forum, mailing list or facebook group? I'm sorry I ask this here. I don't want to abuse the issue tracker, but I have some more user questions. I want to estimate if odot is the right tool for my project(s).

**Comment by maccallum** [comment]
Hi @snopeusz---there isn't an official place to have a conversation, but feel free to email me at john {at} cnmat {dot} berkeley {dot} edu and I'll pull the others into the discussion.

**Comment by vigliensoni** [comment]
Hi John @maccallum, I'm facing this issue again: double float precision values sent by an external device that I need to read inside Max.

Is there any way of doing this?

Thank you in advance.

**Comment by maccallum** [comment]
Hi @vigliensoni, the odot objects all handle double precision floats by default. Can you provide a bit more info about what issues you're running into? Maybe print a packet from the device using o.printbytes and post that here.

**Comment by vigliensoni** [comment]
Hi John @maccallum, thank you for the response. 

I'm sending double values to Max. `udpreceive` doesn't seem to like these doubles and only outputs `0.`, as you can see in the image:
<img width="414" alt="Screenshot 2023-09-26 at 4 29 41 PM" src="https://github.com/CNMAT/CNMAT-odot/assets/492229/fb407d6d-a809-45d0-a010-be9ba8b55665">

The OSC packet coming from `o.printbytes` is 

```
Byte #      ASCII       Decimal     Hex
00000       '/'           47            0x2f
00001       'm'           109           0x6d
00002       'p'           112           0x70
00003       '/'           47            0x2f
00004       't'           116           0x74
00005       'o'           111           0x6f
00006       'u'           117           0x75
00007       'c'           99            0x63
00008       'h'           104           0x68
00009       '0'           48            0x30
00010       '\0'          0             0x0
00011       '\0'          0             0x0
00012       ','           44            0x2c
00013       'd'           100           0x64
00014       'd'           100           0x64
00015       '\0'          0             0x0
00016       '?'           63            0x3f
00017       ''            217           0xd9
00018       '~'           126           0x7e
00019       ''            195           0xc3
00020       'Q'           81            0x51
00021       ''            138           0x8a
00022       'm'           109           0x6d
00023       ''            252           0xfc
00024       '?'           63            0x3f
00025       ''            195           0xc3
00026       ''            248           0xf8
00027       '''           39            0x27
00028       ''            172           0xac
00029       ''            222           0xde
00030       ''            239           0xef
00031       ''            240           0xf0
```

**Comment by maccallum** [comment]
Hi @vigliensoni, the `OpenSoundControl` object doesn't handle doubles--it predates Max's support for doubles, and was never updated. Please file an issue here: https://github.com/CNMAT/CNMAT-Externs/issues. In the meantime, use the odot object `o.atomize`, which behaves much like the middle outlet of the `OpenSoundControl` object.

**Comment by vigliensoni** [comment]
Thank you for the tip about `o.atomize`, it did the trick. I'll file the issue in the other repo.

All the best!
