### ISSUE TITLE
o.route slash broken

### ISSUE THREAD

**Issue by mzed** [CNMAT/CNMAT-odot#319]
A lot of the CNMAT-MMJ depot relies on o.route in abstractions, like:

[o.dot slash #1]

, where one is an argument giving that abstraction a name in an OSC-like namespace. This currently doesn't work.

**Comment by mzed** [comment]
Here's an example: 

<pre><code>
----------begin_max5_patcher----------
462.3ocyT0zSCCCC8b6uhnbtTZ51ZGbEItBRbDgPYsFVFsISIoiMP7emVmtw
Fi8AUhONzTYGG6me447puGcjZNXnjyI2R77d02yCc03vq01iVxmmUvMXXzRv
X3OBz.2dS41rwB4i2qgLqKOwomEFEP50m07iMLp4WbbXD4t1CIqJUU1Bvhoj
05UjiEPMZxICWkdMX.okaEJ4NKQT6xp76RtcwTvENktdoExkUNt0owtn.CkR
ab7lueyRP2XDKLGQI8zGpd4kEmZrZfWRJUboPFxyyCM4hGHQ6gAYrAH0E0cF
L8.L3lk3OlAkvy0XdKB7pat3DcMR.hoNzwDjO2mvKIAIpTrcX8XGf1h2l1Rn
6j.B1IIv9IjQeQ+kLDE88R5rpXvATEaTg+mhBU32QRLDan3jXjxXGRQzaaJq
+9UD0eWVUTbMO6Iv1I8AdFZgP942gw1ow+ljjQUoyVhgVMK4iFJGLVgDuXWK
l5GTIrUwLVjmC31QKOkvvGU.XaG8kWVGKZROBzrIh+qQS+eMzz+HPyfNdS4j
Q7oSmAZSaJQfTOUMQoaLSCPSgzYhioTMLSrLdmGttdJxVOBUocp04Itg.ZoJ
GzxJAJp8ap7a9uCjRmdP
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/38

**Comment by equilet** [comment]
https://github.com/CNMAT/CNMAT-odot/issues/300

**Comment by mzed** [comment]
So, does that mean "closed; won't fix" ?

**Comment by equilet** [comment]
Hi @mzed - I'll let @maccallum take the lead on this one as it's his issue for the future.  As you may be aware, no one is currently maintaining this repository. I'd recommend closing this in favor of #300, which is the preferred thread for the two that are active.  @maccallum can speak to expectations regarding a fix.

**Comment by mzed** [comment]
#300 seems to be a different issue, at least from the user-facing side.

**Comment by equilet** [comment]
Same issue as https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/38.  But you're right:  the decision to remove the error doesn't resolve the need for a new mechanism to allow for dynamically setting pack, route, etc.  That's a design issue for a future release that has been on hold for years now.

**Comment by equilet** [comment]
Here is the temporary solution in the depot for cases like this (note the errors in the console w/ this fix):

<pre><code>
----------begin_max5_patcher----------
663.3ocyV00jZBCE8Y7WQFdlhj.tf8GPetu2wwI.QksPBCIX0ty9eu4K5FbU
W0531YbRjjaNdtmbuG7kId94rcDtO3qfe.77dYhmmdI0Bd1m87av6JpwbcX9
rvBVSKiS7CL6JH6D5clthwT.AC.n.P7hg.n8MrdQMQnA.ZWcEiJVgKHp0hrq
0hEEapnqW1QJDFRkLKLJ..iMSyhTSnjvHvBGb3U+ViCDEN.UUogs4O+EX7.S
LzPrukX.22+uvHIYEcfiHmTqfUy5LgGEByxBNXB5vENdKobYdOsrlrrlPWK1
nNYR1w1uDKvFbimE.lqfBlpFTIZjdPsVjTNitfOHYvIpyGgTf.sCtgjjn1dl
6vQgx8XHmuGCVnxiWmLQMDbwELkU71Z796R8.JSWIXmrEDwWYAA5ZKHfGuf.
p4f6vMoPMDNGu98MTbh..ASyqwaF1iK1Wq4p+4UyinbwoFIKSKYxaesNhbTN
GIJ6paYtg7VBPNo6RSMzYJJfVeA8j0j3DYV5oyr.feNlt9sLrE2gaHBR2RBE
mWOp1bb8wM0WbRiT0Mtt5M9tzyXu3i9G7P+rsPie5AXgBexXgpARcx4Z+zji
Ygd3QQ2l4Hk7Ko79tJ.VXmTnIfok8MM6uecH1l+4ImqCAc1Nju0WW+cbwOIh
S4UdGkAsJrT5CJ6AA2KevjQsCQomSKfWacejS1qivuthd3+vRyJ05ikDNquq
X.eaWG3MZUR3hJJVTwnNwfFEylpxRB00OP9xWk0U4gjK3pYC5BXS5CkMvOfM
vGm3.++5tBdArIajB9YylaUaLMY311sjNtERMQjNLOadsSZf9wJp4QsMoeGY
a0P7lUvcRqBgzmnuyXsr6oDeyQYkjNZek0dS9K+5j+v+PhuS
-----------end_max5_patcher-----------
</code></pre>

**Comment by mzed** [comment]
I was planning this work-around: 

<pre><code>
----------begin_max5_patcher----------
1178.3ocyXs0iahCE9YxuBDOmYJlKCY121NR6iaWo12ppPFvg3VGaD1LSZq5
+80W.hIAHjocZGoJxzywG6y4ymq96qb7xXGPbO2+x8itNNeekiiljhfS6+2w
aO7PNAx0KyaOhygkHu0FdBzAgldbbGoJnHeGlVlVixElsF3Gcq+Z2vfD0OIg
puAA2569oVYnM6YMBBRnODPKUbgdqYYe9FvwsuFwQTATfYT6iHJv5H7a+ze.
lcW70JjY4dd1mMl1czAsD4huRzK0ySQ3GqVo9rdgfDE8jToOCid26e3lZolf
b4xktyEVTHMF9b.W7FMVEpwOPT7EPtfQPtHuIwf0ShCfWRbnxMmQeDUKtQvt
4DGpw.gHsCCHQeqBL2vWo6Sn2U5HLB.Xqgn5Vyt0tc71hIHoMwktkVx63Aqp
rH6XIhBr9LSuQIq6IgoFRA8jpQOh6j+HUXsDmDRPpo1neGtq6lVsMrBTMsAq
UECQ401ptMrCZ86CVtKR+SzFqnFGOTAVntLxJyYDidoDZSr+8aTBt49H.P+W
I24mrIRd8XKdVIgk+Ej9dvuiHqBQwT6v3ArKPagMDQ5VFUvweSaa.Ur8H72B
yQSJLEt2.L+cMFR5fFuxZbAipTBa7TSt63TwcZWsXaiQuBJr5nv82wRWLIjN
AStzHa3YvZ0sXlwYp+XELFYHqd4HnshV1UXJ8DTTvpllYMtb2LxlwjL2O2dq
4vSanFtoxHZQJG93PzV.Ij1P7ga+AHEuGJPBr4JHvumIhBkF5NddMiPFXuFN
ONBmBY.PN5IbgXm9frcFjKGW04D40eKWfKQbwPZBXIeHkyBtkjZxZCvSEn8U
DoUXp68sTkCvQhVV6wJn1Q21IGGPetjjCSTpKVTIWn6+zPH+GTFKIrW3HIKi
MII8ayUdVo1oKZbVNSe6iZ9hGSVHcrhHNcERZyJ8qG2dmLF78rFZwCx7.R2o
kgYw5BK.vRvrvIvrKCYq08A7AYjwGfky.ffWb.TeVKBZL0FB6+NCv.l.Xt.x
LMN3ONNXQMmseurTxub7wnkW.fhhLMnc+hQH+IPn.uqzU3JffiUwHX5ToqzV
mh+3XCm0Tm2cg0kfvcnkJyGK6Wnun9G6iJNYc6vEEH5onQAlqJAXJFsnKxqV
kAKUk8e8nyRMArDUN30iJ6+6Vmc+zJ6db8T8pTjZ5KKEJD03LYoT9oMseU8O
HalMCRZ6Nnu6x4Zl3XGGqNpuW4LTSMv8aZmdzc9IuamcBr44N48cd+QFg9my
rSrGa94X0Q+YrZ1sxL4UL9L1sr2i9gYsmABLMZDqeZjMlYZ.lwmitHZL9.X1
fThsdzGP7fLa.FU69unmbeKiTXaJClhDrQO4n8OfelmrQGxmI65ifRIHZoYZ
gH+w3W.EPy1FFu1UMLqDXTeLMOq9nn4Cjp1B9WfpIIo72mzKtFqiZ2C.Ht8i
sTQZ1wmsagglzYsNOZydXgaiuzooka8nNOcbjcV1oREGamy97zvmmB9Le6Eq
OgKQeFpzuj5ycKQcB+soNIutTmEcaE8LcdL91m7FYJM4j2F6j2E672Da52C6
z2BSdx+X0+61CFDN
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
Use whichever you have a taste for.  The spectral tutorials are due for a complete overhaul when the new version of odot is released...  Many issues there regarding CNMAT best practices and current views of spectral-ism in music.  Another shelved project.

**Comment by maccallum** [comment]
The workarounds seem reasonable---please reopen if you feel strongly that these workarounds suck and o.route should implement the slash argument.
