### ISSUE TITLE
o.union unexpected behavior when addresses contains brackets

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#320]
address matching seems disabled when the address has brackets in the name? (this came up in connection with pattr)

<pre><code>
----------begin_max5_patcher----------
476.3ocyUErTCBCD8L7UvjyHRnszV+.7r20NNAHUSMjvDB0Vc7e2jMPKUEKi
iiiWRHKa17dO1W3UeOTlbGsFEbUvsAddu564AgrA7ZW6gJI6x4jZHMjf9rLa
CJz8JMcmFBKiZDLonKtrQyoZ89Jpq1nqa37aH4OQMoupMoZ8dN7dT21DMkLg
YivQkzFrhnyejId3dEMW6JW5xzn3v.b7L6zrX6XRRT7gRyJbnJayE34S6UdG
vf5isAey22NDNR1KiJX0Ubx9OI.WtVJuEux7XbDN7NwIq6xlyDzbYiP2meqk
BcM6EPIvFRzqx4RtT4nLFHb+gCj8Sh8QI9DAEedAcxxnYloD3LltXHEcx.JZ
OFsljCvI9Gnxq4RSgGrWBEFfxHhGFcmz4IdxhQzHktDcffpRBTgzuTHN15pH
kTMUcOUPx3+XAYPSWkwREz1p8a58NuhkBiKl78J17ya8fMBNiObODb113mJL
0xFUdG0NXvCNBfBZslIHZ60Q8yZxIY8HqnfBIzY3LNa62nhg+HMZDY48HPzz
+kHB+GgnkiAQe.2iGQt1JRU0Vpptsn.XLNqMtKUmGBKYB2RvzhTzsrt7cQHJ
iEPa5+aTNGytT2eTPkxBpRzvZaoMm7a9uevutVK
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
I think this is the correct behavior, although I agree it's confusing. The rightmost pattern matches /foo1, and the left address is /foo[1] (it is not treated as a pattern), so it doesn't match. Feel free to reopen if there should be some discussion.
