### ISSUE TITLE
pattern matching operations with message addresses

### ISSUE THREAD

**Issue by j-bresson** [CNMAT/CNMAT-odot#322]
Enable working with regular expression in order to target specific messages in a bundle when filtering, reorganizing or processing messages.
Examples: delete(source/*/position),

**Comment by maccallum** [comment]
fixed. patterns must be enclosed in quotes to avoid being interpreted by the parser as expressions (i.e., /foo/*/bar => /foo/ * /bar. I know, allowing the parser to be permissive with a trailing slash was probably a mistake...).
