### ISSUE TITLE
o.edge~ emptybundle output

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#325]
I see in the o.edge~ help patch, there is an `o.if emptybundle()` -- seems like it would be better if o.edge~ didn't output empty bundles, since it's supposed to only output when it has something to report.

**Comment by ramagottfried** [comment]
that said, I'm not clear on what the functionality of the emptybundle is in the help patch, I think it might not be outputting empty bundles after all, in which case the help patch should be updated.

**Comment by maccallum** [comment]
I cleaned up the helpfile
