### ISSUE TITLE
o.expr range function is the same as extrema

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#326]
the range function outputs the extrema instead of the range (difference between min and max).

<pre><code>
----------begin_max5_patcher----------
601.3oc4UE0aaCBD9YmeEHdZSxKEvNoISputm26aQQDaZBcNXK.Gksp9eelC
bJNysKoZ8oIk.g6N9tON9NxiSRvapOJLXzmQeCkj73jjDvjyPRXcBdO+XQE2
.ggqmVTuuo1HvoduVwQK34FCeeSkv3.ijhnoHVJJKEkuJ86pazb0VQvk2xdo
pC4Sl5wqRpDE0sJ.zrfQU695VakvBjfFr1vsE6jpsq0hBq+PPmkMsCtLxB2D
ik6llQmRPqBaRV5OGad3Sr9bdesxdOuP37PB174y9yFgGYL9DDtvMxeANnro
86nQKLBkkak0pAThDQIRX3DXt5WQcUs1GMYJcwhzylh4eWoPp5qDrfQC+fnb
8lVUYkXckPs0tCHGYwXATxsbe1xlkhV5R.8V2f6Zi.CNajtqPxE7I28E1uCM
2OHKcqXw.ANGrqbmmYiO7JYKlTrnemEicbLmXWdfc9iY1fS3P17hmzwvENrv
V8.uLjF1UgLZk6h5oISbCouiMi32XKEcIzKwnfB10XMVKE8eaK06Yywbx+m8
FuQkl3XitStUJbA9GxM+y62gf4Ozq99Xz672g5BVK1ye16nO4yFUex9q5SVl
ehBxz74uf975dy+KsUUekW7CgEmNX0UKbid5+UjrznqFHBn1b1ePC0.m8g2W
l5VcQOw6OqnmSTovXkJ3emhBxEC8TL6jkkBUbIoTZ3apDPEjLpv4hoyEvlyn
7kSGewh2zbPnMALAlzIieveKbaJrTp7KAEEVKNH6iOGrv0cBLam5pUCrGebd
N1u0NwuV0JCWTcY9oI+FuWQC..
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
fixed
