### ISSUE TITLE
match() with wildcard

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#328]
love the new match function!
wildcards aren't quite working the way I would expect, is this intended?

<pre><code>
----------begin_max5_patcher----------
771.3ocyW0zaiCBD8bxuBjursUdS.rchSkVs21y68MUUDaRi6ZCV13pzsp+2
WX.m57kpS5GpRIPXX3wL7lG14ogC7VHWyq8PWi9CZvfmFNX.XxXXfa7.uB15
jbVM3lWhrnfKTd914T70Jvd8JYSdp3aJDZ7Rob7UiWvpPK3nRVkJikiJXpjU
75e1tRQSgrQkyU.tXm0RiWYh6tshmnrwEYRvHrOhDOyzQoTnCOBitwsnrTHD
jKt+6S6.elnEchyXs5wbN3qmwvyCGZZ76YpKGklUWlydbujGxXBjwWiB7mK.
CTmAZqgBtdTjYTg9GOMWLWMVmvJdkPOdtm6f6p4d9vbKaxyMGAy6rA54Z8jZ
GeiuCH647FfJ3s3zHrG9oyEO2F64YBdhrQ.IvrCxIsmZKkB0RVB+U3oHZrkY
.dJHFCrVXPGhxfTc1+.jHFdbO9KpM9rwg5wRtEcOuMnTVwq0kfLUlTbz8G6Z
1rJCYkHykUtpJH551rwysKcNqBE95xpQIxTtww8pVJP+vJGtXKNGcGWwRS0Y
WMu9hKu7vJE5YwJjHHMCv1N5IQJgGkT9ktB82rj+x0WHr0nWirlDfspYbeHq
sb5cmr9TT06no2Si5ju6HX6g5+CUSSvg.MQheCZ5fdno+RqN+nzltSWRn8Pd
J8Lzlz2f17SUkoewgRYM+soxNXkdv6Xk9D2skvIPD4jnBxoWmiGQhi82o6nG
7skW0rG3o2tnQjlyuMmKtSsxLcb3glOkoX1MKHxGMyfOYpowjmXnwXCSz6eO
9P0eCMqGSMfPbMFSgyr8l8XFrEgsqJLzrhn8PKneHGgOYjoc9MYxQQlfm8Rx
eLrhP2zojG3FnBbmWbFppL12VGTKapRZqDbONE8BCmxqUYB34ic7IZKeVkkl
xEcqf0OyhsHmCEe3CpG6azP5QzD9kJZneZQCsGQSvYFM1xHVY4C7pZGjPfnu
37d68CS8ggYB6PP96UweHq0ePv6wpzWloz2j0TY+yMqmXeiMuB8y3pDMYtas
067yC+uhrtDj
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
or without the wildcard, shouldn't /foo/bar be a partial match of /foo?

<pre><code>
----------begin_max5_patcher----------
611.3ocqU88aaBCD9YxeEH+TqDKAafzjIsW2y68QTkCbo0cfMxXpRWU9ee1m
cVI+pJqqRIFtONe2m+t6fWmDQVq1B8j3uF+y3nnWmDEgPNfnfcDokuspg2it
QTSqE8cM7WHI9mZfsF7Iy1nTynyVy0VqrjRIBvB.r8.sf0pvY0Zu40RYoYVG
2X.szZWhgojjf3aFZZRBdnMBdvXP1xMUOB0NdWNJw18EhfOuiragRxpR4t8z
tQHgJ0fD4NMMfJp8Gx0O8krwGvJUiR6kI5zzjCWhWE7TNzpFLMfAkJZ.0CYd
oC7AfPFuAg7X+2njlM7Jz687pycdExGtWCUl.ORyc4mkhzHaQJxlh4i3iKR8
heiQhxll5P2MYhaI4pK2v1N8zJUM3b7jZda72hwhwM+sxE+.X300ZnuG5u41
aImpsrKns3Y3skKqsrKose21w7Cd0u.ikHis9L0bZtW5uigRO6yVxqTscpd3
+aB6rM5YmVKnWrVPWrH4nKedc6rOjxOeguKGaOJnuivGf64OC02udPV2.22.
xGLO57XQ94ddM2v8oKqHIdo67Ruys3xYJt3vRoV83J9wr+yc6Ok4BBMr3fxW
5u5xwRLE462UdtaGEmDsrqKxEo+yQlM5d57KFYZ5x2N7WJVEwqF0xiUGrC7n
uwfUXG9gyA8pAc09FmvKJheqFWC8FgjaDJ4HexNvmGE00fbb2j86U70M.1we
94wqkMzqfMrOHa7REuq6YP2GBIRD6KGdxOSdWBZJjdSbBhngmE68GapIbsc3
wXmbFzH4IammS7a09VbsbPfyHSbYd2j+..lZbiA
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
It's intended to work the same way that o.route and OSC-route work:

<pre><code>
----------begin_max5_patcher----------
615.3ocwV0zaiBCD8L7q.4iqnI1N.g1qUpW2UZOtpJx.NItKwFgMYS2p9eew
1PVx2zzjTIzf7v3Ydyyddh2bc.IhUTIv6Aue4437lqiiwk1gSyZGvBxpzbhz
DFHoRoDbfu8SEDU5bFe1jRZpxllv6GM.56EBCzuvqsdO2rGVlIQhjWtCE1lH
d0BFOmpLEA03TpdMmZBtSXhJ01wYcodsfZg.HgvmAVWvhRpjxUDESv2.nHKP
MufMFum0a5cWWsw+hQJHX+IknuRRAFeoHkETojLi1hREckoFfgSEhgeyCAOM
eEfrGQgF9Bd.9JXu7E9yxWfypq4z+TCpcZ5u+yGuqrtDTOS6iFlPJ6Q+GZto
fv3iR.3O0EF7AI.+ykDN47vnfv9OOf9BmGFgQc.50Uj.Gg6Oo.upjxYzdhAo
hEEB4AG3enyH+TAWMkjZpJriOI6uFeHMSbJhJ.N1LcDB2goz0NUjKJsa.N.E
G6u0Kz9Y13iplzesi1SBxRZ1jjJdVNcRNkOSMWGynn888LhhzbuKz26dMHQi
0FcaBMFsOHptI5wCJpljz6Gh0IA0XztBvsAEDnCHb2MCuj5ehAe.0u1y2F0O
3QU+htdheOUkm+CR5uopMGILv.jy3a+qSldQ6eSBRJpJSaSbqhsGZc2jQkJF
2H8zMn5eNx6+s7bVVFk2cfIiIII4TCU.26Q0GBOvSgmnaGdB5Cdv2L7D0miK
zMENmjcf2L3D2C3bt2criZjhhkzRYSJM.oV04Eq79XeyRF2tzLQCJoKYswOx
3gTVKynp0XpJsBBqhsRGfEhLZIuhYzMb0U9c2+QEkX+o
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
oh ok -- I was hoping it could be used to give a list of partially matched addresses within a base name without having to know how many levels to look.

**Comment by maccallum** [comment]
If you just switch the order of the arguments, does that get you what you want?

<pre><code>
----------begin_max5_patcher----------
633.3ocuU0ziZCCD8b3WQjOsqTJXGR.Rk50dt2KqPljAvaSribbPrEw+8FON
vF9RJKsak.6LOO94wyyi89AdjkpcPEw+q9+z2ya+.OODxB30Z6QJ36Ry4Una
D0vLQUYN+MRfaTCryfiLZkRMhMZIW2XMNXtDABaABOBT.MVwVqB6xtetbtYT
I2X.srAXdGdlSBvQWUmmGz5m1H34m76nG0xBtIcCjMWdHv+NbF9IvYA7XD9x
wzWtPBopZIlCYIsnhLWxd4qeIpahNUkqzN4hMjFbdi+KsdJqKDxbvfJFqEbk
RZVwSAKFsCVk32HFKbH884qpMWRPoFp.ogaDJ4BMjZbwQbB0t9gzw1NZayoX
wQj4sRv4NgbZnRa1PHWeKxv8z3YNqoIVBsS5vfA1lfdeXE1UpGlpx.qiWchs
v+a9nl7zZvvyxZ1gUP0SOGbR4dlbshDeGEg1MA7YpHg8RQXQS5mh78lSt+fm
9KvPBNypGJEKJxIQgnfE9vBUppnTUA+c2pbyhpwWqfStqBxlMK3ht6pig+ep
rlR+2UXMYFJZwnQb2cVEeKjsXYsLKGVjCx0lM1YNK5VimwMbGuiiC7SrII1T
aikbJ1XwnrlPtG+Ba9GYmOMzRBqswBEk35sqQBtDQGmUTjcFwWw139wbL8Cy
bXmuYStKyLZx6a96wU7Y0InLfGau3wXTJs3mW7Top0oGE916j7eWLyfJiPhm
m53SzY9rQjkAxtmYadXmuLGvxD5MKh6azLoGQS7CFMtTEurbKnqZoDCjlaTd
0UHOM.MERmIVmRzvVwQ+wqDHbcSUhooDoViAOY2L2ECjhlGLzxZAVjNvtxGF
7Gff7PS.
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
whoa! slick! : )
thanks -- just to have it written down somewhere, here is how you would aggregate the list of partially matched patterns:

<pre><code>
----------begin_max5_patcher----------
717.3ocsV0zaiBCD8L4WgEmRjXS.BjlrR85dduWhhLXmT2ErQfoJcq5+80yX
ngj.RoQckhrimOddrm2C38INtopi7ZWxOIOQbbdehiCZBL3zt1wsfdLKmVig
4plyD0k4z2b8rd07iZzyh8J0hfEozJypkdIRzPXqgvNCEbypXXkwAXoyYATE
umHSzKJoZMuRZLjzC1DWOz69l7bu13pzBZ9mw0EQirfpydlyRje3QFAyv+CX
Vv+FAr89YTDu.ldafAwsvUZaf6rQTCWv8KzKuIt31daWKNWH4YpFI1mCW0ZU
vrDhzW9QTWjxlBgLmqQtRPOFRlJWUY4YAy88Nefr8T5pF8k4uWI06oYbvleq
sR3DIjG1Uwyzs3tDwKLdMLEszGlV9PTO7AjpE+EQJHbdGX18T+VI2hjqKYK3
4iISfAuaVZvOVVMOSw3PfWoOJHORvNwzCbMkwp30075oy79ruManl1ijmflY
hoOWNkjHIjbZQJiNsvCVPHh8SIol1CaZw7trm05iPFBOLNjo4ck+s1DmASlR
aQQhb1fDg.+qIBweEh.1fNMLNQH7tHBahPdPvJD736gG7Kij62zr+v0FwQ+U
2I+HSUTpp4eqO5bvdSz0slUC1ZBGq0Drds2ESe2J0fM1NC18WEee5zVW0zW4
rcoFQPNeWNWdP+rkitdn.XTM0BwxXCQANaAO.CP83iCfM+.yY+F9EB7LHe+P
.jf1AvTzF6LrGavsHpKqnHHi3qPa4sgbr+WF4vd+OX0nHG3u4zgeLrhGnJOq
TF.794OZMdlzB6uH09hORAYUf8y0a0plprN1QKqmbhWw30ZgjpEJYuXhOKlm
ELFW1mAa9fGZZNGkR9Cp6u0pI9Fpln6rZrWUzxxW4U0sPhEh4gPuX00O3gKE
R6RT66VweUzEeLZgVYDrZiZsoBKd2iqruf2sv7psJYi.kVSfc9iI+CPlKtn9
-----------end_max5_patcher-----------
</code></pre>
