### ISSUE TITLE
odot not parsing dictionaries on windows

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#330]
version v1.0.8rc-2-gc... July 2015

**Comment by maccallum** [comment]
@ramagottfried or @ilzxc : can you build a fresh version of the objects on windows to see if this is fixed? Make sure to pull libo, libomax, and CNMAT-odot and make clean; make everything. I don't have access to a Windows machine at the moment...

**Comment by equilet** [comment]
I've built a fresh version of the 32-bit externals, and added it to v1.2.  You can find it [here](https://github.com/CNMAT/CNMAT-odot/releases/tag/v1.2).  Let me know if this fixes your issue, @ramagottfried !  There was previously a hidden version skew in git, also fixed with amended tag.

**Comment by equilet** [comment]
https://github.com/CNMAT/libomax/issues/2

**Comment by ramagottfried** [comment]
hey! great this works now: I just tested and can confirm that odot parses dictionaries and converts them to OSC bundles as expected.

but it looks like o.dict isn't working on windows.

**Comment by ramagottfried** [comment]
jeff and i fixed o.dict for windows yesterday, dictionary io seems good now
