### ISSUE TITLE
odot 1.2 release request

### ISSUE THREAD

**Issue by EdmundCampion** [CNMAT/CNMAT-odot#332]
John Mac reports that he is finished with all the current round of odot fixes, and that odot is ready for a 1.2 release.  Thanks for follow through with that.

**Comment by ramagottfried** [comment]
I have one more crash that came up in a student's work that we should fix!  I'll send it in now

**Comment by equilet** [comment]
Are we sure that it's v1.2?  `git tag` yields the following:

```
v0.10.0
v0.10.1
v0.10.2
v0.10.4
v0.10.5
v0.10.6
v0.10.7
v0.10.8
v0.10.9
v0.10.bootcamp
v0.9.0
v0.9.1
v0.9.2
v0.9.3
v0.9.4
v0.9.5
v0.9.6
v0.9.7
v0.9.71
v0.9.72
v0.9.73
v0.9.73-bundle-syntax
v0.9.74
v0.9.8
v0.9.81
v0.9.82
v0.9.83
v0.9.9
v0.9.91
v0.9.92
v0.9.93
v1.0.0b
v1.0.1rc
v1.0.2rc
v1.0.3rc
v1.0.4rc
v1.0.5rc
v1.0.6rc
v1.0.7rc
v1.0.8rc
v1.0.9rc-mmjss2015
v1.0.9rc9-mmjss2015
```

**Comment by equilet** [comment]
I've released the latest build as v1.1.
If anyone objects to this, please speak up and I can amend the release to bump it to 1.2.

https://github.com/CNMAT/CNMAT-odot/releases/tag/v1.1

**Comment by maccallum** [comment]
This release should be tagged as 1.2

**Comment by equilet** [comment]
OK, thanks for confirming

**Comment by equilet** [comment]
OK, I bumped the version to 1.2 both in git and on the drafted pre-release in github.  The older v1.1 is now removed.

**Comment by equilet** [comment]
https://github.com/CNMAT/CNMAT-odot/releases/tag/v1.2
