### ISSUE TITLE
nfill error crash

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#333]
<pre><code>
----------begin_max5_patcher----------
365.3ociR0zSCCCC8b6uhnbBjJil1sABItxYtiPnzzrsLxRpRRm5XZ+2Iwoc
qiMDbwQ9i77yO68oI3JcG2hQOgdCkjrOMIABEBjz6mf2P6XRpEJCW05bZENK
lR25jbmaWCOhAthpVhQu2m151IgL3gOnZ2HT9u.fQ5C1PcrUB0xOLblKBTwL
xj7LDoLO7TLcvdDZQMfqtZ8cki.ORnH5gfGRSClr+4zomv6ZLSX5Zdnvdbc7
NfV36YFpcE5YjZgPJugb6upCuzJkuRYexc3ry7NN.WUIVnUtETFfR9eqNyeD
dlAhTYwH4I.jU7E.Dwm3RUibcUqXzLyzRsI1QnCmLjPqFouPewRg5mGS.4Cw
OWzs5VCaPq52gnSrulacBE0I7WZmpgbVMqD00b0XgpVXoURNLh4WPNZSyVtw
1CIPD+tecb.eHCbEpnaI3Z3aEC0CKHL032DN+Zn0DOq6lOEG+p+hwnZE8Gd9
NeH8abdWKeE
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
two bangs

**Comment by ramagottfried** [comment]
fixed in libo with commit https://github.com/CNMAT/libo/commit/873c1673b1142603be180564b161f4b4272c187e

(added num arguments check)
