### ISSUE TITLE
o.message and scientific notation

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#334]
Under certain circumstances, values that are bound to bundle parameters can corrupt o.message and parse incorrectly.

Note the following:

<pre><code>
----------begin_max5_patcher----------
490.3oc0SE0aaBCD9Y3WAxuNFwFvPn+UFUQNv0VWA1HvDksn7ee1mIMjs1pp
s9RkhNy8c28ce9huSgAj85ivDI5tneDEDbJLH.gb.AK9AjdwwlNwDlFQmzn6
GzS.I1G0.GMXjMMyvFVt8yS0pZyFirG1zOY8YIYUb3azhjXLhRzCV3ZBnZiR
qI0pyWXqSpfF8rBoLeAT15a89m+d5511n6zidwSSXa2F+GGrDZz8K4ql6kpN
vf2hzEvGzJyChFvgQWgMI+EhwnIzq0qmMWHfsfNLBSfxHLRsZ2HzX7pgmUZK
LJmhGzEyKZwSj4mCfOcB4kPCBSySR0iqHKsDIfQ43QYl6fWrhuIwAnc29YUa
GrqCTOZdxq97WKgVgQ3YNiGGU4lSrRmAaBZbXTlUzefeaysWTa8UUWHxUoCI
2hvSwjxcIU7W0VXazmhHRWDAiUfSJmoZkT7dL9sU4TE1rE0XCyyhiJyby22p
SzKcx9QU45FcKuWaFF75MKyNR3WoL5d2+QmCCcl3+6sP650s6gu2l3qtKVa9
vairuFai7T2JSVV5mv1XI+eaYj99qh27J.4hHFFN.iS16B9Pv8Lv9H3Y+LtL
FckJuaF5NBGjWxGmIDwnU+Fq3mGwaG431BhuTcKLplkXtgtNeN72f2wWpC
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
My understanding of the issue is as follows:  

The compose box on the left is generated by pasting "valid" text from a text editor into a compose box.  The compose box on the right results from editing such a corrupted bundle so that the param reads...

`/time/ms : 1.395e+06` 
rather than 
`/time/ms : 1.395e+06.`.

...when user clicks out of the box, libo reevaluates the text and generates a period (.).

**Comment by maccallum** [comment]
I’ll try to fix this—this is actually a known, long-standing bug.

**Comment by equilet** [comment]
@maccallum put in a fix for this today - I've verified that it works, but will hold off on pushing a new release until after next week's course.

**Comment by equilet** [comment]
Fix has been rolled into the next incremental
