### ISSUE TITLE
o.expr.codebox crash

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#335]
this crashes, discovered by a M158B student

```
/preset = quote(lambda[],
```

**Comment by ramagottfried** [comment]
fixed in libo: https://github.com/CNMAT/libo/commit/68df89fb9ab2e9e18dde213224f5475ed1860b0d

**Comment by ramagottfried** [comment]
I just pushed a fix for two other quote related issue connected with this:

https://github.com/CNMAT/libo/commit/b618e6129f6a00bc912d9a7cc34af7495d71fd41

1. the original fix I added was to make sure we weren't reading outside the text buffer by checking for a `\0` -- but because the matching rule in the lex file was set to `.*` it was inserting EOF at newlines, so if you had a newline in a quote it would fail to parse. To fix this I changed the rule to be `[^<<EOF>>]` which now appears to be safe and includes newlines which I think in this case is what we want.

2. the rule for the quote() function is that there cannot be un-matching parentheses, there was no option to escape signal parentheses so I added a check for this, which now seems to be functional.

here is a test patch -- I'm going to reopen this issue for a little while until it's been tested a bit more.

<pre><code>
----------begin_max5_patcher----------
737.3ocwWErbaBCD8L9qPCmLSn1HAXvclLSO0y8doSGYPIkTrDEDoNMS92qz
JiCNlIA6Pr8Azn0qzS6ae6h3wIV1qDaX01nOi9Nxx5wIVVfIsAqsysrWS2jV
PqA2rWypqo2xrcM+mjsQB1SrQ+oQHYSQEzBDEQBpPNHmD6VO4MqEMxBlD1G7
Vq0xGJXvFz5WIUl9qb9s+rhkJMmrXb3LOWjuOLfCI5Ah5I5GaWjYmkOTxLqv
1d2ekmAauX0ceBG14vjyaOKDssmlLQ+vcfz.m8W0Nd.KTVkyknuTJJaJQ39C
cuiIzWD6YBc7rPUn64cPn2M976M9viW7IlUohDFZNs+XibBwFIdIjV6I1NLs
5hr+ZSQw2no+lI6MIubz3.wrr75xB5CGPCyopm8o3ST+Ffp+FAWdCMk0UN7J
DDIVm7IDfm7C5PP5MpN+evFg0kEGS4PzHxTrMkUyREYLsi8PWW2xU8PYJBy4
0kSGGegW.EKjvHfuHm.e0Qi81Jt3ynhqftdUFcJ0EQuBmvcR3I1tI742HDJG
VztthbNKUzvgEGLFZwV0mmoGbDVODENVZwvKgV7PxzokKuV0haZnyQvmjShO
wAwPItGLD4+QqUWb9zpIbz9L74SrFD0UqF5MtZU+KfVsOx77IVM74VsZKe9g
qUCtDZU8av20QvHWWYZ8Zd2twT5qsp87LS4oeuYl3QQouzb+PfzUYHyft2x3
n0IWTsdGRUK1gbwtt2vEGLICcA.5Jz7UFmxzFRmRbNBdmbR7NNLbOdO5itl.
+l4CXUPD+huqChBs88SR0hlpz1yx1KPidNJxX0xbNUlK3c7Q+kTH7y2SuJiU
ALVuBiQEY+8bZGx32ExwC.4HiOuKbVL.bBGAbBF.N9i.N3AfCYDvIZ.3r7.b
LkBzxx6YU0acFfP0Y5NAHahbgo4byTeXZE697V+g2eZSqTM.jpp+lJym0tYg
4sS1qU8yp3M4a0fJjeZx+g0MTrC
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
testing in context, there was indeed an issue with the previous fix, it turns out the special Flex  `<<EOF>>` doesn't function within other expressions -- (it was failing when it matched E, O, or F characters! ha).

changed now to `(.|\n)*` which seems to be working as expected (the original version was `.*` which was stopping when it got a newline). https://github.com/CNMAT/libo/commit/8ac12477cc995032c2948f88377e9c72fbc3cf68

keeping this issue open a bit longer until it's been more tested.

**Comment by maccallum** [comment]
Fixed
