### ISSUE TITLE
new default font for o.gui objects (codebox, display, compose)

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#336]
lower case `l` and the number `1` are too hard to tell apart in the courier font IMO
I'd like to propose changing the odot default font to be something like Monaco or Andale Mono. 

Of course there are others out there, but Monaco and Andale Mono are in the default Max font menu (at least on my machine...).

**Comment by adrianfreed** [comment]
monaco is a core Apple font. I am not sure if it is on windows.

**Comment by maccallum** [comment]
Windows only provides Courier New and Lucida Sans Typewriter, according to this: https://support.microsoft.com/en-us/topic/microsoft-supplied-monospaced-truetype-fonts-93aa7a47-2149-be09-31a9-c22df598c952

Although, on my Win machine, I only see Lucida Console...

I plan to switch the default to Menlo on OS X, and Lucida Console in Windows--I think they both look much better than Courier New, and they both fix the ell vs one issue. 

I'll leave this open for comments until it's done

**Comment by maccallum** [comment]
Omg so much better...
