### ISSUE TITLE
crash with o.expr.codebox

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#338]
to replicate, click on codebox.

codebox:

<pre><code>
----------begin_max5_patcher----------
407.3ocUR0zaaCCC8r8uBAcxFP0wNMMqX.65Nu6wACx1LYrSVxShtvcE8+9z
G1MYWjLeuGIejVummw6LKfiy9J6DKK687rrHT.HaMNiOJW5URWTF2TAKS1pd
y.DDJRRHXghz6zyiSFTSN12XWAZzcs2LqohR1Cr8hV8N4vvaqj9OsfyAthx.
SLOE5HOq9BpTE2plfUWUGUgCKddoC9SQifcSQfrUOJmJ72jRN1MHKNgB1zYO
Ci0RsjeHvq5hac5zI77YQvKcy5AELBicfsHYxUxcDNBkkgpVJXgqfG73eVkV
c41hPgZHNvgsQSyJJNj1ccu7vyaJ8F2LSJfh6082sH6MJiM8OwOzh6NZppYm
WUlRldaBRR4eeVo9gr+2.wE+Wzmo3aIp253l2tXzzEYerJ0qXSRp+Wn95OsP
OkJ+yMUO4Mvw8Aeb3viQ67zw6LTnPN7uPZxqpCnejmGNhZ3xooWAqCM536qv
qK+aqWRy5WDwPTmBeLFZgWwM8IDo0aLx6pYarQ7kiG3oT8uHs5YL197Pm+H+
e3ZjK2M
-----------end_max5_patcher-----------
</code></pre>

crash report:
https://gist.github.com/equilet/746b11f1cdf27224faafeac02f01b707

sys info:

```
{
	"version" : "Version 7.3.3 (5d15e6b) (32-bit mac)",
	"platform" : "mac",
	"arch" : "x86",
	"osversion" : "Mac OS X Version 10.11.6 x86_64",
	"samplerate" : 44100,
	"iovs" : 512,
	"sigvs" : 512,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "b18b859472309c31e199bdbfe0062f69",
	"MXJ Java Version" : "1.6.0_65",
	"MXJ Java Specification Version" : "1.6",
	"MXJ OS Name" : "Mac OS X",
	"MXJ OS Version" : "10.11.6",
	"MXJ OS Architecture" : "i386",
	"eventinterval" : 1,
	"overdrive" : "off",
	"mixerparallel" : "on",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "viddll",
}


```

**Comment by maccallum** [comment]
I can’t reproduce this. Can you provide more info? When does it crash? When you instantiate the box, click it, send something through it?

**Comment by equilet** [comment]
Click it, as described above.  I don't get a crash otherwise.

**Comment by maccallum** [comment]
That’s what I did—it doesn’t crash. 

Your crash report says nfill crashed with a malloc-related error, but I checked in a fix for that last summer:

https://github.com/CNMAT/libo/commit/d6e4649d8d05dc94581b7a7c566298b3a15fcb61 <https://github.com/CNMAT/libo/commit/d6e4649d8d05dc94581b7a7c566298b3a15fcb61>

Are you running a release built against the latest libo?

**Comment by equilet** [comment]
Reviewed and cleared after recent build
