### ISSUE TITLE
error in o.overview -> o.edge~ / o.autodoc_overview

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#339]
steps:
1. open o.overview
2. turn dac on 

results in error printed in window: 
`attempting to use realtime object as master clock in a poly~, bad idea!`

**Comment by equilet** [comment]
@ilzxc - any thoughts?

**Comment by equilet** [comment]
```
{
	"version" : "Version 7.3.4 (fcd0ee6) (32-bit mac)",
	"platform" : "mac",
	"arch" : "x86",
	"osversion" : "Mac OS X Version 10.11.6 x86_64",
	"samplerate" : 44100,
	"iovs" : 64,
	"sigvs" : 64,
	"scheduler_in_audio_interrupt" : "on",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "b18b859472309c31e199bdbfe0062f69",
	"eventinterval" : 1,
	"overdrive" : "on",
	"mixerparallel" : "on",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "viddll"
}

```

**Comment by equilet** [comment]
I narrowed it down a little further:

<pre><code>
----------begin_max5_patcher----------
506.3ocyUFrahCCDF9bxSgUj1aznXCID5oceE1qqppLISoFkXGY6.zV08Yes
GmnkcKEPTTUOPhlI+1+i+7XyKwQIKU6.SB4VxuHQQuDGEgo7IhFhiRZ46pZ3
FTVhD1pVtNYR3SVXmESqR48VUsp5d0FPuQ.aIe2oinRg5UvuG02wsUOJjqtW
CU1fsyySylPVfOoKJ7uXrzLxcCC4AkzJ4s.ZyOzBdy3jI6aExFvhEFcHonNT
OKWeyb5dJU81QorgrF6SMgoMYOuLhmwjTWQLjNLV6ScPnjc5c+H24+5qww9G
SNS70BFCeEb.9cJNQylhHpjhunkWJoXGfTrCSJ5GmTWDkpTssfz9FJ8SnSos
DqlKMBqPIMjkfcK.RRFgKqIRk7lmAs5HbjMiE3HhyoEXiGK65zwM6vbL6r43
E.q24DooSKj1GHMJdM4alT2XdDZ5NVGliL4NVTTjlmyJnLGklVdEOPxJ+Z0l
8Njqqx4pV0bFnZQlGO4SulPJ+yARXolzHj++8+3x0m+eImQ0qqFmpwKMH+cE
WCFqPx8mJ2SjeK2K5f6NmsStKxIzS3j+r20woSslvEN8C5zHXNN8xeyZJrsw
65b+MqYPMZhq0dsR6CmOACExP3TLTCaDi5mgY3ZWWs00R2qC8S6JKRBCUUCZ
Yu.anh8N+Z7e.7ryoqJ
-----------end_max5_patcher-----------
</code></pre>

**Comment by ilzxc** [comment]
The issue was I believe with o.edge~ but I am not sure... won't be able to review this until Saturday. 


Ilya

**Comment by maccallum** [comment]
Yes, it’s printed by o.edge~, and is an important warning, however, it seems to be printed whenever the dac is turned on whether it’s inside a poly~ or not. I suspect Cycling may have made a change to their API at some point, but I never bothered to figure out how to fix this.

**Comment by equilet** [comment]
OK, thanks for the info.  Will investigate.

**Comment by equilet** [comment]
For whatever reason, I cannot reproduce this with the most recent build.  Closing for now.
