### ISSUE TITLE
crash with expr codebox

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#342]
crashes in an attempt to assign to a bundle member

<pre><code>
----------begin_max5_patcher----------
539.3ocsT0riaBCD9L7TX4SsRzrXSHjzGfdt2Kqhb.uY8ViMBLQrMJu60dLj
xRRVkV0UJYLdlu4G+Mi8wv.7NcOuEi9J5GnffigAAfJmhfg8A3JVegj0Bvv5
EE5pZcKGG4sZ38FvxCFdqw9wwbUt4gCLo8aBMIWcZDpTn3E5NEfOYh+EZotw
WEwKHqWGMagrHF83.dcmQxMlWq4dGv3yldRqLOwJ.CwSz0J9EniPWLpV0UIT
13.GJ5fxZlo3YgZ+1FdgwGcJM05CJCjjzX2R5zxwFHeEAQhLnUT5Iqcu7EJc
732xNvK2tqSUJ4akb0dyyNTYzqYujYX9RHIMBswQBjLmvUGwfvoKlXIo63WJ
MBsD7e0fWDR5v1yfVtz9e0E9lXU8eoHbIyWDVu1jM3d7rJfDmdomzDziNV5T
XnSDc2Sqkh1ZI6U70m1HPacp3ibNib64LRBLgQyhmLnkr7uZPif+mXHdeci8
RcI2Ab9kZKLwdkQ6mJq3U63MeJ2eWOGGgb2ysk8mw251rq+cV7t7625jxuyJ
9I2Xi6zcen7N0WXq.5OIcCrPuIuSuj2Iqmx6fevKcydVERtS+aaFs5tlhQJX
78BzeReoknEJlQnUS.YyI.5pM76MSiA4cyjcpZdl7GQVc8AdS6.ZHI1IqW7c
9rHXqP42Bu0ia3GDi3WBZXM19gw1L5ZfBC2udE16pcdrQ0If1WnKymB+M3B1
E9A
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
fixed in libo, at commit: https://github.com/CNMAT/libo/commit/b22fc6e8d5104b732378189446856b9f5181940c
