### ISSUE TITLE
o.overview bugs

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#346]
`newobj: o.callpatch: No such object`
`newobj: o.mappatch: No such object`

The errors above should not occur, as the user has just installed odot and they don't (and shouldn't need to) know anything about adding the `/dev` and `/deprecated` folders

**Comment by ramagottfried** [comment]
fixed, there were some references hidden in the patch from before they were moved to /dev (not in the autohelp abstraction).
