### ISSUE TITLE
bizarro o.compose save state bug

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#349]
I'm not sure how this happened exactly but doing a bunch to debugging with an unrelated object I have been working, caused o.compose to somehow save a larger bundle in than it displays (see test patch below).

Probably this has to do with Max restoring the patch after crashing, which is unsurprising that the patch could get corrupted, but it's something to be aware of, and possibly fix:

<pre><code>
----------begin_max5_patcher----------
2671.3oc6az0chpq8Y8WAKdVsrS3qb9abe7LypKqRm5brROJN216rl+6WRBP
ALIjfJBVlkEkjcR1Ymc1eO+d5D6mheO5fs0eY82VSl76oSlvZh1vjr2mX+5x
2Wsc4AFX1wKVu4vaaW9g8LduIQumv54gCe75Swaev4gcKeMJskuY+ie7M6Ye
a2m8j7waY8rO93a05by5rA8.TqmCIKe9YVm0538zFAveQkF+HsQeb019uosQ
PUa6E5fCp03p3sw6ozCmEyrx+CV78J.s63q7eeHERTUT83SY+F9jN7bbb8cT
IvJHJusL4EEvkQeRmrGda41njjHE.KkjUFHJ4CUiRUteJkDvH4.PIq9Ax6mR
hccj2uVT6Jjziu9X56ORIUThOHERJDLVm8LpvqVHKbn0+ZQvVXhkmqERAgIa
vai18ijW3rNDWWTSvmr40HJkeeR5XbV3n2.Veb+xjMw6XiwGGHcPOuY6VJPJ
Nz2G+OQOj7xlU+ytnCLtSYDezmrmOsbuTZARS1STN6Y5j0H6IpD6I6WO3n.1
2YDFoc+g5tEcyub+zi2Pe48aHKJRaVTzorndKvHjEJbQHjxoNObgePnUnG8U
rOqu.G5KAreOGbW.DZSz2XP4y+M33SeiveKHH8EEz25L6n.7BjTdWjLlcfj9
u.sFUEN9vvTjT5vZfmGYDO+n7iKp7iQF89DiNH0tKPkcWPI6tDI2FZPVMHxH
LPfQXf.QwfHivzxr.PtQXfdFgAZZDFXhQXfNFgAMXDFzjQXPCFgAMXDFXpQX
f1BQgyQHJXnPTvTgnPaDhBMIDELRHJnmQXflFgAlXDFXfQXfZiv.0FgAMXDF
zfQXfoFgAZqaB5G5l.C0MAsR2DzNcSPS5l.C0MUCQcCNs2JHDoL1Th+mwoVg
Nx4M8IKpzFSpoWsForgXG+pMxDOVsohKkhVsrqXhtxfjIwWKNXTchzo8UhDg
W33e5R+e3uUrANQbQU3jKVoJbY6YN6iB3jt8KCz6mt4J28Gp6V3YXY.DbdVt
asNHpPKUHJoJjBz1gr1lhs00yIbXEW8wNnEMArJkbxGPU1G4iQv885mypuuO
RAGof2ZJHVkRCr.kFXQJMvhD3fOUHCVkRCrJkFXYRMw5HqBW8XnlVA7Izb+E
.5zEuQ0FXMUaf0TsAVG0FX0pMvpUafaRsAVsZCropMvZekE2tqrXStxhM8JK
tEWYwMckEa3U1QJXKnf4oha6lcQqhOtikONHDxZN9XB0Svz6r7D8Yaa88rtR
Iwa1k1IK2d4v+b7tjmWthAsSVaoalUurY2OdbezpD9z3m5SjyLKjO8oKNj8h
aXJMoX5oyzgM+O1LAnE4S1l07TI9zOmC1ehIb7jiJzF+yzozGyzNyjqhe8s3
CQ5jYRA4xPUdNjKHyowTYb14nrd1IzMEkJBN6MLfr5DDVsBGtAwYUbrUaLX2
p7Y0oIeVAUle.BL+.DY9AHRwEbpxJPk4GfJyOTDkRsh5hbeVgl7YEzz3CPSi
O.MM9.zw3CPswGfZiOflL9.Ta7AXpwGf1pNg1o5DLQ0IXppSnEpNglTcBsT0
oqugZNQlo4zygpqDbXe4kpFH8K+TwrFo3LThlyrVOr7WQqe7oi6VuM5Q9wDs
6f.+PQPrdYxRNxg8lYQBSQOHf9finzGz1bfTdOIeJ2ExM0j.13SmM.AzgRxm
WHa1n.3FlCX5nHAYvUZcbcylkrEwAm8n1piBMdE8yAL0inFWRvMeh3zEjHRf
4HgiWF8s7Go6Y1PIRn+sfl6kQF3DdT1iSw.wqmioqGpz1yof.5mh.yoH+4O+
fr4GtHyOPjh+AnKv763Jb9C3MUmIwzomPJ2SFubsUr1CGS93mxfNGnWAp0AF
0FgA76YLoApF2Ibo78xortk2NX+1cUIHGllFFwToZnhSD3LOlaMppq3PZ2jh
Q33Jgcv0siPb8DgVg.6FTdeTnYiui3aqZGCcGGyYIStEW0ZGZJQTtmXQgcGZ
ARkfd6PJEpM.zMjXIQciOGEpgUdcDVcyzR0Yxqppbi3Uel3sbhP17q9xzuUV
fkemoz3DzTrAl4GgxkOS3bcdYW.7.pmQ7eC.Nqw.dGE.Dj8aLm+LeBtMGqpI
EkTx7oOE9JuENO.nVFSxFymaovdxoqeg12bqaDnBi63juvMY5eyIzKjtr0+F
Htos6QmhKwz8GoJn.T4Hq9tlxMSAKr9AamYjAWzoWAaYXSFOeaX+pH8HCnfJ
bZEBGo3LS0gymQs.JlCOYGEBMd8ZeL34Xl2ALkBAhDh5zUH5.y2fBDWGeCpP
dM2yft6PPWOCjAYNRzkFaVf8hcX3l3Dym3Dz+vIyhwTmgVJrRIzsycVHGsta
cVnhJhqryByATmIB6h6t.Mn39YdC3Tx8AGt6Cr9741TTwUBWuR.jN4dde5uA
86hItzfYKhqjEzKaeTeLdhgmt9TXX2TxfuvclxyU80QDd4JGdlwTgkv6xiKP
w53UB28kk0gt6Zvk04pfbt94LXm60k12p8sgKn6UosEhuABnuQtWQQHTtGzc
uc88Z2qN0dxN18pw.sMFnsw.sMFnsw.s8UOPaidQM5E0nWTidQM5E0nWTidQ
YltS8q1SRmWgsjqWE1pe.uIstBaMK+OsixbMxki9FfPtxEjK4JWPtjqbA4Rt
tEjKYvTPtjdWA4RFNEjKYnVPtj6pBxkLLJHWR+rfbI8wBxkzSKHWRurfbI26
EjK4NJOAjw7DzMjhaRdBHeAxS.4qXdBHCh7DPt2KHWxPofbIC0BxkbGUPtjA
cA4R5gEjKoGVPtj9YA4R5mEjK4dufbI2UoRlLlJ4wTIeKtFzKSkL4KPpjIeE
SkLYPjJYxvLUxsvlEiuIHk4.Quy6WNrCWA7RatWArtLJbpvIpdpVkz2V3zlT
GKZaFMavpednugvKwBHMf+X3BL8RrFOHWywYu.RTP4JwtyVvEnYFH0mIvXTP
qDzYRgG3ZLQ3rRplqomp8+LsWUHwEQz5441biHTqko5lce8jPL65bgXinVVo
Z75eGTynm0cH9kNtecFlqmLGoFm11HBe9T7tI8+mMdhtpx.ZKRA8PjxPSH5N
DyPSO75JDq+GTuKhBgqbT875NQVWsZ.H6a1RkG.NVvrjjq+N+X7JDUJAGqtg
8kix9PB+uUaxyIjTt7RiiUOGgnahgEcSLotb1+zW++F3nr+QY+ix9Gk8OJ6e
T1+nr+QY+ix9Gk8OJ6evJ6W+rYA8fzpBW6zpBW2zpBW6zpBW6zpB29zpB27z
pBcbZUgASZUgKeEqHM+kWNr5bxs5be37RtJLTStJLXStJLPStJLPRtJzGStJ
zGStJzWStJzWStJb2mbU3dJHKvW1fr.2aAYA9JDjE3KYPVfgQPVf69.rOJ6e
T1+nr+QY+ix9Gzx9s99zISl7moSoOr99roSr2tYWzAaq+x5uslL42ztseaYx
pWnsSadRVqSrODeb+pHNn1wO8y4PnMaNmw6eczgjM6VlrIdWYfrEutKe6seE
s+PFvr0v90k+LdO80fYrW2ri+Jl859nesIGdWVKK2u5kMIQqRNtmgW1u66Zy
GZ75n86Ntg1JLktx+Y5+GUTB8lC
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
Yeah, if you copy the o.compose and paste it into a text editor, you’ll see that saved_bundle_length is 7768 bytes and saved_bundle_data is huge. The fix for this would be to regenerate the text from the bundle, but there’s a reason it’s done this way that I can’t recall. Ilya may remember…

**Comment by maccallum** [comment]
Fixed. When a bundle is found saved in a patcher, we now call doFullPacket.
