### ISSUE TITLE
scale() check

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#354]
I'm seeing some unexpected results from scale(), might be a floating point error?

here's a test patch:

<pre><code>
----------begin_max5_patcher----------
662.3ocuVszbaBCD9L9WgFNY2hwHA9Ulgq8bu21oCAqjpTrfADYvMS9uWoUR
DrAOF6j1KZ7tZ0956aWyKSbbuOugV4htC8MjiyKSbb.UJENFYG28IMoYIUfY
to462S4BWO8cBZi.zKnUh6rZ406yqEYTA7l.i1hDQ5uX7G+YIMUniINZsefG
hrTctJD9cfe.5Glmv1ANO+9mliCrdunjVISgDAKmOfuVoNCLGsdRlRLtMivF
kUhCYTHBtJEuNYh5v6c1JnMExjht6FZGKwPIfIWter08eWkk6uiUUjkbnWss
fwWHCGDouyAojFkTfRTVklaC7ak026aLuLg+HUpXq8dqBsEJZj04UoIYTIVW
mI.OZSlLFmllWygLZyf8Xaa3gbt3gjT53ngga2nYP.cDS11oyq7TE6Ofm.3o
GfDdA9IIbK380QCRP0Yu3PAUatq6Y3t2DdJ4jk9o46nJCOGnFeDnFeBnFeBn
FqgrtvZLx934HiSOFlkFXe9bj0ydHvK.zG2G5iQSmpur0oyPKPsQcF5SnNg3
ys9cP9BNXPBC4lHLjPfvDsVSXhBOGgAODgIZjDF4Ffkigv7k5rrulj9apbkz
QRejDoytXn2jKtcM.HRjhy23SVuIhP6rM+HzI7CbZFSfsngX3ODVgupgYxkv
lHXJNLXy3vl+iCy8livRI3GSQvkxVimb+qBbjivnYcfnALDG7lkWAlcaCTl8
vZHa4pqZbBeQHCfIRT331+9NFm.KftzIeaET4J8GiuU40ko13ZVMfdK01IwB
FGpmN1DpsYPFzXiCdDwgzKN5xKon3YZYkwXHDRh5S4kJw0dfHiqEANhaI8Yl
09HPSRojHHjPTco9qUZVo2J5tWRuK40LSqUF4Wm7WfVOa1A
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
Wow, that’s so weird. In the source code for the scale function in osc_expr.c, there are two values that get computed, m, and b. m is declared as a double, and for some reason, b is declared as a float. If you change b to a double, this problem goes away.

**Comment by ramagottfried** [comment]
oh cool! nice find — are you checking that in?

**Comment by maccallum** [comment]
Yeah, I fixed and pushed
