### ISSUE TITLE
o.gui.attach update tests

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#357]
~~~1. currently o.gui.attach seems to fail to read GUI objects that have been changed by pattrstorage.~~~
2. there's currently no way to tell if o.gui.attach has successfully set a value, or successfully attached to a new object -- consider adding a unattached outlet to provide more information about the attached state. this would mean not unioning unmatched addresses.

**Comment by ramagottfried** [comment]
issue 1. above is now fixed.

**Comment by maccallum** [comment]
@ramagottfried, did this ever get dealt with? Can you comment or close?

**Comment by ramagottfried** [comment]
it's been quite a while, but I believe this was a suggestion you made, and has been implemented a long time ago. There are now three outlets, the middle outlet sends out errors, and the rightmost outlet is a delegation outlet where unmatched (unattached) messages are routed. Seems to be working fairly well as far as I can tell.

The big change was that previously the object was union'ing the attached addresses with unattached messages -- but I think the updated design seems right, and makes sense that the delegation outlet handles unattached / unmatched addresses.
