### ISSUE TITLE
strange map/value() behavior

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#358]
not sure what to make of this:

<pre><code>
----------begin_max5_patcher----------
1001.3oc0Xs0aaCBE94jeEVHUo1TmXiuVOo9vdYOu2Wppn1zT2Yarrwcoqp+
2Gb.mKM2rSSl1jh.Ab9NG36.efyaCGfdfMmViL9hwOLFL3sgCF.cI6Xft8.T
NYdbFoFLCwlPmWVMIlkPkFZpLgSmyggsxRq4F2ZjSJuzHij+PB4RhowKjrF5
kjqtxzXFkSRRpn00z5Kux3pVWTR3wOkVL69JZLWMivg3I1lFN9gPUnirxUTZ
bmFDqgmQ47WKoJDnu0jk8cR7Oobj4ZsV.onIOsP.BVNXcmOxJ3ORhAuXuRe0
o+F5CKC8B7pnBNvQ2aZhhcd34wXGzJdnfjCd.80pTRFRNv6CGJKL6HiWP+kv
savzrI0zLAUY.T99XQWfEcCtQVgssAxburXu3tCSH31YWM+0LEabLDAaRRZc
YF40crqSL0mhtdpXxOEMVUoaYopF04JqaWz7tCSsd3HYkOFnVWu8Rs6mLKEG
LnEbBOkUrZf77fr1MPkstXgqN5su3sjsrOtby9kE3zZNVnKnDB1PDvbZAXhy
RSDIgDVrULgSmwpd0JmvexhURqHbVkEoJk+TNkmFacwTzRUjrzBZLqofu5dw
sk4vvoAeWWHA54CUA+iKsDcbolXVdIqltYVoiDrv1oHAMiNLeZqzZBCfsqGy
IAmyvd5vEBPjWnI2+PSQRF89LZwL9SRiBc113IDNQMWc8MMhtQHdhCkEJYTY
grOar3vXG946H1gE1BEKPEEo5QVGAdNP6Orsq1FL1ST3fawttod5tUV5zhVh
YoUKbCDqvVeZ6upa.OqQGnGsc94Ft9JwSZO1us4JCab2oUWumaPakQverCmO
tEdMcB2CuuNB1PGpD5CvmAE9PHPt99mcEd+yg.+Ju6aJBjvk2f1mG6otK0wV
IcX6d1dr2tx.N.06DDcZy.aQG28z9BwO8AnqgiGWqNuzMHiAHi6CjQ.jQ8Ah
E.wpOPVSLniKe85ueDflA5EEb8spHcauhjBz3dAZjBzndAxRAxpWftPA5BMn
+FOEeM0awkY6TTwWIiD4LQbakmM7AjN3Oi78I8o1Gyg8bgXJY1lOlSjrFKRV
F6LQcXsWwyafpnt7IhG90aG0cSAa4aEOwhka6hr8PJdv8AXe6+K92GB5FaAS
H3bzG92e.hP1+5TXMqoJtcYpuByXISjHdiUZAbi5J1fWyFVUBsBVhaMq00.G
zg.qmbep3fwcYEZeBhTmnxcvk3OUji5Pj8OAqvvNDmnSPb76xlifMBj5v.or
7EZUs1XHFBkimY.OGZBMSKTMguX.UQeIs0d3RHDoRnhvERHMUpCdyC7PJnB8
lphlTcRSD42G9GHLNToO
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
seems not to be the ordering:

<pre><code>
----------begin_max5_patcher----------
585.3ocuU0ziZCCD8bxuBKehsEHID9nTINzK8buWPUFGufoN1Q1NTnq1+60e
jra5lzEnJ6JjXxL4Y+RduYbdHL.tUbhnffOC9NHH3gvf.WIagfp7.XN5DlgT
NXPN4WhsGfC82RSNockEiUDFAqAQZhRWeadYNkyHZ2RSpJVfz38T9teHM38T
mjlLNdHXx7Y1PRbrKax3XvlpEQy7zr8vnjjFaunTWu+SpppzmYDG5ZbdP5yE
DOcla.fesjw9FB+Sh4YXiE2igg1+FdkBgXbFUUvPmaoENIHhQUZKaqgebsgu
0vQ9PUVjO7gqNDs5ozMCWy8jHIGeSIp9ciQ4DrnjqaJzc5t2K356QXmRGeQG
OMI0FlsXpML8SMbb6Fon+1sQIlVgNZDh6tQH4eZ6+mFM4TgbLVjQr.a41nrL
oBrBrinsWRTJhZvcOYQN6YEHGULXM7HhURrxqeU201HWALWN3kvc0pVCv7qS
eIs+7kjk9QvEKb1yxaxWRgMfxQ49gwuHoH1qO41xvZLi1CSr4FqAsizxAyD3
QXj4nqbjdejnfHQZgLBIo584DME24wYStrHFunoVN4lDwYyuUUL4FN+qGGD5
itszktvLmPkdaB0724tM2ilav6Ee2z89Yq+2RnRTJw0TTMd.d9ELyL8S4HMU
vafw9MNKnNcoqkn5M40YJtGXx1rdQll2CDcM7j1hGukgJJNRjpJvNJL82GDR
a5hgtTJ2m5NJEZN0kViepqBRZZg0l92RouO6z7oP+RMSERdI00nFZY9wv+f+
H3Sf
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
no problem when using messageiterate instead of map:

<pre><code>
----------begin_max5_patcher----------
972.3ocyX0zbhiCD8L7qPkqhpR.rkkLlf2p3vdYOu2mPskvngnYMRT1xYI6T
y+8Ue4AuCLfE3YlbHQQxs6W2O8T2x4yCGDrVbfVE.9MvG.CF74gCFXVRuv.2
7AA6HGxKHUFyBDQaXU6KHuEL09TI8fz7D3FQNLmHoaEkuA2Qju.E6okDonDR
JYxW1Qkrb3HksOGL54foOygDyjt9lKsujnVBi0gbmeyIpWTgiZXk1A2PfpwD
4ElgVLCcXpc.1KGL15fwdEzPKgdLnS7BSnESXqfdlWNXj0Ai7JnmLwD0SlbL
rS8a+sYC1uc3vPCtggGwcte6wMaxgdg63kFbG2RO+je46RW9t7dwcge4qC2v
ksDHY9opctXregNzF5vVgNxuZ.PGvP+.djE310dP9UHXjCX83plplELNMWTy
MkNwX2p75cLdAUZJ0hbK9QAW9QRNUuVras8DY9KL91+pjlKskuQIOEEOELaw
Byv745gDTVTLXUKOUw9WimP3nFmw1Xqru9SgXbvwPQkqearXWR91dpEzf.vJ
8S9xvg5eMsiMQ3z+Qg1IcPDQUzBUBAfVp4Rrx4XfTjImWjoGPww5ALtEAzNS
QmOSa1JpjuUXRxffuatOED7G0EE+II+uoxdkIjf0fBvZuY.qF.klnGlO6RD.
J67DPR2If0D9VMIn+w722DEHhnG1WFkK1P0Fdx0JHfkfsTIYylRZUEs5gGC5
iiKVwBFaHIzLilIA60oEz7KqgNgvZoV9wocDQ0blfeVRBecBIyvDoW7vCJ8x
kI5f14dS9qoZLUPTJm39PrjjjZniXsL.rH8VzJIuO0J4hBcI2arRyLqNIM8h
pE7cqV9gnQTlw1xeP0HW2UWcapGrplISdbJ3CPxTvqjhZ5CPxifU8YQGmbJA
eKEcV79TGsSUalrkxj5K.QuwV2nLrs0cxEac+Ku3iKYOgFTWHLTcgPv28xfd
WT1dL6oTK6bZQ4qqWR+ZSJssbxNK276kLRw6pyk8vkeQwt6+DeCGr7lmtyib
lPy7g.ey+.FS9oW++SgUh5x7FHZ1YAGyvMzJIiSj5d+GMxYyY2k5JP3NfCpO
.R2j75Hot7A.cuHMuqHc24TZGPZQerKg7f7bFsisYufwkNEHZdbTppqN18oj
yNcF180UYnuN6Ni6EcHraxs6mfPWifv8.RcRbk0GhqrNjR39BH70Roj9Bo3e
F6RntTWCeJR1B2j86ekVV4r1.hpK2mDk5oOM0LkwsSMeScPI8UVi8yLqPJUM
xjptX0k1tMGlOKv9ppdik7Zloc0PMxeY3+Aa+j.A
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
The behavior here is due to the `*` operator in the address being treated as an OSC wildcard. The matches are working as expected, so the addresses should probably be rewritten to avoid special characters like `*` and `/`.

**Comment by maccallum** [comment]
This is fixed now
