### ISSUE TITLE
split/join() char issue

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#359]
when you use split with an empty string you get an array of chars, great.

but then if you try to parse the chars, and repackage the string, the single `'` identifiers are used in the string:

<pre><code>
----------begin_max5_patcher----------
431.3ocsS0zSCCCC8b6uhnbofTYzV1G.R6Jm4NcBExBrrERpRSQEP7eGamUX
rABtfzT77yu9rcdsullvuy0qZ4rKY2vRRdMMIgfPfjs4I7GE8RinknwciVpa
aLhm44wpAUefpbZavCwZ9Jkw3p4401SCtMn1YqxxYYJ7v7wgKaARoyFIUyAV
.GnH9ykEUPtRfplIyvLnEZ6CQ1RfwvPXzVkzARgSxjsf5kwI9t0mTNPz0ELp
P34FUbo4b1hskt2YC2KjTghcvZ0uPXkUiFfscOpsfNzUR4mfQ0+BZiHHWAy7
sdkLD6YY0TPIV0rJJLYFFN+7QErE3y7VZJdj+mMDUeiejzsTgD+VWY9gtxbF
3h5vQ0b.igrN9S2XNasSaGpAHXsAyX9dlAnD8minxG+sVxzCsjyl9idxUcFy
0B4FU.Z+tY+SdU0u5UkiKnvEioPQwdlEMXzJu2GSjjH9WcvVWmWNrtC2FrhO
1ukp1f1JBZmcGRkQNGzWQSySJe6VxTOf2QV67X5rbJUaiomQod0S5A9iIDgG
V8.r2cdZt38SGyiOJ7lk21oo6uTryuk9NzvELX.
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
This is fixed for `join()`, but not for `string()`

**Comment by maccallum** [comment]
Fixed for `string()` now
