### ISSUE TITLE
compare subbundles

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#360]
should `==` and `!=` support comparing subbundles?
seems to me like probably this should work:

<pre><code>
----------begin_max5_patcher----------
521.3oc6V88aZCCD94j+Jr7yYk3j.AlTecOu2GUHSxQq6B1QNNnrg3+8YewY
CJgonpMoVoJAm4978S39tvwv.5VUGzPIel7MRPvwvf.DxAD30Cn64cEU7FzL
p5tB09ZUCPi5u0.cF7lY6TJ64w0x0lYFnwXUXqkmhVKmskqG6pgXTIjPgpUh
AZgGbmRZZD+DbXrj6h8vhx95X6yeJcveY6dUqoBLXMx7n0ZnAjFtQnjazPgo
uOYYqrAijjm6Nh8BxCdu5Cj4G0Pu4T5uuxlFgbHKImUl63En0C0XM2T7jP93
MyJaAl2UImk3F9Anby1VYYEroBjOZdpu0WNlAkbCuOxoysAZoMlrbmvE8XT3
vhY1taBulmDQxb9Gm3BByKN2jrL66EW4YpE5eRIvV3KA2GPuXr4d0KJBV77q
cdjdwUQqv.l8dpSHO3949TXnSDMYZIzUqsbyRvY3UbSGokqAx8Djldu8zxIo
SlpkLNUK4VjluzVU8Udw2ACM5BswISrWGYJNAIS4KcGoHY5U8c2amUZr+9Js
+uKmVt5icSeraZx6lvoCbP+E+CBbBygeIoqQ0pKFFb8KUH+YFqzRhDR7o0mY
i8Y72bk3TyCaB4wWKW0d755CftwaLlB61imUZmZdDpJj8ponpFNHFrOCQ3ZK
gyXYasZrrncKxn8tZ2WqksBjLE5x7oveAjwlR3F
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
Bundle comparison would be great, but we’d need at least two operators, one that cares about the order of the bundle contents, and another that doesn’t.

**Comment by maccallum** [comment]
Moved to libo: https://github.com/CNMAT/libo/issues/25
