### ISSUE TITLE
o.expr.codebox crash with omax_util_liboErrorHandler()

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#361]
click the compose box in the patch:

<pre><code>
----------begin_max5_patcher----------
1017.3oc6W08aaiCC+4j+JL7Sa2hc0mVVCXXusmu2uqnvM1ayqN1F9itzaX+
uejTxIMqMqNaYaX.CPPVhhhj5Gonn+zxEgW2rsnOL3kA+SvhEeZ4hEDIjvB+
7Egax1ttJqmXKrINurusJ6tvUtUaFGpJFFtqsvIlvvfK8KUOtorFVj1I2S7s
M0CuMaMwMySqMaX86Kqe2UcEqGbhQoiYqBTL2GMC+HUwrcBGkSe4+QxgKhmD
UYtyLu9CQhv81gyJcFBR7yKWhcql8odcyl1l9hIQNTrkLzvK5xpya1f1LKVx
jPaUPDKlK4PaU.PLUBM2HMzbKK3PiFpURsRQCYFCzbjSRMIooNlsFnQCMoVi
0sNSmvR9RgYMRqwILMmq4BTuL.+TZbTpUlZUWt5equnr92KadB4qJqKV2LVS
vexIFDJ9lBBodswferhSJFTcjXPO09raKxu55w57phqpJpe2v6wkkRwiwPd1
Plyvj.xXAflyMXGXWbF0gzXnKbFsHZOJRB.7aOTTbNNxRbhtZuBNac6ZIXvG
5p4LnKE79IPHh.zrVQFIFPkfgfI3bMF+HvooXPkD5vHlHN16jEc13vBVlGhr
HctfMIu87kBhijAGUikSakFJ1oVz1PMKclDJvHNtucrH49SUjQ6gsHjMAvgI
YhKCtwDq6PFowAv9vuQlchRj3zFc.btHN5sQLQMwjF5RPtbGDO1E4TrbmBEv
pIjX.dSXds6f.qdGWVmymND2+bldBH.RRI773rcJsAFYEgoR7.EvhEHgPgkX
BQ.zHLduB5UIQm3AiHzRgDS6CV79QRaFm73bOpDkpNLDW4CwYZe38ehm+S77
uUwyAW9MTwRcwGg2edP4JMwi0kM0Sz6Gtqhd8J7nky8lwpp+Na8MECOwapG8
8St0ROfR0vIt+6m26gRt8bVsVw11Nnjs7BjwGTx1Gy5CdUvEfVlyod0LvfSr
3ViLFbsvq7SUTfQdmTcE7zGGtDmuPkgfpfpSHPAApm.dNZHhvEhnLHtbzPD8
O7ybSbK3lCvhiu3Fn1S9O2KJZ5iU+Uunn94dQ40u9UHdf+xvMzD.UvIfpwKQ
HKuH3YvZ+EzC3VDQ64O+QqWW9q49lOHSxoOtDQZ6ocgi8zAej3nC7W7K0jIg
zOzWz2L1sdBA7+sPvdiJunenrNa.yWumGtmoG0cOWEgYaeZMwNGZJcNZBMG9
Nl1Tl21TVO3QwTIkfzHtWlhCmwcWYR0X5CZx2qUqmgUKNGvi9fS9QfmzyglT
y0Q7cqI1bzj9AZxc8Iqs81htdO2jRfjVenoCmZVQSKqcSozIgcE2VNwuhnj0
AY.Ffq+ictj1aSbYMC2.o55pGK8YLAM+4k+u98X.c
-----------end_max5_patcher-----------
</code></pre>

crash report:  https://gist.github.com/equilet/47939d7acb7045ccae1339513861fd22

**Comment by equilet** [comment]
{
	"version" : "Version 7.3.4 (fcd0ee6) (64-bit mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 10.13.3 x86_64",
	"samplerate" : 44100,
	"iovs" : 512,
	"sigvs" : 512,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "b18b859472309c31e199bdbfe0062f69",
	"eventinterval" : 1,
	"overdrive" : "on",
	"mixerparallel" : "on",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf"
}

**Comment by equilet** [comment]
maybe related:

<pre><code>
----------begin_max5_patcher----------
438.3ockSszSiCCD9bxuBKeBjBow4ETj1q6YtuTU4lL.lM0Nx1oJrH9uiGaG
nrTztHYMVy279yieNMgtSMCFJ4ZxuHIIOmlj3gPfjndBcOetafa7tQU4v7nN
uS0CniYAWrvr0adU+jlaEJI4GDgzVUd1YrbxJxJyH.8me9R.2oj163c.FTQD
aja6dPHueqF5rgdprccdQFopnBuZBWUk4EjMGkHi3O9DwbFhvh9P2t6wKZWp
obZuZxN.V+jTFQCP1mFgPIo+bZX3Fd2uAKM6CZuUSWhDxk7vPrWRSQQ1+MI1
o1OpLvm4OOOgMxszqu00.r7MeWNqoAYo0EnjstEuJq+VTVyooL1WQYeA0rPw
F9Ane6tIY+.rc.j2ae.MWWeJ68bKOj1pF2TbkaFXWhBbZJ7BDqfk4Hg+8orN
iT6iuAEkwPih2by0KQWhXMWcTRZqxHWvZ+b9IaN502SBzAg7u+Q4ejP7OtRX
TS5tEJLR6j2el5AiUH8elNxmV5oKKeb7.nMQm8kvsy8nRipWl4UExfZkWUCG
DK96eInbsaWx5Vjlz91hN2VSCg59tqkSh3Buqxuj9JfPrn+Y
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
hi jeff!  not crashing here testing in 64bit so far, ... are you running in 32bit mode?  or maybe and older build?

**Comment by equilet** [comment]
I posted my specs above...

**Comment by equilet** [comment]
Looks like I might be out of date:  `odot version v1.2-19_windows_beta-64-g5714c45 (compiled Thu Dec 14 22:41:29 CET 2017)`

**Comment by equilet** [comment]
Let me update and try again...

**Comment by equilet** [comment]
OK, great - thanks for the nudge.  Nothing wrong here anymore.
