### ISSUE TITLE
dynamically construct sub-bundle assignment

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#362]
<pre><code>
----------begin_max5_patcher----------
853.3ocuWE0jZBCD9Y8WgCO0NkSIg.B8GPetuW5bSDhdbERXfvUs2b+2axFP
QEOQOlaFu0Ka1ra1ureahuNch0JwVVk0ruO6WylL40oSl.pzJlzLdhUNcabF
sBLyZUsTJ3V1lo304o7LlDlCcPonVdp1J4tLF3h1EWPkwOkx27XIKVZ1CtDu
4N1y7czRLoUN62MKw3W4tBlwdqUT9Fq8Sml.APr54GBszpda5TsvdfIGm8W0
Za2eR1VoImugzEeSoaHjnHGHqwgy8TR7UyW62IuI2SdKlGKxKDUryR8EoIpu
hrV35FYYGwWrpdMnXsPDsO0xR4rXQMW1EANBrZUVTxpXbIUlJ3c.BhSfFA7V
pkNMh8oW+ETqEb4ZZLfLNWFiI9.3h7L0TlhJ2fNtW6npz+ANBoP+Kg88h2ts
XPE8EVxiqp4IYrGyX7MxmzF4g6a9Dpj1TBnNxCCT6OzRs.pF.gVmCRADC3CB
aOirDJjZVu5CgncnWqM548Pl+NZs9l4NrIbvGawINBlGgPMBENNdLMw7Zd5E
Zuf+3sWZKBHvWsUDuGe6G0YY+jF+Glr2Se7Hy1bcWrojxqUrrEEzRZdkR8qQ
7H4BZdgtPedfMLrjJY.n.iT1ulUxo4LfblTmmuKxJh+VuLTuaGdGHYqAfQ3t
jskiFYy+JjMjq+mAaqkxzRmLTOW8LJpR3dWiNiVAVpYqFiZs1I7.CSy1H9mE
z.keFkcOtoWPm.2Ge2Y+PeUh8.VKfb7cj3dZqzAR7OcWZBj24awt+Oou1SMB
Ti+Ar3PB0Djy5a4r2EgsB7g8yc0GSLOIspHit6btLYTnxv8rJhr9tW3tXxvt
Ed4s+Bsaii6ZdjFw71E0o6XQxWde8TYaKJUMVSXZCO8vPYV5FtTXZHjyxWwJ
+hFO+l9sMmbNodnyrNGClAe8NdC3MBnNlakZdgB9NvyN2VYe06tB5hyfAPEz
I+Z.X+p0eL3WIpKiaCq4cm.EpILIrJYJGdkWGa7stLM6VhC5JwwcDhS3.xGx
HDG7.hSvHDG2ADGrAa+Pwwefw4ilOACHNKOKNlxbZQwKrxpFigPn5l7rnbei
SKEG2LzEFVxdIs0dBngVpnwREGttz7rys9DKyRU8fJ40o.YcpNxuM8+.QGJf
q.
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
feature request

**Comment by equilet** [comment]
It seems that there is a bug in assigntobundlemember()

**Comment by equilet** [comment]
<pre><code>
----------begin_max5_patcher----------
754.3oc0X00aaBCE8YxuBDO0JQSwFyW6GvdduuTUY.2V2A1HvTktp9ee9CXi
z.ooqPTpTvXe4b80mqOX6vKqrbR4aIMN1ey9m1VVurxxRaRYvpqskSIdaVAt
QCyIiWVRXBGWyyDjsBs8Fhv9BFmQ1RaDR.WZesfzHVectsfaC5wSy0n4oOdE
D0aj0VRYEDgNBfNiMhmKHZvCfwaE8375rVgEYOPY2eaMISXXRXX7ZOWa+fP0
MPnm5FTVZeixmWWsRU3NCLtiiYSxQ+khiPDZHGCVbNlNIGgK77HHBch3HdRN
BV34wYhi704zlpB7yivAPbuQyHS7bEwLFbbru4PzaWxza8NNSbGNiLjfJaMz
eqsAfqO.uQwv80u9n+adS1VUuNimST.e6TrDF8dlfm1xxKHkjxTR8Eabzy5a
bbskUyU2AWNVdKYx712aKJ9AN6WDopZmVej7IbVymdlDoQN4CWBcT34jNJH5
rRFkMsLJ5qfLpKcdBTQ9mgqFAhAmGxnzokQnuPqFAfAKtNx67a0nyFYDdZYD
3qypQcpHXbxmTEIOAXEugrWlTmxjUdYCaiPdHP0vWWMUV02TMSVEsg8ZuyET
FIi2xz8PvHIX3GUWBWbcILZfrLJVkG6O.K9IR9sFkzsED18hGzcpm2X.xwBr
oe8CbsShk8IHRUn5cOcgxlGvUNTe+ewxKj1+vNu.fftl+EDBIuB2y2Pj67LH
.PyfHIZXDAdA6gDNlWwumW9i4Ux64EZGktd5Rq7dyeYWOiqruq7ug2Vm0q55
Ek1+aVOWJ6oLrfxYCAA1ADuNmTqdr+nuyczgFbLg1y.5yEIzwDI+4HRGU5DM
d5D74BczwD5v4fjIGSjhOYoycIdIMuhSYhl9uXv5.8a9pU3PlyfLrALVuUhA
ltw9SLvS.IRlARfR.GfEd6stAtp5IRcS2HQS.4FjOx0vib0MoLSSecyZxSzd
75s3bv0xcVDxsUZqMeuisglyi5TJOkRMqk1IskQ90U+AXT+ppB
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
https://gist.github.com/equilet/cf2093e839eb1176a17e4d532a2d8abb

**Comment by maccallum** [comment]
Right, `assigntobundlemember` seems to not be doing the right thing when its first argument is an expression

**Comment by maccallum** [comment]
fixed
