### ISSUE TITLE
o.messageiterate

### ISSUE THREAD

**Issue by wagne342** [CNMAT/CNMAT-odot#365]
I accidentally fed an o.messageiterate object into another o.messageiterate object and was surprised to discover that this caused max to crash.  Shouldn't iterating a list that is one message long just return that message?

https://gist.github.com/wagne342/7df0c48daa21d0eb670d9d14025148c0

**Comment by maccallum** [comment]
I just checked in a fix for this. o.messageiterate wasn’t handling unbundled messages which is what it produces. Should be good now.
