### ISSUE TITLE
Need for a 32bit output option within 64bit objects or a specific conversion object

### ISSUE THREAD

**Issue by nesdnuma** [CNMAT/CNMAT-odot#368]
Hello,

In Max7/Win64, I've just discovered that o.prepend transforms the argument of a message in a 64bit float. However, some OSC receivers, such as Reaper can't use doubles. So it might be interesting either to add an option for 64/32 bit handling in all odot objects or add a new objet to convert the argument type for a full message, already structured with tags.

**Comment by ramagottfried** [comment]
hi @nesdnuma, thanks for your note -- Odot supports a wider variety of types than the baseline OSC spec, so for use with Reaper, or other generic OSC libraries, you may need to run the bundle through `o.downcast` before sending out to OSC 1.0/1.1 receivers, which will downcast Odot to OSC 1.1 (and doubles to floats).

**Comment by nesdnuma** [comment]
Hello ramagottfried, thanks for the infomation. Maybe it should be written in good place in odot overview patch.
