### ISSUE TITLE
Max8 compatibility issues

### ISSUE THREAD

**Issue by wagne342** [CNMAT/CNMAT-odot#370]
• o.display no longer automatically resizes to fit data in Max 8.  This may lead the user to erroneously surmise that odot isn't working properly.  Indeed, I have tried to replicate some of the errors reported in the last few days but found that things were actually working perfectly, just not displaying properly.  @kulpajj Please feel free to set me straight on this.

**Comment by ramagottfried** [comment]
already fixed, we just need to make a new release.

**Comment by ramagottfried** [comment]
@equilet I guess I'll leave this issue open until we make a release?
p.s. thanks for noticing!

**Comment by ramagottfried** [comment]
actually, I think it's better to separate the bug issue from the release update issue. so I'll go ahead and close this since the bug is fixed.

**Comment by maccallum** [comment]
Just out of curiosity, what was the fix?

**Comment by ramagottfried** [comment]
it was pretty weird actually — Jeremy B helped me find it, but it's kind of a roundabout bi-product of setting editwhenunlocked to be true, at this line here:
https://github.com/CNMAT/CNMAT-odot/commit/ab132671cb10c44e73fdc1adadef89e9eafafff7#diff-564ab72ee12970005592385a08154ba3R1029

the only difference in behavior is that you can highlight the text in edit mode, which seems totally reasonable.

**Comment by maccallum** [comment]
Oh good, glad it was something straightforward.

**Comment by ramagottfried** [comment]
lol! I was more expecting the fix to be something that had some relation to the word "resize" or something... but anyway, it's working, so no complaints here!

**Comment by equilet** [comment]
Yes, I noticed this too, along with Jon Kulpa.  Thanks for dealing with it @ramagottfried - I've been out of town and unavailable.  Will push a new tag soon associated with a release and will test.

**Comment by wagne342** [comment]
That's what I call same day service.  +1 to allyalls.  So far all of my odot patches are behaving as expected under Max 8.  Quick question, should I submit an individual Github issue for each Max 8 compatibility problem, or should we try to consolidate these issues under one umbrella.  My sense is that each problem requiring a fix should get its own issue.  No?

Wishing you were here. -J

**Comment by ramagottfried** [comment]
: )  actually I fixed that a few weeks ago!

yes, I think that's best to isolate the issue reports for one issue each, that makes it easier to tackle, and also, it feels so good to close them.

are you seeing some other compatibility issues?

I'll always be there a little bit psychically!

**Comment by wagne342** [comment]
Solid.  The only report so far from the troops on the ground is related to o.collect not functioning properly in Max 8.  However, I have yet to replicate this error and I suspect it may be a display issue.

**Comment by equilet** [comment]
The o.collect "issue" is a red herring - the bug was actually in o.display
