### ISSUE TITLE
/address-naming conventions

### ISSUE THREAD

**Issue by dappertutto** [CNMAT/CNMAT-odot#373]
Is there documentation anywhere for the proper, best-practices, and excluded naming conventions for odot's addressing? o.gui.attach excludes hyphens but o.pack doesn't mind.

<pre><code>
----------begin_max5_patcher----------
602.3ocyVsrbaBCEcM7Uvn0DBHwC69Az0cealLBrhsRAIFIgqcyj+8JjfZbb
BgDrc6FKqqtVGcO5btVO45.x46HRf2W79tmiyStNNlPsAb5l6.pv6JJwRSZ.
dvJprtDuG3aWUQ1oLqbqZCUp+RTn+OX2hYqtQsgKI5Ho84VRYjBdCy7CfcAY
MUTVIQY1+ntfOvYpGvEj1XgGRj2ndYl0XUwFJa88BRgxVIIwoAg9dnzksCQI
gsCwKBB8tav1Ko+1r8QvfdDnqr0X9i2rr+LagTsulX2b.v6t1Ud10s8C+Ixa
Lxuza6IjFO.WTzTAFiKjp8kFvAfOKS.WzNjXl.gCHhAUb14thapxIhYUYv2s
xhxPlJKbrJ6u5uZr.WQTDw8DFNu7H00oUsuGHGyVeluuqwE+z6f83BeyCCSL
zT3nW8wu4U+WaJK+l9DSTeNZXJsK.WrFAnDitGhRGzH.E+gZDftn1hsXASKI
OvHWJ+RDJa.ULteAl8OvvTQjR7ZxI5jNFx6sYG37cK8ri0sr.MJ6r75oHrsI
vpKkp.9QTEo+OpJFkgNCJC3QJinvEiRQwWqWMrtgFfUJbwlYIMPueuSagmMp
kHZJ++g+HyNhbLHXdq3KdYp4T1F+XFSxaDE8.18RFuCmyUDohxvJJmMHmk1b
d06johSzDv43yBWrR6zasKyB33oC7rvIcB3DekHRzqSjQyBX3TXRX5YnDgKm
BRmdoYMC355sDgrKaCH5FEOxMTPluYJkYmZ7z.AYKsO+DSDrPawUZ+civ1RX
WpscEnhqISVCsiO0H+r6eXC1BkA
-----------end_max5_patcher-----------
</code></pre>

**Comment by ramagottfried** [comment]
ok fixed, minus signs are now allowed within o.gui.attach OSC addresses
