### ISSUE TITLE
feature request: o.display

### ISSUE THREAD

**Issue by superbigio** [CNMAT/CNMAT-odot#377]
I constantly find myself having to resize the object depending on whether the messages displayed are long or short, wide or narrow. This is partly due to the fact that when resizing o.display in edit mode the object snaps to the vertical size of the last message received. Is it possible to consider implementing scrollbars and have the object keep its vertical size constant?

**Comment by maccallum** [comment]
I sympathize with the problem here, but there's no one currently available to work on UI improvements like this. I'll make a note of the resizing issue in my wishlist for future UI improvements.
