### ISSUE TITLE
o.downcast is not present in the make-release Windows scripts

### ISSUE THREAD

**Issue by RumAngelov** [CNMAT/CNMAT-odot#379]
Hello, I was looking for the o.downcast object in the releases, but it was not included.
I just downloaded and recompiled the o.dot library and realized that it was just missing in the make-release scripts for Windows.

Was this intentional?

**Comment by ilzxc** [comment]
To the best of my knowledge, this was an honest mistake. 

Sorry for the delay in getting back to you.

**Comment by ramagottfried** [comment]
Hello all, just had a minute to check on this, and it looks like o.downcast is in fact included in the release, and also in the make-release scripts, but it gets installed in the packages's `/dev` folder which is not automatically added to the Max search path. Maybe this was the problem?  

Probably we should add some clearer documentation about the dev folder.

I'll close this now, but feel free to reopen if you are having issues.
