### ISSUE TITLE
o.expr refactor

### ISSUE THREAD

**Issue by ilzxc** [CNMAT/CNMAT-odot#38]
Documented in a session with Adrian.
### **`/math/operator/logical`**
- `&&` -> `&`
- `||` -> `|`
- `o.if /foo` should be a valid thing
### **`/math/operator/assignment`**
- `??=` to be added to `/math/operator/assignment`
### **`/math/arithmetic`**
- `fmod` unnecessary
- `det` unnecessary
### **`/math/constant`**
- add `phi`
- add `twelfth_root_of_2`
- add `thirteenth_root_of_3`
### **`/vector`**
- `sort` is not general (what happens if there's a sub bundle?)
### **`/string/function`** & **`/string/operator`**
- need to verify the API for concatenation, etc.
### **`/conditional`**
- need to document the semantics of `o.if` LHS/RHS evaluation
### **`/core`**
- `delete` needs to take a list of addresses to delete
- `imu` gone
- `tokenize` gone (or part of debugging)
- `typetags` should be `gettypetags` (consistent nomenclature)
- **type promotion**

**Comment by maccallum** [comment]
These have all been taken care of with the exception of the `sort` function, which has been made into an issue in the libo repo: https://github.com/CNMAT/libo/issues/28
