### ISSUE TITLE
o.pack

### ISSUE THREAD

**Issue by mzed** [CNMAT/CNMAT-odot#382]
I just ran into a funny inconsistency when trying to use o.pack.

I think this is related to #2 

 Here’s a patch:

<pre><code>
----------begin_max5_patcher----------
695.3ocyWt0aaBCE.9YxuBKq8XVFlagje.6489TUkC4zV2B1HiIKSU8+97M5
xVocNijzpHAhSN3y46bylGmEg2H1CcXzZz2QQQONKJxJxHHx+bDtgtupl1YU
CWIZZ.tBO28eJXuxJmrF0H1AH0crtg+rUBcZcoJlfecMiCUhdtU8TuF79FFu
FT10l3Ex1ZWQwl6+bxJ7u0TzqFTM1KcS+lM0vgurSRGaKbncZopp6X7auVBU
JGtEYKxmiJsWWEuHdNJIaQL5JyK7zrYlKymXLIYMpVHd.cGHAbnDWdlINsL0
.aY4jPlC+P6suf3VIiqXpfgs3sgcDHHKKLNdZbh8lihj+SJtoVnMbvdaxyE1
TIsATf7ZfS8oi3QIIwK0IR8yVvgAFOGg2P42hQW4U4FgrgZor30wOkjaHlPx
L2ximD9MPWG8V3EYwubiPf9DYz3RxHwEx3YQxqx9yL+FDlszbKK+BlfIYu+I
3jhbWgc5IHA+JcohERs6BHSdN3XSN934+q800eiV8.ndyT9.yoVZKVcNXteq
d2nJfo2hJOunHG0UyZBdpLo3TVh64MYocFFI8hViG+9WiSxS+XViSNe03CLe
IqwCk6UmxhaOnCE2wYmIR0mrbKhjn2kP+ibb.Wd7G6vSEI0s4zkrkM6CSGq6
bxmqF1VcWzw0udj0sGWqJImXaUWNJs1E.a9nl+5ymrKnQ9eFB5D8xpAGw2zg
he1M1BcJF29kRGni47wGnjPtEj1j9ng8Psr4br+aSSbJMMKQBvRkm.CQJBvP
livLcKkGhkxNAVJjBDBY7BDxzXLjzl4fDSOZdgpOxBAnWXGWONsscGH67JaM
gdf18Baftbt8QF28ncZLVB6XC5uzJgJ0CYT5IL8Rqag2W3lpiaD5TFum4yZZ
3zlzNrjqm02omI5dAyL0YOM6WDAQSLO
-----------end_max5_patcher-----------
</code></pre>

Using [o.pack /foo] creates a different OSC packet than sending “/foo 6.66” directly to udpsend. udpreceive doesn’t understand the message, although I can get it if udpreceive is in full packet mode.

More serious for me, Wekinator doesn’t understand the o.pack OSC message, either.

**Comment by mzed** [comment]
I understand this now, thanks to John. Wekinator doesn't like doubles, which is what I'm getting from o.pack.  Unfortunately, o.downcast isn't part of the Windows release.

**Comment by ramagottfried** [comment]
hey @mzed I think o.downcast should be in the windows release, but in the /dev folder which isn't automatically added to the package search path. do you see it there?

I think probably we could move o.downcast out of the dev folder in the near future. If I remember correctly, we recently added a blob type to deal with sub bundles. but probably there are some other pending type handling questions.

**Comment by mzed** [comment]
Super. I pulled it from /dev.

Messages created using `o.pack -> o.downcast` are understood by Wekinator. OSC 1.0, ftw.
