### ISSUE TITLE
dev folder: documentation and visibility

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-odot#383]
I think we need some clearer documentation about the dev folder, since it's easy to forget it's there. How do users know to add the dev folder if they want to use those objects?  At the moment I don't think there are any mentions of it.

related to issues: 
#274

and #329 
and #149

**Comment by ramagottfried** [comment]
sounds good, maybe it should be in the overview -- and also maybe in the git readme, or anywhere where people are reading about how what the package contains

**Comment by maccallum** [comment]
i updated the text in the subpatch in o.overview for the dev folder to explain what it represents. 

i also added a subpatch for the deprecated folder with a similar note about why those objects are there, how to install them, etc. 

i also put a readme file in both of those folders that contains the same information that's in those subpatches.

i'm satisfied with the state of this now, but feel free to reopen if there are other things to do / consider.
