### ISSUE TITLE
o.collect turns floats into 0.

### ISSUE THREAD

**Issue by matcham** [CNMAT/CNMAT-odot#385]
when a bundle created with o.collect is parsed by udpreceive (without the CNMAT argument), floats are turned into 0.
If the bundle passes thru o.route : floats are parsed as expected.

Using openSoundControl instead of o.collect : everything works fine

please see patch below that demonstrate the issue 

<pre><code>
----------begin_max5_patcher----------
1281.3oc2ZssaiaCD8YGf7OHPzGcc4Ppq8sEAXA5CsaA171tEAx1zoZqrnft
jlzE8eu7hjsjikLiijbZPPrhoFINmCm4vYjx2u9pYnk7GY4Hqe15KVyl8cwH
yTiIGYV8.yPaCebUbXtxPDew5n7z3vmPyqNcA6wB0o9osO8KIEh+JHX9WSDe
6iw7P42AxBp8N6iiRXq3kIpKhTOZZXwp+LJ496xXqJztjiSvB7bKvwQc.SkG
r8Wfs9ily8JdLOSeEXoE6+.ZZZR41njXVgBFP8na3IE4Q+CCocSbCq4kEG07
jvsJyQeHKJLdGrzlW7TJS6KHz94VdYaBWoNytoHZslPW9sezFPpA+2quRdTb
XtwKHBOcIKC0COR0LGnnQGEyPHmlZZSAMVnxDDPAK6NVR3x31X54jvbKzxvj
6aPFMwM97w8xxhBdRe311StfJfuFx10e9x.Nbd.uaPS8OePukkmGdO644dsS
wNBY.AtKbDjgOwnn.xIHi9h1ah089zZQNPFSnbnSCfgmCBB5k.HWDBvY3IfD
1eKt0OG+7EYBuhYUoCWK.2KoPUhBTaPoPPgySbf1a9u72OVFG+6gq9KVQG7j
6HjTfWzq7fsVdXhCHncFPTO98YgqiX58G2M3x6asOmW.Abb8cId1N3.e4FdT
wQLc23GcnV6HVcKI02Sx7FebfkahhiUVeWMB26lGyJ0mvv5sGb2eg9cK5yrK
QHgqk4Id38kFzxhxBdykqNLKMimxyJhD6WoLxY3i02Ut0YVrU.QUj.IPIH3q
kEbG8rAxzIOVtNU.WVzCLKeLlhLfLzUdF3cdphuXx30TEX2fNmkrVDUH.g3G
PhcaCvdcU2T+yC7GqLW5qnbuIruC2p5Fkg+Rh.+tsuCRvHrq69s5sbwV1.lP
wDr+YrNDPzRRzoTRh3cwjjrt4290ObK5zglUBSftBlwWYh3OQJSTC.+XnLQb
Gd.9oTVxmEw4quQFFwiMAZX0VM.LZ0g+oOeysQaY2F1QyovqPQXSLW3N8ASh
sVR08M2Sh.1WHxFd11PkC6Nhko8CvbKk6bZ5xVGTfcllNT.OzT2aN06RzJFA
dS2aN08MRu4DBZDSD5uIcpmWimgm+DkBPnWpZ.HFDQLwskPblnM+MA6fGd32
7GONw2xDcQKIVsaM+.Y+VUCSO8ipCZr1KEJG48BvibCB1hFqDE+3PsOiF0DL
hyj+HK7GdogIr2VvVm33WUno6622oFZjkpgS2tVUNKwEOosqQmHAav.rOJB1
+u3wHAdR0opGez642dMLBwa7EBhIVxkFDho6Z123rqog1ZvPOqBJsUpXoC++
uPgS4INf1x4kYqpmF8MUDnre5VyxKhRBqeICeYWsMsrhmsloB2vcujMvdPGN
.LUNfH7rkUMx3.cxl5ERYePF2NGkL.NpM1HO0Sa0.LgTWSlP4am1BFtIDN4D
ZObSHXDBIC2DZx742lEFzfHib.6QLe2HG3vHuAMgm3ajjSvk2E75HPXHVGHF
o6Q8GwPAybA4yQ4nr.LctPW6+LDYjDhQhdzASC5PzzAlgAaBg.iDcfQjjMyE
niYgNl4BjwT4qt1f9cAmKtG.Ai45.YhKiBvWbVGOnrdUiGgooOvxxqtI5YWz
X12zEF6OW+8nD820cBgxXODUeI5FeQgYhdxJDMjUloaO5Q2pNkQa4BWHoLpl
Hj3WN0pd+jsSkmV0SopGwquRXv+Q2c5yJ
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
Hi Mathieu,

The odot objects in Max default to using 64-bit doubles by default, instead of 32-bit floats, so this is expected behavior, even if it seems a bit weird. You can send your bundle through o.downcast which will, among other things, convert all doubles to floats.

Best,
John

**Comment by matcham** [comment]
Thanks John for this fast reply

ok, I understand the problem...
adding o.downcast after o.collect does the trick, thanks.

best regards
Mathieu

**Comment by matcham** [comment]
BTW : there is not o.downcast.maxhelp in the latest release
(it used to be in a "dev" folder in some previous release)
(but the external do work fine)

**Comment by maccallum** [comment]
Strange about the help file—I’ll look into it. Here it is just in case you need it.

<pre><code>----------begin_max5_patcher----------3320.3oc6cs0aaiiE94jeED9oTrNthWDoTwNKlEyhceZvL.SeZaKBjsTRzrxRdkjaS1A8+9xaxVxVWnbLscmlhFGKQc4vOdNemCIOj4Ot9pIyydJpXB3cfO.t5p+35qtRdJwItRe7USVF7zhjfB4kMIM5KYy+8ISUEUF8To7zq.kwKiJCd31xnhxphSWuLacYRTo7dczmcUP4hGiSe3t7nEkp2MESl4LE354J9EzwQ7KD+Svmz2Tbn78ve22BY0d9wos93ix00Ack3pI2GmD84n7h3rTQQvo5yGrZUsSeUsaQTy+8L4Cxa5lSEmpNEbyoxi9b7tOV9yMmWIK40v04QRQ+IJYx1GSVXTd55X48nN4WutRjjncZvxnhUAKT2rnQop3svF1SfSLeEnwjXHyisE13slOjjs3+DEVCgtZR1pnz3zU4QEQokAkZYeSwgQ2GrNo7t6yRKKh+eRI.hl0Z42qkvVKTTGjh+eOONHYSE3g73vrTgPznkPb5pW2G.Pkpfa8Ji7JRCV0xMyUL3vRGEVvqjqKlGjKZnlmHeCnpBKyxRZVzl6KI59RcwqhSS2AEKyV0cg4wO7XO267LdgK66YKKo3t0opRuiqSTdWQvmah1kAIIZSxlO9mBRiWFTFILKkUWmMEFkFvqnOVrHOKIoQ8UUxmaojPtN9hnuDGV9n7EUWYfe4wqpThlroUNL9AAUPiywIHJZdlhxmUfdsSsdt1F9txnkqR30hlWPCRq5Fr0IuZb9cHw3VVEAODswbrNS1+bcRxuFvMYJATGtUEE5f7XHhOg5RqeGIwoQKxVmJuM2ZEzj0CVqD0oKedkVGexjM51cPLhYRy.DjI4Gk7hLZMahc3FcgSZJIa4GQUm+qWec0Wldf.X1rnmVkOaAmEqFyTCb7s2mkA9APC4oCBk8AMbef11VnIS64ngfVBBNycJvSwgJQVLZGjsMFtcPbh+IAwmulSXjN4vTylGj9fo3AR46kT8YWZZDuNq2vFunbtSfRtsrhbQhjGQboQ7HM0.yloiIA7VIK3gnHB24lZ2i1gYaqAbWo6aO4mHTO.Noa.+TAngYeIcA2QD3GeLJfGASm.7hrDUXRbG4hJlyLOwGjohC2yDy1MEimU.hwxvO7wC1rfOI1+81rrJONsb9y7PumXI+PDhhVfJ8CwFFUPmek0S.pnUVXlhJvSBprHa4Rdf8sBK+qe98ciFN8WcYNRRJBwWTqwrc6j1tUWL8jTc6KZte429o2yoldOmiByfTWhO1AAHNNPlqmGy0VZFthfz3XjGV5SEAGR0.yN2zHbn51J97erLCDWj4QcfcFxK5vftpG6f1VUHnTMySFOB1sG.z6rqroqZbaBH6VnysN9uGRdGw6c7FdeLjgQ+aqwDoPKsoIRnoMf9l+YWei2K8eiqLE9Sbm47NbN4v5MfHpewOaszGtSUdR3AST93gCya67MMuMzQMtZXGWCItQWjD2tbOs97Nh6iPN1xPx2UY5f8Mj3F8JwcSDzSifJqqgItg9WvD2tyHbcNnu0Ht0nk1zzDha2Sh91Eosoij4BpzoLAqHe+5jiGeqpGr9F5jCiOI1g1efrz0bSGHKL7RefrJAyAy6FwPChXSGGxQQxd0pmEt978c9otkCyLbJPUOsCuSkoDGP33BiLHr3c1onSy9h87XI0KTiLl6v5HtWPwGcfXxHnc0nCDIsg7FFdnm6AJ676hhRMzEEB+8be7cU4Hgqp6aC2yDnyIZt.CiKVkD7b67yYEKfBqOQU3VWlmHdZexT.24AFQXNL5ml9wz2puDCg0N6OyEwD6PUMM59Y6oFYF13mZQ+yN0vkUOKU3JwmIoVGrikryM7sJOhysFBpQIZIpAMxn4SQCNWhzy+ryjyqkQ6OwgiHz1QNe+ZLBI8xvXCNlemaHRAPln6LHJYH1.cLc.QQW.y4IuUGrw6xAZXMZ0GnZdPMnuQvyerJVrS.UFSl0G.H76p9.n.GFzrd..OMC19QMLs8uDGOBB9ou0hQSOEPufXzvmeOoW1Y4jl2jgLKKm7dMImreRNo6fhuo43z3nu2lu1BJfNRTWoTIJu8Vqhr04KppY59BAZJegQEkwoaxd8OrQTEWmQ5JiUF7LTF7snLvLEG3c9G.sjPPMTHXVDHHlpQHRPO6IElpSHxdS6IEDSkBapZVAzCKE1zHs5gOnTHRUdqYgHxXD.x.o.uuBTVdnZ4KAOyhFSAPsIZN1QzLroiZQ8GroVzhLnZG3YYb3pr3zRsOOhmbR8ID3LF+2TOusGZKoGaXiK5j23ZrnA8O0lDXS4LP1j+zX5SKJCHS8ph7rsT.MQJbsoTXJS.xlQXfLMXKQxtbZsnMVzP3SsEckhwvhlM8kfL0jFaUMHS6xfMEBnoDKh7aqe2pdT0BUymIcqBcnjsGaKw2zVRaRKBMskDYSgvTekPqJEl5qD0Myiy4UxbN0bhlJY8PV29v8bc8sufIh0nd3cp0i+cAkk4wyWWpFFn56GCiZci+PR17fD8pBeyXh0xxJ+5sBm7SEt8h1XKJVOe95zvjMKirwusVnRYig1VKnutsVTknKta2WKXNxCnNvW2VKdcas30s0hCMUT3wOMPRxNvpHxSNMADUN3SIufrO6O8I1nmdVEUz9PxExT.On9gNYBJN7UZFVlhzXk5gASrD4xnhKnSts2bCXnJNySsAhfmAwXrC2Wu7eP1Tf2fqSEn6Ye8EtMJGPPdDXQVJO7gxnPPYlHGjlyC.6l2bvvChv1tKqTsvcbN2IeU1LNhrJqnmUVv6.T5LpHyG3tsDudGw24fE+6RLAyU288DV4LwGpv7DeHNmCjGIsA+GREIef3942kOq51kOxsOChXhkcPUGRwSAblClHSS3eyC8lNy9BxkVRAv6ydsod1E6V4SYroeQOIhVsBTcIQoeeWRT5CJ28PXmWTXPYfdwBeTafEMePHT+Q8KY2VWpr0k2F6BU+r2CyuRYARZ6Q4tuTT+.WTkNmqtxIdd69X18bBNN5TvEjVugCvvQLuPretFphe.pLKXvia5YblXK+iOl9wx294fj0hDHiWmfeL8qFsepcQvXoi9U9oOUsQKNd5JH8EwWgbNQ7UHGC4q1bHkHx0QtEouS0s0xGGaNLpIbXD5dOEhyziLPY.GlSSNLpRLtU.r2RQxuwKvWvK2dZIXkDqBRu.xrJ4XEazbC6ZaovjocDRtDFkenyEv.riFZ1Z7UKlX09SCEC2bzk3fxCQiaP4+SxXe25144Ve6KCVcSRvx4gA27gfOMEvus3GRu4iSdqvCpP.93DveADLETc7MR+72D7F9+lBdfetvv7nhhnhadCnpeJc3Xu8wloaG5u3MHzVWqkJ0U01tJgP2c2AsMm8s0ujVBGazsMMC6ZvPtptt1x+dyfb33gbC.SnuaUXShDueDXItcvrgM2dAKQcZq7uihSRwMMZsslqRjyoBCkpGmnwa80t4G7aV.Ap1LSHjCEQX+ICPboRZDBzo1hgeL.h6QCPZNppaom2rLRDyO6ykhJ.H5oEQqJAgYqmWa9jMBAcFDAaSuQw4p+6p.BpVevdcLAz9GMLoiISu9ZqQiA.GaqGMJO9U+En.626T0COZt26R64WWWBJeLp5OqFf4hIxRLX7hSpilRshj.7XsyZbsEIYkfr6kmSsDld4wDbPpeX0JIFiTaldJ0ObWfJw5ljEQbrKoH6c12xipl7Oe0peSuovzkgGx9FdOFkrRjqHheGkC9Q9UA1aHM6BOdLNLrQtGrCBQN.18oa+YQRTPduFmd9RMHUdg.8X8Zb5Xc8n+gF1J.YxNwEjH64SAnX8pUYxoMa9yRyurPgonJINprdyi9uqiyESsl7d3Fp+xu8ShQDcl8UK0ghqV.fTmdUK8sNN9q4YgqWHlxQfJ9bN9DTJl7w6yxWVnm6QAzbxPFEi0.HC15HS+llLKTyUaTd5JNqiJN8nUwWyq1qmzaO92eehIsbCsQerEzpDuPOMJn8oKJiVpji+ZzxUkO+2lrecsC2Q5SFjjj8kvbQxfTOG85XOB73OdLfuyFPFcOfv539wNiMfen2QbHYdc3xZs6XaZcvit0w8T05HGmrePDzLkbi3fucFNRjp6+PG0VFLdDvK9nAucFgYaaSBmygOBo9K6jWu8jy6T1k2t2NILaqj3b2E4JNXb8j2oyvvGTiSdWMmJSEPu6r6ng692OFFXBCGENuyTXQUaa9pvIbYrMGs4FZN8U6o4bTqPvCnB0bAbXW46kHdvWj30XAPNvjl1YOa2osm4pBhjHCO1SO7PMNRwJ6q+iiizo2KpZzbUCNvh0yLb9kIOFHNHzISbflnExNchiqAhi6oSbLQ4w6zINPSTdNchSi89h929d1mg3k+pGBIn16UiG3USr2qdHNYrcd0lvhdnVBpXW1YQ1IjjcVbc6rv51eQ008Bpa2ESmLIS5ZQzc8Wu9+utQ.zA-----------end_max5_patcher-----------</code></pre>
