### ISSUE TITLE
o.downcast.mxo is missing in latest release

### ISSUE THREAD

**Issue by matcham** [CNMAT/CNMAT-odot#386]
in latest release there are
o.downcast.mxe
o.downcast.mxe64

But Mac version is missing : o.downcast.mxo

the help file o.downcast.maxhelp is missing as well

**Comment by equilet** [comment]
@matcham thanks for the report. I’ll look into this when I get back into town this week.

**Comment by equilet** [comment]
@matcham please find `o.downcast` in the `externals` directory for the [current release](https://github.com/CNMAT/CNMAT-odot/releases/tag/v1.2-20_beta_3.2).  I think what you'll find is that this object was included in the `/dev` folder in all previous releases, but as such you'd need to manually include those folders when installing our package.  This will be addressed in a future release.  Thanks again for popping in about this.
