### ISSUE TITLE
o.timetag help patch example issues

### ISSUE THREAD

**Issue by arthur-parmentier** [CNMAT/CNMAT-odot#390]
Hi,

This is what I get want using o.timetag within its help patch.

![Capture](https://user-images.githubusercontent.com/37796888/81110111-646d6000-8f1b-11ea-95a8-5f13dc181268.PNG)

/nevertrue happens to be always true, and I can't see /resolution/estimate value appearing...

**Comment by equilet** [comment]
Hi Arthur, can we get some more info about the system that this is running on?  Please make sure to include system information about the version of ODOT you're using, Max., etc.  Thanks!

**Comment by equilet** [comment]
If it makes it easier, you can go to `Max -> About Max -> copy support information to clipboard`

**Comment by arthur-parmentier** [comment]
Sure, there it is:

	"version" : "Version 8.1.3 (da28f19) (64-bit windows)",
	"platform" : "windows",
	"arch" : "x64",
	"osversion" : "Microsoft Windows 10 Professional (build 18362), 64-bit",
	"samplerate" : 48000,
	"iovs" : 32,
	"sigvs" : 32,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "ad_mme",
	"audio_driver_subname" : "",
	"eventinterval" : 2,
	"schedinterval" : 1.0,
	"overdrive" : "on",
	"pollthrottle" : 40,
	"queuethrottle" : 100,
	"sysqelemthrottle" : 1000,
	"refreshrate" : 33.333332061767578,
	"schedslop" : 25.0,
	"eventprobing" : 1,
	"mixerparallel" : "off",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "viddll",
	"glengine" : "gl2",
	"packages" : 	{
		"CNMAT Externals" : "1.0.4",
		"CNMAT Odot" : "v1.2-19-gd491203-master"
	}

From what I experienced with o.display, I often have to resize the object to make hidden lines appear.

**Comment by equilet** [comment]
@arthur-parmentier could you go ahead and install the latest version found [here](https://github.com/CNMAT/CNMAT-odot/releases/tag/v1.2-20_beta_3.2) and report back as to whether or not that fixes your issue?

Thanks!

**Comment by arthur-parmentier** [comment]
![Capture](https://user-images.githubusercontent.com/37796888/81267009-0ee1a200-9046-11ea-83ff-9b6360029963.PNG)


Here it is: o.disply is fixed, nevertrue is still true.

PS: I did not try the beta first because there was Mac OSX in the name. It's good to keep them well named so that we are not confused by the zip file name!

**Comment by equilet** [comment]
Thanks for catching that (fixed).
Regarding `/nevertrue`, we're currently investigating this and will be back shortly.  Thank you for the report.

**Comment by maccallum** [comment]
Confirmed that `/nevertrue` is usually true on Windows

**Comment by maccallum** [comment]
This has been fixed. On Windows, MinGW's version of `gettimeofday` has lousy precision, so everything was working correctly, but the clock wasn't changing between calls to o.timetag. I replaced it with a version of `gettimeofday` that calls `GetSystemTimePreciseAsFileTime`, which produces the same resolution that I see on Mac OS X.
