### ISSUE TITLE
bug with int* typecasting 

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#391]
int8(), int16(), int32(), and int64() seem to have an issue casting...

<pre><code>
----------begin_max5_patcher----------
403.3ocmR00SCCBE841eEDdQMo1txZYclrW8YeWMFrioL6fFJcoyk8eW3R6b
SqIK9Bj6gC2ONm69v.7qpNdCFcG5QTPv9vf..xADzGGf2v5JqXM.MrJdonot
hsCG4e0v6LvKIqrmShSISyxmE8jLQHMIEVrqFnVIj7RUqD3S5AksaTslJtAx
eZO5JkzzH9jCXYwS5gEK8MwqquMkRFxq++lc0b+jfwnmOIOqXkvCCIolYJeW
He6EMuz3+Q1baIPo4T2EYhqfnbR7ji4w1kB4wlzgcHLzcDcw5FuqVGWpVxcD
GQ7VLHdzYEyiPGEvEH6cw0IqtYPTSodvT5onSIdzojSQoYdTZlCcTmHeTmfL
lSPF2Ix+Sm391ppGXkevM3nyh9eNTuOMC7oB5kXP.CXf+wdNTDG94tVipUWN
z9GGOz2UZIuwHjLiPIOiEwy5WklUWukqa5oCkwtZrVocgEQPnP5Cg0erluUL
veJfvzV8vXEiVMzZ3NZF1+U6BkV1J5Ga6BosjvZmjsg2T2qrv1Y3gvu.tg77
O.
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
{
	"version" : "Version 8.1.3 (da28f19) (64-bit mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 10.14.6 (Build 18G4032) x86_64",
	"samplerate" : 48000,
	"iovs" : 512,
	"sigvs" : 512,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "06e024609662aa9dc4f572b2cdddd559",
	"eventinterval" : 2,
	"schedinterval" : 1.0,
	"overdrive" : "on",
	"pollthrottle" : 100,
	"queuethrottle" : 100,
	"sysqelemthrottle" : 1000,
	"refreshrate" : 33.333332061767578,
	"schedslop" : 5.0,
	"eventprobing" : 1,
	"mixerparallel" : "off",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf",
	"glengine" : "gl3",
	"packages" : 	{
		"CNMAT Odot" : "v1.2-20_beta_3.1-8-g039c9d2-master"
	}

}

**Comment by maccallum** [comment]
This isn't a casting issue, it's an issue with the way (u)int8 values are represented as chars inside single quotes. In that example, /f becomes 0, and 0 is the NULL byte, which terminates the string. This requires rethinking the representation of 8-bit ints, so let's keep this open for now.

**Comment by maccallum** [comment]
Moved to libo: https://github.com/CNMAT/libo/issues/24
