### ISSUE TITLE
o.compose refresh bug

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#395]
`o.compose` does not recover from a red state after being set in the right inlet externally.  I know there's a political joke in here somewhere...

<pre><code>
----------begin_max5_patcher----------
671.3ocyVsziZCCD9b3WwHeYujxRBO29CnpG68pUHmjAhoI1Q9wBaWs+26XG
ytPQrfnpp8BFOu778MyXmWFjvJT6PCC9L7cHI4kAIIAQdAIw8IrV9txFtIXF
qT01hRKKsWmE2YCx2hfAQvVSq7V5OjBn.aTaSgBmEZEqqs.tqCKsjUbuxRty
z6RoRZonZfZ9SHoAkfqqhawJXqvVS50ZuilmkV9td+89oICTNaiPhvVkqoBp
DFCuC4ZfuxhZfxqxFQ4OBl2hjx0XeFIrPkBMx6rC2iFebJUNY.RSiB6zngxM
tUnjKOxhY6sfaKqEx0K84XOYNewvQoP1rG7KiyG4WVPafGi9HcsBYCZCrZVT
XgqnnA6Th93OZ3wJLhJzKe76wvC9XPFEkJpBEDUwlOMgcj+gixK30AC7+j9G
Vy+Jpw6L.GZ4MqT5VpXzHLuY2YokYiCjyzL+Rd9kXkKBywra.TpgDr5TF7DX
cuGD9zkSMJoPYJTkBTSypTXcJTmBhTXyiWDkYiBU87GlDVlbNXlGEthlAVwK
wCA4wPO6TnmwNvai3m80XhRih6819bG1mZL1aIggF0pVV3jUM3xFTt1Ve3Qe
jZZTj2G.3wafqk3VJYOgnUC63zj48WnoYRVneIOKPjym9wzY1USciefcNV5K
tlluQ4FRovs.33EMmfXNT.kPEfvJXMTCBXykAd7VjrQyutFoq.4KXeP+w+iC
S4waRm9WcXJe9+zwoPrBOB8aOIGnEu7iKAFkSWtOSdqkFdmZpPiUHCubcnUd
XBYmoPe8m0hq4r1mQm.SdW2Sn1DMObLTO0Fk1ucQZXqP1uMTqXZ7Iwd6mDjv
0T2hkZUb5Ppw1Mq+IOVqpB0RmH9jGAP5HC8qR5qSLcwViPa8fWG7KfFy63I
-----------end_max5_patcher-----------
</code></pre>

**Comment by equilet** [comment]
I should mention that this problem may exist in another issue thread but I couldn't find one...

**Comment by maccallum** [comment]
Fixed
