### ISSUE TITLE
casting functions

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#396]
`float32()` and `float64()` don't seem to convert a timetag properly.

Please also look at all of the integer casting functions....

**Comment by equilet** [comment]
<pre><code>
----------begin_max5_patcher----------
670.3ocyW0zbaBCD8L9WgFcJcJEijP7QmoW64duSmLxXEWRwRLBQhSyj+6Ur
Xhq+plPno0GfQRqza2me6yxONyCuPuQViQeD8Ujm2iy77foZmva6XO7Zwl7R
QMDFdQi0pUX+tkTMqKTkRKrFY6jUBa92KTqt1HyscmMkSBB8Qjr1mzn9mnus
6bzM1COntorOTI6NE7BgZE94MUrDxH8ha+PJ9YrMh0RqzbsTIVTBaLrcomlM
q8g+.KSk7d241epV4FnPvuGQBceBNY8SuX8SYwAIwwLNmDERRiyXDeDmBKQd
4zwMkZg8j7QTeBdiVYqK9IrChChQPE5.4lJSPtdorMvCoj4V6bHQPeBAuiit
ZtRe+6FoFIMFTJIvK1uyJs0xMh7tuSOISQOGS84lxxuHx+gzh82azoHO5jRd
KKpqJEOLR1fkDBpiLnmgwdQzwYENmrrIYushFiTT1qYrZawZ4UOqkl65+Fq.
hQX.kw4+yTPjjIjJOiUjNnxk.n8nrQxXzDZ.mQSHgzzPVBKMl42ZzMVeoKwN
wSH6rVVWKVIOhdXogjHBKlQewl0QcEdLzxQRGs87oKdxagzv3RF4NswX0Egv
qjrKv.msoY.sJY+GY1RX7.d6MSX+0Ma4uEpfVOUqXEp8miGIkvgdgzvosGX.
EOrObYg5vqmB4Z676yH05FSdOpaEVnco6RYssPIrEt6ttKln8hQaVJMm+BiS
Ivst.HxwHSdUHmNDj6h4UgCe.3jMA3DMj5IdB.hN.f3S.Ns2K3xUzTPc8zxe
Fojo.oA.D8Hb5ZuEUU2IM0aCFfvYscqF5ER8ggEptgfEC1HuqnO9HXFgwYcY
c9VMFHsvah692O30tKeZTMEaarbEmCRv1T49Oh0UasyA20YOM6W.OoSfD.
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
fixed
