### ISSUE TITLE
Unsigned odot externals not loading 

### ISSUE THREAD

**Issue by stefademo** [CNMAT/CNMAT-odot#398]
Hello, 
the odot package is no more loadable, apparently they are unsigned. 
Please have a look at the Cycling '74 page https://cycling74.com/articles/using-unsigned-max-externals-on-mac-os-10-15-catalina

I tried to disable the xattributes, but with no success. 
I'm running the following configuration. 
Thank you for your help,
Stefano
{
	"version" : "Version 8.1.5 (9359645) (64-bit mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 10.14.6 (Build 18G4032) x86_64",
	"samplerate" : 44100,
	"iovs" : 512,
	"sigvs" : 2,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "424544db2d2395f2021cdaccf81a3b36",
	"eventinterval" : 2,
	"schedinterval" : 1.0,
	"overdrive" : "on",
	"pollthrottle" : 40,
	"queuethrottle" : 100,
	"sysqelemthrottle" : 1000,
	"refreshrate" : 33.333332061767578,
	"schedslop" : 25.0,
	"eventprobing" : 1,
	"mixerparallel" : "off",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf",
	"glengine" : "gl2",
	"packages" : 	{
		"BEAP" : "1.0.3",
		"CNMAT Externals" : "1.0.4",
		"cv.jit" : "1.8.0",
		"hap" : "1.0.6",
		"HISSTools Impulse Response Toolbox (HIRT)" : "2.0.1",
		"Jamoma" : "1.0.1",
		"jasch objects" : "0.7.2",
		"jit.mo" : "1.1.2",
		"LowkeyNW" : "1.2.0",
		"max-mxj" : "7.2.5",
		"Mira" : "1.2.1",
		"Miraweb" : "1.2.5",
		"MuBu For Max" : "1.9.12",
		"mycollection-externals" : "",
		"Node For Max" : "1.3.2",
		"odot" : "",
		"sadamlib" : "",
		"shell" : "",
		"SoundDesignToolkit" : "2.2-0.78",
		"VIDDLL" : "1.2.3",
		"Video & Graphics" : "7.2.0",
		"Vizzie" : "2.0.3"
	}

}

**Comment by equilet** [comment]
@stefademo thank you for your attention to this issue.  We're looking at it now.

**Comment by andrewh** [comment]
Using `xattr` works for me.

**Comment by equilet** [comment]
This solution is temporary.
There are two more elegant solutions, one of which we're still looking at internally.  First and most importantly, when the package gets distributed in the package manager, notarization is automatically baked in on behalf of Cycling.

**Comment by maccallum** [comment]
Looks like there's a solution for this, so I'm going to close. Feel free to reopen if there's something we should do
