### ISSUE TITLE
Transforming OSC message to Max message is faulty

### ISSUE THREAD

**Issue by maybites** [CNMAT/CNMAT-odot#399]
Hi

consider this patch:

it uses the CNMAT's OpenSoundControl and Odot packages. When creating an OSC bundle with [o.compose] and the bundle contains a float, when creating a Max message with the help of [OpenSoundControl], the float value is set to 0.

interesting: when transfering it into a dict and getting the data out it is still the correct value.

<pre><code>
----------begin_max5_patcher----------
907.3ocyWssaiBCD8YxWAhmSYwXys91p9AzGZeaUUjC3l5JvFAlzzsp+6quk
VxVRJMgTURvHFeYlyLimi4kYNdK4aHsdtW59GWGmWl43nEoD3Xe2wqBuIuD2
pGlWEosEuh3M2zmfrQnkuhHbumy2Jm0UQYkDgdRgVgzB8P4Ke7BPVuQx6DaG
JvJ0HR7bMwXbddt2Y6pFKxefxVsngjKL8ll3GL2MIxOMKNKAFXufycQQpdBC
8CbuSM8WmMS0L+DQqDotg9fQi1joDswgJLARgpGQAmE.9KEBC7GM.QSI.Qgv
dHLK9jPHi7jzB+..utlvtg2wJthyDM7xAQJX.jBFFov8hz4l6qu4paoUjawq
NL1iPZrahq..3b.9thZoFIz0D2D49D2bVEVLZOPvjFqs3En2nBfvyDdaIrBW
PnrPg7GPC6wB38TpJ3.fJPuEME3ifAwwvLyURlBgomDBKn4B+0TxSi05S+5V
uMmyTlApeKJYZiHJXL1hK6o3IZe4ap0lxY3lm2t2SeevrPfAqI1RpQaiP1oz
hWSJVHMF4LVfEhF5xNgg3z4Mf63QpVRJ54cU5pAWQDjlEDFdYIYOcVgqqeqa
cuZ27D4r498c22KK30R+qVW.ULdb4Qw8mOSZ25d9cCEWNo0C.6iJGl8SfoaR
I5BgQpTMPnoXevowkqBys0k3mGFiW1+DKGYR.3vnWsp2iy6mk+E8HfHyNwHC
Of1zbgneHb+vyK2eXhtxSZzTP8y8y4U07VxDkMD1aYx4k7FiMqSYeuAzqnYe
O2QW8XBRoRLGfLxOSQFi1VRIQJKvjlg9Po9kxriRxhRBak3AMaSvP8WfEXiV
fx.WVpJrknZLamUMJYA.o6YD+Ck2H07CB0I.1l9CAgrqr4eLR+3hnv80.lxc
Nb+5FJamuz6HqjD88PmXqmLzIwhQCt+RuZdkT1++cw5UWIeW2VKuqIeqsr8S
aceOepfzJnLr5DI8FThYLCFYFqhTqA3SzCvNnSRQpcueJh1E07lBRyaml430
LXLXDMEXLXDXTaNSQX6yTT5Dnm3uozvQkcDOb1A7jzbzXBYSABgiHKD8csQa
WT2iJFXXgSUMncoheygGd9sOs2Z.UC9PQV4G8rlzzZmtVqRVnGM3Ict9UJy7
pt7uWCYMc63i0RvMxR9BY89tFCExlXyQz8p3REy5nVcKwqTkZFNEcSas8PEZ
hvYuN6e.y.Cxn.
-----------end_max5_patcher-----------
</code></pre>

**Comment by mzed** [comment]
This has come up a bunch of times. o.dot promotes the float to a double, which isn't a valid Max type. You need to go through o.downcast before sending to OpenSoundControl.

**Comment by mzed** [comment]
<pre><code>
----------begin_max5_patcher----------
1019.3ocyX08aaBCD+4To9+.hmyX1lOLz2lpzdcSZ6sooHGvMycfMBLosaZ+
uO+AzlzFHtcjtlDLJmM9te+746NyuO+rE9qE2Ra88tv6adKV7akjEFYZIKFD
rvuhbadIo0LPeN8Fw5q8W12mjdqzHWDTHtgmSZk22WtnTzXmcX.XoGH.fAwo
onvXTVDDlZDsT2o22GdHdWEiWRkFsgFjdkfKuhjS0BgCBYEVMu952gxtWq0D
Y9OX7MqZn4Rq1ihiL5Amnukg0sH7izpnSNnV3tpsk8KqZ0Obub6Xk2USsJv+
ickkelj+SpRie2Ln+b9Y56paKclaqnssjMzmRtanRuqDB+oIoc3C3j7QpgAv
wAoYIY3PP+mvkJlxvMHG3lmvAmDjqPsGJ.9LPNdJjmfLNBog5awf2Xf88Oez
FMoeOxfSTrA0YI+ef6XQL9TMk+EQGu3R0trFQ4gQ8g1sCgNraGgrq0P3wfc3
3vdo85Se4xuxpnekr4TPDcE0Jqmx1R8vpsgd47Jh7YvF.Wh8AM6rgggusbBT
XukxK7f53wpuPCE3N3mNtOv3BjBChBAIIgY1O3LMQjdLh.7hAaAKWFrkQuwc
bjNINf65PGZ9WL9TX4isLoQj6QkvGGLvPbeH33oWEhF0cTaSLAmzb2v1Ty0C
STKYKsXkxfT5dEQJaXq6j15cV7.ArvmVslZL9g76Z6tgTQkzlUTNYcIcrdqH
0022us6dZeVoeUwU6t.nKKgqr.SeengQdFwNSN9ZygJLHLy43F6UzDZhhlNc
4PAAt6rNYFTUopZGTHxVnJ3+TEC50+15Rxcif2KFupA3gJgFbnzHSwCvX6t1
Xa5CyxpWXjC7f1Pe7AA1q4gY3Uww4DTMR3jdPXSHtz32XEiHBxEU0hVpStTt
FwA4r21jwg5OoFJNHSm3NZHPDVICXcAeA9dppKRMm4b2auXOv8yxrV44TRWU
R4aj+vj2BbvATPjD6bDp7JxzF.DqargWzMZY.nx.c3GRcEoed.x3c02r6Phh
5mY6ujHys2EiFqAdB1cIBpaX78OD6+RVrXGBVcnx9RhdMRiYma+RF+IucEi4
p63QrXqnqIeXFGdiFd6XkEzVIiSzU7rynzmDROpwWvbVg5iQbbENXVygBSbB
gg6OJQSA0reF9pYBw6Onm9ZsLQShdTrj6MTzbXnZV.dLCMxNnYPewNsz7J6J
jLhmP3LXANY.3YCvXWTW57wuPWbefym+iaKnYirfBlIF93HFOeHN6k6A0muP
cVxszl19mvpJU50qsQaRWZ+Oia+uMQkeCcKa3QRrhHMpLhRU5vtFax0aS5Oj
iekPQw7N1P.TMX0p1jAWmLtstunMSl9yOSMf+B3GBFUH
-----------end_max5_patcher-----------
</code></pre>

**Comment by maybites** [comment]
[o.downcast] is neither part of the windows nor the OSX distribution...

**Comment by mzed** [comment]
Unfortunately, I think it's in the /dev folder, which isn't in the search path.

**Comment by equilet** [comment]
Hello @maybites - [o.downcast] can be found in the `/dev` folder.  Please include this folder when installing this package if you would like to use those materials - this is covered in the release notes.  In a future release (soon), we'll be including a more prominent pointer to this object, and are considering moving it to the main externals folder.

**Comment by equilet** [comment]
<img width="1091" alt="Screen Shot 2020-07-01 at 10 23 15 AM" src="https://user-images.githubusercontent.com/2237372/86273321-ecbb5a80-bb84-11ea-8645-32561ecf4757.png">

**Comment by maybites** [comment]
thanks to you all. found it.

**Comment by maybites** [comment]
hm, I was just looking for those release notes, but didn't find them. I would expect them either inside the package or on the wiki or inside the readme.md.

**Comment by equilet** [comment]
Agreed - it's not an ideal location, which is precisely why we're looking at the issue in the upcoming release.
