### ISSUE TITLE
crash with dynamic assignment

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-odot#401]
There may be an existing issue for this - if so, please close this one in favor of it - but please include a link to the issue if possible.  Crashes on my machine with latest (1.3a) when binding an int to /num and passing it into the expression.  Code is malformed, but shouldn't crash.

<pre><code>
----------begin_max5_patcher----------
753.3ocyW0zbaBCD8r4WgFcxtgXiDelNSuly8dblLBPIkTrfADt1MS9uWoUf
sSBwlZ6j1KhwK6xSu88zB9IqQ33hU7ZL5qnaPiF8j0nQPHcfQs+dDdAaURNq
FRCK3+pH9Qrs4VR9JIDtXZiHqPzEOK0DM9wKIQcAEMKxD4bI7fnaCVzH6hRZ
iZBIWWxM6M70M44emk7StBtaaSpjIS9Ql3g6p3IRSdDWxTGaD0KRewrRoScP
2pK4YKK8h8PoZyhXdUeTJrWJQ1rupXK3Rd0cbAKNGnfS68TomsnYwtgdYGf9
dc.rMBGyDOrW9G3pY7Ug5Uemsr2dC85P28XZHum1WpTFzLEQ50.3u2t040.3
4oIMw8J8kHxIo+ESSypKyYq6iTz8Rp6KDx5reCadhB++NttWF56Xb0gjo91H
WJvTWucTYM32yRL9tif2wMRY+GkIGsuefL+fFbZ.3pcM8.ut0i67c+147BVJ
rOdaCH5b3jOLG8.eajuVfCb9v7vg+qrvDJLfxi5CZ4GfEtXJeUY0zjhTtNwW
KwytuQjHUuuZlC5an43b1h3T13aVZiD2ZiTOkrGDiE1nknKPjISlismK1VD4
PEcYOEQOTQeAQbdSUtGtJkAwfFRUnPcBDJY1p43NdmmI3IEMBf79c5REulKj
LML20aF6XUBNcqBc.S1sG7b91yHDRDLE7JJbhI3SzBktV0qyRttUoTM8kr7F
93463tliU9G86EmnDUVYY95wutNa395UkxMoWEidPEi1yr5+2Tr1C8zPyoce
Pw7FhhAI.sjW8kp.J53uTFqKZpR51qceABZKNo7ZYl.Zi6lTjIodsJCFongf
zY.nfgxHxljJpRUeMqVvOMJFNDn8+r3H8EIsgiNmFGIC.5yheY.3DdFvYH1x
f2fi4fmZt0RdUcax.DpIkOV.84HaKy+pw7SX9BthuLqKe3kIXVkZbfTMKnoB
1V3UAdXSop4qUhlrViohbJHgov5Ah0ksyCfg0VOa8G.6ycH6
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
Produces an error now as expected. @equilet , can you verify and close this if we're good?

**Comment by equilet** [comment]
verified
