### ISSUE TITLE
Review the contents of the dev folder and move stable objects to the main folders

### ISSUE THREAD

**Issue by maccallum** [CNMAT/CNMAT-odot#405]
Obvious candidates are `o.downcast` and `o.slip.encode/decode`, but there are probably others

**Comment by ramagottfried** [comment]
hey -- yes I think for dev/externals I would say:

`o.atomize` -- was updated to output blobs a couple years ago in the case of subbundles, seems stable now
`o.downcast` -- I think this may have also added the subbundle to blob? or just drops them?
`o.gui.attach` -- the design is stable, and as far as I know it seems to work stably (there is room for improvement in handling a few situations, but overall ready to go I think)
`o.slip.decode`
`o.slip.encode`
`o.validate` ?
