### ISSUE TITLE
Update make-package-info.py

### ISSUE THREAD

**Issue by maccallum** [CNMAT/CNMAT-odot#406]
This script currently doesn't run, as some of the directories it expects to operate on have been changed. Is this script necessary? Is it necessary to have a script that does this? Or can we just hand-code the package-info.json file?

**Comment by equilet** [comment]
we should update it and it should be generated.  I can do this.  [Here](https://cycling74.com/tutorials/package-authoring-the-finer-details)'s a reference.

**Comment by maccallum** [comment]
Done
