### ISSUE TITLE
osc-compatability relies on two objects in the dev folder

### ISSUE THREAD

**Issue by maccallum** [CNMAT/CNMAT-odot#410]
`o.downcast` and `o.messageiterate` from the `dev` folder are used in `osc-compatability.maxpat` to illustrate methods for making odot bundles conform to OSC 1.0.

One thought would be to move the contents of this file to another `.maxpat`, and then have this file contain a note that says that you need to add the `dev` folder to your search path, along with a button that would open the real patch.

It's almost certain that these two externs would move to the main release, as per #405, so this would be temporary, and I think it's important not to hold up the release in order to review those two objects.

**Comment by equilet** [comment]
Deciding to move these into the main release, along with `o.atomize`.  Will post back
