### ISSUE TITLE
Add a "start here" file to the extras menu

### ISSUE THREAD

**Issue by maccallum** [CNMAT/CNMAT-odot#417]
This should be small, and list each of the support files (o.overview, o.expr.overview, basically everything in the extras folder), with a brief description of what's in them. This would probably be the featured page (or whatever it's called) for the package manager

**Comment by equilet** [comment]
This was my initial call to rename `o.tutorial` to `o.home` or similar.  I'll ping you directly

**Comment by equilet** [comment]
removed links to other items from the tutorial home patcher and added `o.start.here`.  This can function as a first-contact patch.
