### ISSUE TITLE
o.slip.decode crash

### ISSUE THREAD

**Issue by alexmstahl** [CNMAT/CNMAT-odot#426]
Context: Teensy sending SLIP-encoded OSC bundles to Max via USB serial. Bundles contain ~500 bytes and are sent approximately every 50 msec.

Max consistently crashes within 15-60 seconds, when this serial data stream is connected to o.slip.decode. Also seeing several seconds of latency in the decoded output, before the crash. Tested on Mac and Win10, tried many serial object and Max scheduler settings, to no avail.

Interestingly, and fortunately for my project, the older slipOSC object works fine. Does not crash and has much lower latency.

**Comment by maccallum** [comment]
Hi @alexmstahl--sorry for the slow response! I wasn't able to reproduce the crash you were getting, but there were some serious performance issues with o.slip.decode, which have been fixed, bringing it in line performance-wise with slipOSC. 

You may have moved on from this, but if it's possible for you to fire up that teensy and check this, the build is here: https://github.com/CNMAT/CNMAT-odot/releases/tag/1.3.3. 

I'll close this for now, but feel free to reopen.
