### ISSUE TITLE
odot not working on Mac M1 chips

### ISSUE THREAD

**Issue by jrmylee** [CNMAT/CNMAT-odot#427]
Are there any plans to add support for M1 chips(ARM architecture)?  Is there anything I could do to work on adding support?

**Comment by wagne342** [comment]
@jrmylee I am aware that a stable build is currently in the works.  Could be any day now.  @maccallum We have a small but growing set of users with M1 hardware and I have recruited them as an odot Beta-testing working group at CNMAT.

**Comment by puchifilou** [comment]
+1 for this request.
@wagne342 Me and my colleagues at Tripin' Lab are working on a project (spatial audio interoperability) making an extensive use of the odot library. We're about to spend an all week crash testing our solutions and we'll be able to put our hands on some M1 macbook pros. We would like to be able to make some compatibility tests on those machines as well. If it's not too late, would it be possible to include us in the beta testing group?
Best regards.

**Comment by maccallum** [comment]
I just put a prerelease build for M1 here: https://github.com/CNMAT/CNMAT-odot/releases/tag/untagged-b6a32387e96c9dc3c775

I don't have a machine to test on myself, so if others can check this, I'd appreciate it.

**Comment by puchifilou** [comment]
Hello @maccallum 
It seems the link is broken.I get a 404 error.
If you could check the link, we are starting our testing sessions, so I could check all this right now and give you some results before the end of the day :)

**Comment by maccallum** [comment]
Ah, sorry about that--I hadn't made it public. Try this link: https://github.com/CNMAT/CNMAT-odot/releases/tag/1.3.1-rc.1. Thanks for testing @puchifilou !

**Comment by puchifilou** [comment]
My pleasure @maccallum :)
I'll come back later today with our first feelings ...

**Comment by puchifilou** [comment]
@maccallum
All we could do today was copying our patchs on the M1 machine and try to start them. We were unable to make them work as we got an error message saying that the o.atomize object was compiled with the wrong architecture. Could you check that this object was successfully compiled with the M1 target?
Best regards,

**Comment by jrmylee** [comment]
Hey all,

I started using 1.3.0-5 on the M1 Max. Able to use my existing patches
after some shallow testing, will continue to report findings. If anyone has
any patches they want me to quickly test, please send them my way.

Jeremy Lee

**Comment by wagne342** [comment]
@jrmylee Can you go to Max > Extras > odot > o.overview and open each of the help patches there and report any unstable behavior?  It seems there are reports of o.atomize not being compiled for -arm64 architecture (see max window).  Can you confirm?

**Comment by maccallum** [comment]
@jrmylee that's great! Please do what @wagne342 wrote and pop open the o.overview patch to make sure all the objects load properly. 

There's something potentially confusing--I see that the release I posted prints `1.3.0-5` to the Max console. That's just a mistake--I uploaded another build to the same Github release page that's exactly the same, except it prints the correct version: `1.3.1-rc.1`.

@puchifilou is there any chance you've got another version on that machine that Max is trying to load? Could you triple-check that you got the right one from Github? If you have the developer's tools installed, you can also check the architecture(s) by opening the Terminal and typing `lipo -info path/to/odot/externals/o.atomize.mxo/Contents/MacOS/o.atomize`. On my machine, I get this:

```
% lipo -info ../externals/o.atomize.mxo/Contents/MacOS/o.atomize
Architectures in the fat file: ../externals/o.atomize.mxo/Contents/MacOS/o.atomize are: x86_64 arm64
```

**Comment by jrmylee** [comment]
Hi John,

Here are the objects that don't load properly when I open o.overview.

Happy thanksgiving,

Jeremy

[image: Screen Shot 2021-11-25 at 2.10.05 PM.png]

**Comment by puchifilou** [comment]
Hello everyone,

@maccallum I had a closer look today the Macbook Air M1 and you were right, there was another copy of o.atomize on the drive. Everything is back in order now. We managed to launch our patches successfully. We haven't noticed any strange behavior for the moment and no more errors / warnings. We'll keep on testing for a few days and we'll keep you posted...

**Comment by maccallum** [comment]
@puchifilou that's great to hear! Glad it's working.

@jrmylee that image didn't come through. If there are any objects that aren't loading properly, can you try the image again or list them here? 

Happy Thanksgiving!

**Comment by jrmylee** [comment]
Hey John,

Actually just realized those were the deprecated/dev objects.  Everything
that should be load is loading fine :)

Jeremy

**Comment by maccallum** [comment]
Thanks @jrmylee, @puchifilou, and @wagne342! I'll go ahead and close this, but reopen it or start a new issue if other problems on M1 show up.

I'll put a `1.3.1` release up as soon as #428 is resolved.
