### ISSUE TITLE
O. DOA with MaxMSP 8.6 -M1

### ISSUE THREAD

**Issue by aquamon1** [CNMAT/CNMAT-odot#436]
Odot appears to be uncompiled for MaxMSP v8.6. All O. objects are orange.[Tested on MacBook pro M1, v 13.5] 
![Screenshot 2024-01-20 at 17 07 42](https://github.com/CNMAT/CNMAT-odot/assets/8845808/e7605fbe-c229-46c9-8cab-fb4479448762)
 
Works fine with MaxMSP v8.5.7.

**Comment by aquamon1** [comment]
This has now been fixed. Update to package manager expected this coming week. See https://github.com/CNMAT/CNMAT-odot/releases/tag/1.3.6

**Comment by wagne342** [comment]
The update was just released in the package manager. Let us know if you encounter any further errors. Closing.
