### ISSUE TITLE
o.slip.encode and o.slip.decode unrecognized by Max / macOS ARM

### ISSUE THREAD

**Issue by nesdnuma** [CNMAT/CNMAT-odot#441]
Hello,

I need the o.slip.decode for a critical patch I've been running successfully under Windows but now I've moved to a Mac ARM running Sonoma. The o.slip.decode is in the package but I got an error message when trying to use it.

It would be great if this could be solved before the beginning of June. I got several concerts.

![image](https://github.com/CNMAT/CNMAT-odot/assets/6513218/6bb07ece-76ae-4c05-b5d6-c3c46280d69f)

**Comment by maccallum** [comment]
Hi,

These two objects are in the dev folder, which needs to be added to the Max search path manually. Can you check that and let me know if that fixes things?

**Comment by nesdnuma** [comment]
Hello, I just figured that out after reading some messages on Max forums. I moved the object to the regular Externals folder and it functions! Thank you.
